-- Default incident task automations (in-app alerts via tasks).
-- Re-run safe: upsert by id.

insert into public.app_task_automation (
  id,
  name,
  active,
  module,
  trigger_event,
  conditions,
  task_type_id,
  title_template,
  description_template,
  priority,
  due_offset_hours,
  due_offset_days,
  due_from_field,
  assignee_role_id,
  dedupe_policy,
  sort_order
)
values
  (
    'tar-incident-reportable-review',
    'Reportable incident — manager review',
    true,
    'incidents',
    'incident.reportable_set',
    '{"isReportable": true}'::jsonb,
    'tt-review',
    'Review reportable incident {{incident.documentNo}}',
    'A reportable NDIS incident requires manager review. {{incident.title}} — severity {{incident.severity}}, status {{incident.status}}. NDIS deadline: {{incident.reportDeadlineAt}}.',
    'High',
    24,
    null,
    null,
    'role-admin',
    'one_open_per_entity',
    10
  ),
  (
    'tar-incident-ndis-overdue',
    'NDIS Commission notification overdue',
    true,
    'incidents',
    'incident.ndis_overdue',
    '{}'::jsonb,
    'tt-check',
    'NDIS notification overdue — {{incident.documentNo}}',
    'Reportable incident {{incident.documentNo}} ({{incident.title}}) is past the NDIS Commission notification deadline ({{incident.reportDeadlineAt}}). Complete notification and record the reference on the incident.',
    'High',
    null,
    0,
    null,
    'role-admin',
    'one_open_per_entity',
    20
  ),
  (
    'tar-incident-investigation-sla',
    'Investigation SLA breached',
    true,
    'incidents',
    'incident.investigation_overdue',
    '{}'::jsonb,
    'tt-review',
    'Investigation overdue — {{incident.documentNo}}',
    'Incident {{incident.documentNo}} ({{incident.title}}) has been open {{incident.daysOpen}} days, exceeding the organisation investigation SLA of {{org.investigationSlaDays}} days. Review investigation progress and update the incident record.',
    'Normal',
    null,
    3,
    null,
    'role-coordinator',
    'one_open_per_entity',
    30
  )
on conflict (id) do update set
  name = excluded.name,
  active = excluded.active,
  module = excluded.module,
  trigger_event = excluded.trigger_event,
  conditions = excluded.conditions,
  task_type_id = excluded.task_type_id,
  title_template = excluded.title_template,
  description_template = excluded.description_template,
  priority = excluded.priority,
  due_offset_hours = excluded.due_offset_hours,
  due_offset_days = excluded.due_offset_days,
  due_from_field = excluded.due_from_field,
  assignee_role_id = excluded.assignee_role_id,
  dedupe_policy = excluded.dedupe_policy,
  sort_order = excluded.sort_order,
  updated_at = now();
