-- Default incident task automations (in-app alerts via tasks).
-- Re-run safe: upsert by id.

insert into public.app_task_automation (
  id,
  name,
  active,
  module,
  trigger_event,
  conditions,
  task_type_id,
  title_template,
  description_template,
  priority,
  due_offset_hours,
  due_offset_days,
  due_from_field,
  assignee_mode,
  assignee_position_id,
  assignee_role_id,
  dedupe_policy,
  sort_order
)
values
  (
    'tar-incident-reportable-review',
    'Reportable incident — manager review',
    true,
    'incidents',
    'incident.reportable_set',
    '{"isReportable": true}'::jsonb,
    'tt-review',
    'Review reportable incident {{incident.documentNo}}',
    'A reportable NDIS incident requires manager review. {{incident.title}} — severity {{incident.severity}}, status {{incident.status}}. NDIS deadline: {{incident.reportDeadlineAt}}.',
    'High',
    24,
    null,
    null,
    'org_incident_manager',
    null,
    'role-admin',
    'one_open_per_entity',
    10
  ),
  (
    'tar-incident-ndis-overdue',
    'NDIS Commission notification overdue',
    true,
    'incidents',
    'incident.ndis_overdue',
    '{}'::jsonb,
    'tt-check',
    'NDIS notification overdue — {{incident.documentNo}}',
    'Reportable incident {{incident.documentNo}} ({{incident.title}}) is past the NDIS Commission notification deadline ({{incident.reportDeadlineAt}}). Complete notification and record the reference on the incident.',
    'High',
    null,
    0,
    null,
    'org_position',
    'pos-gm-ops',
    'role-admin',
    'one_open_per_entity',
    20
  ),
  (
    'tar-incident-investigation-sla',
    'Investigation SLA breached',
    true,
    'incidents',
    'incident.investigation_overdue',
    '{}'::jsonb,
    'tt-review',
    'Investigation overdue — {{incident.documentNo}}',
    'Incident {{incident.documentNo}} ({{incident.title}}) has been open {{incident.daysOpen}} days, exceeding the organisation investigation SLA of {{org.investigationSlaDays}} days. Review investigation progress and update the incident record.',
    'Normal',
    null,
    3,
    null,
    'org_position',
    'pos-gm-ops',
    'role-coordinator',
    'one_open_per_entity',
    30
  )
on conflict (id) do update set
  name = excluded.name,
  active = excluded.active,
  module = excluded.module,
  trigger_event = excluded.trigger_event,
  conditions = excluded.conditions,
  task_type_id = excluded.task_type_id,
  title_template = excluded.title_template,
  description_template = excluded.description_template,
  priority = excluded.priority,
  due_offset_hours = excluded.due_offset_hours,
  due_offset_days = excluded.due_offset_days,
  due_from_field = excluded.due_from_field,
  assignee_mode = excluded.assignee_mode,
  assignee_position_id = excluded.assignee_position_id,
  assignee_role_id = excluded.assignee_role_id,
  dedupe_policy = excluded.dedupe_policy,
    sort_order = excluded.sort_order,
  updated_at = now();

insert into public.app_task_automation (
  id, name, active, module, trigger_event, conditions, task_type_id,
  title_template, description_template, priority, due_offset_hours, due_offset_days,
  due_from_field, assignee_mode, assignee_position_id, assignee_role_id, dedupe_policy, sort_order
)
values
  (
    'tar-enquiry-created',
    'New enquiry — intake review',
    true,
    'enquiries',
    'enquiry.created',
    '{}'::jsonb,
    'tt-review',
    'Review new enquiry {{enquiry.documentNo}}',
    '{{enquiry.participantName}} — status {{enquiry.status}}. Triage the enquiry and set the next action date.',
    'Normal',
    24,
    null,
    null,
    'role',
    null,
    'role-intake',
    'one_open_per_entity',
    40
  ),
  (
    'tar-employee-credential-expiring',
    'Employee credential expiring',
    true,
    'employees',
    'employee.credential_expiring',
    '{}'::jsonb,
    'tt-check',
    'Credential expiring — {{employee.name}}',
    '{{credential.type}} for {{employee.name}} ({{employee.searchKey}}) expires {{credential.expiryDate}}. Renew or update the employee record.',
    'Normal',
    null,
    7,
    'credentialExpiryDate',
    'org_position',
    'pos-gm-ops',
    'role-coordinator',
    'one_open_per_entity',
    50
  ),
  (
    'tar-employee-credential-pending-review',
    'Credential pending HR review',
    true,
    'employees',
    'employee.credential_pending_review',
    '{}'::jsonb,
    'tt-review',
    'Review credential — {{employee.name}}',
    '{{employee.name}} ({{employee.searchKey}}) submitted {{credential.type}} for HR sign-off. Review evidence and approve or reject in Workforce planning or the employee record.',
    'Normal',
    24,
    null,
    null,
    'role',
    null,
    'role-hr-officer',
    'one_open_per_entity',
    55
  ),
  (
    'tar-employee-leave-requested',
    'Leave request — manager approval',
    true,
    'employees',
    'employee.leave_requested',
    '{}'::jsonb,
    'tt-approve',
    'Approve leave — {{employee.name}}',
    '{{employee.name}} requested {{leave.type}} from {{leave.startDate}} to {{leave.endDate}} ({{leave.daysRequested}} day(s)). Approve or decline in Workforce planning.',
    'Normal',
    48,
    null,
    null,
    'org_reports_to_manager',
    null,
    'role-hr-manager',
    'one_open_per_entity',
    60
  ),
  (
    'tar-client-alert',
    'Client alert added',
    true,
    'clients',
    'client.alert_added',
    '{}'::jsonb,
    'tt-review',
    'Review client alert — {{client.searchKey}}',
    'New alert on {{client.name}}: {{alert.title}}. Review risk and update the support plan if needed.',
    'High',
    48,
    null,
    null,
    'role',
    null,
    'role-coordinator',
    'one_open_per_entity',
    60
  ),
  (
    'tar-location-alert',
    'Location alert added',
    true,
    'locations',
    'location.alert_added',
    '{}'::jsonb,
    'tt-check',
    'Location alert — {{location.searchKey}}',
    'New alert at {{location.name}}: {{alert.title}}. Confirm roster or site actions.',
    'Normal',
    24,
    null,
    null,
    'org_position',
    'pos-gm-ops',
    'role-coordinator',
    'one_open_per_entity',
    70
  )
on conflict (id) do update set
  name = excluded.name,
  active = excluded.active,
  module = excluded.module,
  trigger_event = excluded.trigger_event,
  conditions = excluded.conditions,
  task_type_id = excluded.task_type_id,
  title_template = excluded.title_template,
  description_template = excluded.description_template,
  priority = excluded.priority,
  due_offset_hours = excluded.due_offset_hours,
  due_offset_days = excluded.due_offset_days,
  due_from_field = excluded.due_from_field,
  assignee_mode = excluded.assignee_mode,
  assignee_position_id = excluded.assignee_position_id,
  assignee_role_id = excluded.assignee_role_id,
  dedupe_policy = excluded.dedupe_policy,
  sort_order = excluded.sort_order,
  updated_at = now();
