import type { LocationRecord } from "@/lib/location";

type BulkLocationSeed = Omit<LocationRecord, "latitude" | "longitude" | "geofenceRadiusM">;

/** Generated bulk locations — run scripts/generate-bulk-dummy-data.mjs to refresh. */
export const bulkLocations: BulkLocationSeed[] = [
  {
    id: "loc-northern-sil",
    searchKey: "NTH-SIL",
    name: "Northern SIL House",
    description: "Four-bedroom shared living in Salisbury — active overnight and weekend support.",
    locationType: "SIL house",
    status: "Active",
    address1: "45 Commercial Road",
    address2: "",
    address3: "",
    city: "Salisbury",
    state: "SA",
    postcode: "5108",
    country: "Australia",
    phone: "08 8285 3300",
    mobile: "",
    email: "northern.sil@abilityapp.local",
    accessNotes: "Sensor lighting at entry. Staff parking at rear.",
    pictureUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=640&h=400&fit=crop",
    capacity: "4",
    validFrom: "2023-04-01",
    validTo: "",
    createdBy: "SuperUser",
    updatedBy: "SuperUser",
    alerts: [
      {
        id: "loc-alert-loc-northern-sil",
        lineNo: 1,
        alertType: "Operational",
        showAsAlert: "Yes",
        name: "Roster coverage check",
        description: "Verify minimum staffing before public holiday weekends.",
        validFrom: "2025-01-01",
        validTo: "",
      },
    ],
    clientLinks: [],
    employeeLinks: [
      {
        id: "loc-emp-loc-northern-sil-mgr",
        lineNo: 1,
        employeeId: "emp-michael",
        assignmentRole: "Operations manager",
        primaryAssignment: "Yes",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-1",
        lineNo: 2,
        employeeId: "emp-sw-001",
        assignmentRole: "Support worker",
        primaryAssignment: "Yes",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-2",
        lineNo: 3,
        employeeId: "emp-sw-002",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-3",
        lineNo: 4,
        employeeId: "emp-sw-003",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-4",
        lineNo: 5,
        employeeId: "emp-sw-004",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-5",
        lineNo: 6,
        employeeId: "emp-sw-005",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-6",
        lineNo: 7,
        employeeId: "emp-sw-006",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-7",
        lineNo: 8,
        employeeId: "emp-sw-007",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-8",
        lineNo: 9,
        employeeId: "emp-sw-008",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-9",
        lineNo: 10,
        employeeId: "emp-sw-009",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-10",
        lineNo: 11,
        employeeId: "emp-sw-010",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-northern-sil-sw-11",
        lineNo: 12,
        employeeId: "emp-sw-011",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Weekend roster",
      }
    ],
    productLinks: [
      {
        id: "loc-prod-loc-northern-sil-1",
        lineNo: 1,
        productId: "prod-sil-wd",
        active: "Yes",
        validFrom: "2023-04-01",
        validTo: "",
        notes: "Northern SIL weekday service",
      },
    ],
    activities: [],
  },
  {
    id: "loc-southern-respite",
    searchKey: "STH-RSP",
    name: "Southern Respite Cottage",
    description: "Short-term respite and STA — two guest rooms, flexible roster.",
    locationType: "Respite",
    status: "Active",
    address1: "8 Jetty Road",
    address2: "",
    address3: "",
    city: "Brighton",
    state: "SA",
    postcode: "5048",
    country: "Australia",
    phone: "08 8298 7700",
    mobile: "",
    email: "southern.respite@abilityapp.local",
    accessNotes: "Ground-floor only. Medication lockbox in kitchen.",
    pictureUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=640&h=400&fit=crop",
    capacity: "2",
    validFrom: "2024-01-15",
    validTo: "",
    createdBy: "SuperUser",
    updatedBy: "SuperUser",
    alerts: [
      {
        id: "loc-alert-loc-southern-respite",
        lineNo: 1,
        alertType: "Operational",
        showAsAlert: "Yes",
        name: "Roster coverage check",
        description: "Verify minimum staffing before public holiday weekends.",
        validFrom: "2025-01-01",
        validTo: "",
      },
    ],
    clientLinks: [],
    employeeLinks: [
      {
        id: "loc-emp-loc-southern-respite-mgr",
        lineNo: 1,
        employeeId: "emp-isla",
        assignmentRole: "Site coordinator",
        primaryAssignment: "Yes",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-12",
        lineNo: 2,
        employeeId: "emp-sw-012",
        assignmentRole: "Support worker",
        primaryAssignment: "Yes",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-13",
        lineNo: 3,
        employeeId: "emp-sw-013",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-14",
        lineNo: 4,
        employeeId: "emp-sw-014",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-15",
        lineNo: 5,
        employeeId: "emp-sw-015",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-16",
        lineNo: 6,
        employeeId: "emp-sw-016",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-17",
        lineNo: 7,
        employeeId: "emp-sw-017",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-18",
        lineNo: 8,
        employeeId: "emp-sw-018",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-19",
        lineNo: 9,
        employeeId: "emp-sw-019",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-20",
        lineNo: 10,
        employeeId: "emp-sw-020",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-21",
        lineNo: 11,
        employeeId: "emp-sw-021",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-southern-respite-sw-22",
        lineNo: 12,
        employeeId: "emp-sw-022",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Weekend roster",
      }
    ],
    productLinks: [
      {
        id: "loc-prod-loc-southern-respite-1",
        lineNo: 1,
        productId: "prod-sil-wd",
        active: "Yes",
        validFrom: "2024-01-15",
        validTo: "",
        notes: "Short-term accommodation / respite",
      },
    ],
    activities: [],
  },
  {
    id: "loc-murray-bridge-day",
    searchKey: "MB-DAY",
    name: "Murray Bridge Day Program",
    description: "Regional day hub — life skills, community access, and transport.",
    locationType: "Day program",
    status: "Active",
    address1: "120 Bridge Street",
    address2: "",
    address3: "",
    city: "Murray Bridge",
    state: "SA",
    postcode: "5253",
    country: "Australia",
    phone: "08 8531 4400",
    mobile: "",
    email: "murraybridge.day@abilityapp.local",
    accessNotes: "Bus bay at front. Evacuation assembly point is north carpark.",
    pictureUrl: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=640&h=400&fit=crop",
    capacity: "15",
    validFrom: "2022-09-01",
    validTo: "",
    createdBy: "SuperUser",
    updatedBy: "SuperUser",
    alerts: [
      {
        id: "loc-alert-loc-murray-bridge-day",
        lineNo: 1,
        alertType: "Operational",
        showAsAlert: "Yes",
        name: "Roster coverage check",
        description: "Verify minimum staffing before public holiday weekends.",
        validFrom: "2025-01-01",
        validTo: "",
      },
    ],
    clientLinks: [],
    employeeLinks: [
      {
        id: "loc-emp-loc-murray-bridge-day-mgr",
        lineNo: 1,
        employeeId: "emp-oliver",
        assignmentRole: "Team leader",
        primaryAssignment: "Yes",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-23",
        lineNo: 2,
        employeeId: "emp-sw-023",
        assignmentRole: "Support worker",
        primaryAssignment: "Yes",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-24",
        lineNo: 3,
        employeeId: "emp-sw-024",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-25",
        lineNo: 4,
        employeeId: "emp-sw-025",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-26",
        lineNo: 5,
        employeeId: "emp-sw-026",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-27",
        lineNo: 6,
        employeeId: "emp-sw-027",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-28",
        lineNo: 7,
        employeeId: "emp-sw-028",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-29",
        lineNo: 8,
        employeeId: "emp-sw-029",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Regular weekday shifts",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-30",
        lineNo: 9,
        employeeId: "emp-sw-030",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Weekend roster",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-31",
        lineNo: 10,
        employeeId: "emp-sw-031",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Relief pool",
      },
      {
        id: "loc-emp-loc-murray-bridge-day-sw-32",
        lineNo: 11,
        employeeId: "emp-sw-032",
        assignmentRole: "Support worker",
        primaryAssignment: "No",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Regular weekday shifts",
      }
    ],
    productLinks: [
      {
        id: "loc-prod-loc-murray-bridge-day-1",
        lineNo: 1,
        productId: "prod-cp",
        active: "Yes",
        validFrom: "2022-09-01",
        validTo: "",
        notes: "Regional community participation",
      },
    ],
    activities: [],
  }
];
