import type { EmployeeRecord } from "@/lib/employee";
import type { OrgPositionRecord, PositionAssignmentRecord } from "@/lib/org-structure";

function staff(partial: Partial<EmployeeRecord> & Pick<EmployeeRecord, "id" | "searchKey" | "name" | "firstName" | "lastName" | "email" | "jobTitle" | "department">): EmployeeRecord {
  return {
    preferredName: partial.firstName,
    middleName: "",
    phone: "",
    mobile: "",
    employmentStatus: "Active",
    employmentType: "Full-time",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "",
    siteBranch: "Adelaide HQ",
    costCentre: "",
    gender: "",
    birthday: "",
    employeeNumber: "",
    reportsToId: "",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
    credentials: [],
    locations: [],
    emergencyContacts: [],
    alerts: [],
    skills: [],
    documents: [],
    activities: [],
    leaveEntitlements: [],
    leaveRequests: [],
    businessPartnerGroup: "Employee",
    createdBy: "SuperUser",
    updatedBy: "SuperUser",
    startDate: "2020-01-01",
    ...partial,
  };
}

/** Executive and corporate leadership — merged into employee seed. */
export const leadershipEmployees: EmployeeRecord[] = [
  staff({
    id: "emp-board-chair",
    searchKey: "EleWr",
    name: "Eleanor Wright",
    firstName: "Eleanor",
    lastName: "Wright",
    preferredName: "Eleanor",
    middleName: "",
    email: "eleanor.wright@abilityerp.local",
    phone: "",
    mobile: "0400 100 000",
    jobTitle: "Board Chair",
    department: "Executive",
    employmentStatus: "Active",
    employmentType: "Part-time",
    startDate: "2016-05-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-EXEC",
    gender: "Female",
    birthday: "1968-03-22",
    employeeNumber: "EMP-0900",
    reportsToId: "",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "8",
    fte: "0.2",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "Board chair seed",
  }),
  staff({
    id: "emp-ceo",
    searchKey: "PatCh",
    name: "Patricia Chen",
    firstName: "Patricia",
    lastName: "Chen",
    preferredName: "Patricia",
    middleName: "",
    email: "patricia.chen@abilityerp.local",
    phone: "08 8294 1000",
    mobile: "0400 100 001",
    jobTitle: "Chief Executive Officer",
    department: "Executive",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2015-03-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "12",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-EXEC",
    gender: "Female",
    birthday: "1975-04-12",
    employeeNumber: "EMP-0901",
    reportsToId: "",
    driverLicenceClass: "C",
    driverLicenceExpiry: "2028-06-01",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "Australian citizen",
    bankName: "Commonwealth Bank",
    bankBsb: "065-000",
    bankAccountNumber: "90010001",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "Australian Super",
    superMemberNumber: "AS-90001",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "Executive — 5 weeks annual",
    medicalRestrictionsNotes: "",
    notes: "CEO seed",
  }),
  staff({
    id: "emp-exec-hr",
    searchKey: "DiaFo",
    name: "Diane Foster",
    firstName: "Diane",
    lastName: "Foster",
    preferredName: "Diane",
    middleName: "",
    email: "diane.foster@abilityerp.local",
    phone: "",
    mobile: "0400 100 002",
    jobTitle: "HR Executive",
    department: "HR",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2017-06-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "8",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-HR",
    gender: "Female",
    birthday: "1980-08-20",
    employeeNumber: "EMP-0902",
    reportsToId: "emp-ceo",
    driverLicenceClass: "C",
    driverLicenceExpiry: "2027-09-01",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "HR executive seed",
  }),
  staff({
    id: "emp-exec-finance",
    searchKey: "JamWh",
    name: "James Whitford",
    firstName: "James",
    lastName: "Whitford",
    preferredName: "James",
    middleName: "",
    email: "james.whitford@abilityerp.local",
    phone: "",
    mobile: "0400 100 003",
    jobTitle: "Chief Financial Officer",
    department: "Finance",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2016-01-15",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "8",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-FIN",
    gender: "Male",
    birthday: "1978-11-03",
    employeeNumber: "EMP-0903",
    reportsToId: "emp-ceo",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "CFO seed",
  }),
  staff({
    id: "emp-exec-ict",
    searchKey: "SamRi",
    name: "Sam Rivera",
    firstName: "Sam",
    lastName: "Rivera",
    preferredName: "Sam",
    middleName: "",
    email: "sam.rivera@abilityerp.local",
    phone: "",
    mobile: "0400 100 004",
    jobTitle: "ICT Executive",
    department: "ICT",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2018-09-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "8",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-ICT",
    gender: "Non-binary",
    birthday: "1982-02-14",
    employeeNumber: "EMP-0904",
    reportsToId: "emp-ceo",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "ICT executive seed",
  }),
  staff({
    id: "emp-exec-quality",
    searchKey: "MarHo",
    name: "Margaret Holt",
    firstName: "Margaret",
    lastName: "Holt",
    preferredName: "Margaret",
    middleName: "",
    email: "margaret.holt@abilityerp.local",
    phone: "",
    mobile: "0400 100 005",
    jobTitle: "Quality Executive",
    department: "Quality",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2017-02-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "8",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-QUALITY",
    gender: "Female",
    birthday: "1979-07-30",
    employeeNumber: "EMP-0905",
    reportsToId: "emp-ceo",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "Quality executive seed",
  }),
  staff({
    id: "emp-hr-manager",
    searchKey: "SanBl",
    name: "Sandra Blake",
    firstName: "Sandra",
    lastName: "Blake",
    preferredName: "Sandra",
    middleName: "",
    email: "sandra.blake@abilityerp.local",
    phone: "",
    mobile: "0400 100 006",
    jobTitle: "HR Manager",
    department: "HR",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2019-04-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-HR",
    gender: "Female",
    birthday: "1985-03-18",
    employeeNumber: "EMP-0906",
    reportsToId: "emp-exec-hr",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
  staff({
    id: "emp-ict-manager",
    searchKey: "AleKi",
    name: "Alex Kim",
    firstName: "Alex",
    lastName: "Kim",
    preferredName: "Alex",
    middleName: "",
    email: "alex.kim@abilityerp.local",
    phone: "",
    mobile: "0400 100 007",
    jobTitle: "ICT Manager",
    department: "ICT",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2020-01-10",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-ICT",
    gender: "Male",
    birthday: "1988-12-01",
    employeeNumber: "EMP-0907",
    reportsToId: "emp-exec-ict",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
  staff({
    id: "emp-ict-officer",
    searchKey: "JorLe",
    name: "Jordan Lee",
    firstName: "Jordan",
    lastName: "Lee",
    preferredName: "Jordan",
    middleName: "",
    email: "jordan.lee@abilityerp.local",
    phone: "",
    mobile: "0400 100 008",
    jobTitle: "ICT Officer",
    department: "ICT",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2021-05-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-ICT",
    gender: "Non-binary",
    birthday: "1993-05-22",
    employeeNumber: "EMP-0908",
    reportsToId: "emp-ict-manager",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
  staff({
    id: "emp-quality-manager",
    searchKey: "QuiTa",
    name: "Quinn Taylor",
    firstName: "Quinn",
    lastName: "Taylor",
    preferredName: "Quinn",
    middleName: "",
    email: "quinn.taylor@abilityerp.local",
    phone: "",
    mobile: "0400 100 009",
    jobTitle: "Quality Manager",
    department: "Quality",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2019-08-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-QUALITY",
    gender: "Female",
    birthday: "1984-09-09",
    employeeNumber: "EMP-0909",
    reportsToId: "emp-exec-quality",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
  staff({
    id: "emp-rostering-manager",
    searchKey: "RilSh",
    name: "Riley Shaw",
    firstName: "Riley",
    lastName: "Shaw",
    preferredName: "Riley",
    middleName: "",
    email: "riley.shaw@abilityerp.local",
    phone: "",
    mobile: "0400 100 010",
    jobTitle: "Rostering Manager",
    department: "Operations",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2020-03-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-OPS",
    gender: "Male",
    birthday: "1987-01-25",
    employeeNumber: "EMP-0910",
    reportsToId: "emp-michael",
    driverLicenceClass: "C",
    driverLicenceExpiry: "2027-03-01",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
  staff({
    id: "emp-rostering-officer",
    searchKey: "MorBl",
    name: "Morgan Blake",
    firstName: "Morgan",
    lastName: "Blake",
    preferredName: "Morgan",
    middleName: "",
    email: "morgan.blake@abilityerp.local",
    phone: "",
    mobile: "0400 100 011",
    jobTitle: "Rostering Officer",
    department: "Operations",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2022-07-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-OPS",
    gender: "Female",
    birthday: "1995-06-11",
    employeeNumber: "EMP-0911",
    reportsToId: "emp-rostering-manager",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
  staff({
    id: "emp-finance-manager",
    searchKey: "TesNg",
    name: "Tessa Nguyen",
    firstName: "Tessa",
    lastName: "Nguyen",
    preferredName: "Tessa",
    middleName: "",
    email: "tessa.nguyen@abilityerp.local",
    phone: "",
    mobile: "0400 100 012",
    jobTitle: "Finance Manager",
    department: "Finance",
    employmentStatus: "Active",
    employmentType: "Full-time",
    startDate: "2018-11-01",
    endDate: "",
    probationEndDate: "",
    confirmationDate: "",
    noticeDays: "4",
    siteBranch: "Adelaide HQ",
    costCentre: "CC-FIN",
    gender: "Female",
    birthday: "1983-10-05",
    employeeNumber: "EMP-0912",
    reportsToId: "emp-exec-finance",
    driverLicenceClass: "",
    driverLicenceExpiry: "",
    visaSubclass: "",
    visaExpiry: "",
    workRightsNotes: "",
    bankName: "",
    bankBsb: "",
    bankAccountNumber: "",
    payMethod: "Bank",
    tfn: "",
    taxDeclaration: "",
    superFund: "",
    superMemberNumber: "",
    standardHoursPerWeek: "38",
    fte: "1",
    leavePolicy: "",
    medicalRestrictionsNotes: "",
    notes: "",
  }),
];

function pos(
  partial: OrgPositionRecord
): OrgPositionRecord {
  return partial;
}

export const leadershipOrgPositions: OrgPositionRecord[] = [
  pos({
    id: "pos-board",
    title: "Board",
    securityRoleId: "role-board",
    department: "Executive",
    businessArea: "Executive",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-org-root",
    sortOrder: 5,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-EXEC",
    primaryEmployeeId: "emp-board-chair",
  }),
  pos({
    id: "pos-ceo",
    title: "Chief Executive Officer",
    securityRoleId: "role-ceo",
    department: "Executive",
    businessArea: "Executive",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-org-root",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-EXEC",
    primaryEmployeeId: "emp-ceo",
  }),
  pos({
    id: "pos-exec-ops",
    title: "Operations Executive",
    securityRoleId: "role-exec-operations",
    department: "Operations",
    businessArea: "Operations",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-ceo",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-OPS",
    primaryEmployeeId: "emp-michael",
  }),
  pos({
    id: "pos-gm-ops",
    title: "Operations Manager — Service delivery",
    securityRoleId: "role-team-leader",
    department: "Operations",
    businessArea: "Operations",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-exec-ops",
    sortOrder: 20,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-OPS",
    primaryEmployeeId: "emp-staff-133",
  }),
  pos({
    id: "pos-rostering-manager",
    title: "Rostering Manager",
    securityRoleId: "role-rostering-manager",
    department: "Operations",
    businessArea: "Operations",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-exec-ops",
    sortOrder: 30,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-OPS",
    primaryEmployeeId: "emp-rostering-manager",
  }),
  pos({
    id: "pos-rostering-officer",
    title: "Rostering Officer",
    securityRoleId: "role-rostering-officer",
    department: "Operations",
    businessArea: "Operations",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-rostering-manager",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-OPS",
    primaryEmployeeId: "emp-rostering-officer",
  }),
  pos({
    id: "pos-coordinator",
    title: "Support Coordinator",
    securityRoleId: "role-coordinator",
    department: "Client services",
    businessArea: "Client services",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-gm-ops",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-CLIENT",
    primaryEmployeeId: "emp-isla",
  }),
  pos({
    id: "pos-intake",
    title: "Intake Officer",
    securityRoleId: "role-intake",
    department: "Intake",
    businessArea: "Intake",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-gm-ops",
    sortOrder: 20,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-INTAKE",
    primaryEmployeeId: "emp-gabriela",
  }),
  pos({
    id: "pos-plan-dev",
    title: "Plan Developer",
    securityRoleId: "role-coordinator",
    department: "Client services",
    businessArea: "Client services",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-gm-ops",
    sortOrder: 30,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-CLIENT",
    primaryEmployeeId: "emp-rose",
  }),
  pos({
    id: "pos-exec-hr",
    title: "HR Executive",
    securityRoleId: "role-exec-hr",
    department: "HR",
    businessArea: "HR",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-ceo",
    sortOrder: 20,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-HR",
    primaryEmployeeId: "emp-exec-hr",
  }),
  pos({
    id: "pos-hr-manager",
    title: "HR Manager",
    securityRoleId: "role-hr-manager",
    department: "HR",
    businessArea: "HR",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-exec-hr",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-HR",
    primaryEmployeeId: "emp-hr-manager",
  }),
  pos({
    id: "pos-hr-officer",
    title: "HR Officer",
    securityRoleId: "role-hr-officer",
    department: "HR",
    businessArea: "HR",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-hr-manager",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-HR",
    primaryEmployeeId: "emp-staff-146",
  }),
  pos({
    id: "pos-exec-finance",
    title: "Chief Financial Officer",
    securityRoleId: "role-exec-finance",
    department: "Finance",
    businessArea: "Finance",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-ceo",
    sortOrder: 30,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-FIN",
    primaryEmployeeId: "emp-exec-finance",
  }),
  pos({
    id: "pos-finance-manager",
    title: "Finance Manager",
    securityRoleId: "role-finance-manager",
    department: "Finance",
    businessArea: "Finance",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-exec-finance",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-FIN",
    primaryEmployeeId: "emp-finance-manager",
  }),
  pos({
    id: "pos-contracts",
    title: "Contract Administrator",
    securityRoleId: "role-finance-officer",
    department: "Finance",
    businessArea: "Finance",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-finance-manager",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-FIN",
    primaryEmployeeId: "emp-jessica",
  }),
  pos({
    id: "pos-finance-officer",
    title: "Finance Officer",
    securityRoleId: "role-finance-officer",
    department: "Finance",
    businessArea: "Finance",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-finance-manager",
    sortOrder: 20,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-FIN",
    primaryEmployeeId: "emp-staff-147",
  }),
  pos({
    id: "pos-exec-ict",
    title: "ICT Executive",
    securityRoleId: "role-exec-ict",
    department: "ICT",
    businessArea: "ICT",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-ceo",
    sortOrder: 40,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-ICT",
    primaryEmployeeId: "emp-exec-ict",
  }),
  pos({
    id: "pos-ict-manager",
    title: "ICT Manager",
    securityRoleId: "role-ict-manager",
    department: "ICT",
    businessArea: "ICT",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-exec-ict",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-ICT",
    primaryEmployeeId: "emp-ict-manager",
  }),
  pos({
    id: "pos-ict-officer",
    title: "ICT Officer",
    securityRoleId: "role-ict-officer",
    department: "ICT",
    businessArea: "ICT",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-ict-manager",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-ICT",
    primaryEmployeeId: "emp-ict-officer",
  }),
  pos({
    id: "pos-exec-quality",
    title: "Quality Executive",
    securityRoleId: "role-exec-quality",
    department: "Quality",
    businessArea: "Quality",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-ceo",
    sortOrder: 50,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-QUALITY",
    primaryEmployeeId: "emp-exec-quality",
  }),
  pos({
    id: "pos-quality-manager",
    title: "Quality Manager",
    securityRoleId: "role-quality-manager",
    department: "Quality",
    businessArea: "Quality",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-exec-quality",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-QUALITY",
    primaryEmployeeId: "emp-quality-manager",
  }),
  pos({
    id: "pos-quality-officer",
    title: "Quality Officer",
    securityRoleId: "role-quality-officer",
    department: "Quality",
    businessArea: "Quality",
    locationId: "loc-adelaide-hub",
    parentPositionId: "pos-quality-manager",
    sortOrder: 10,
    status: "filled",
    site: "Adelaide HQ",
    costCentre: "CC-QUALITY",
    primaryEmployeeId: "emp-staff-145",
  }),
];

export const leadershipPositionAssignments: PositionAssignmentRecord[] = [
  { id: "pa-board-primary", positionId: "pos-board", employeeId: "emp-board-chair", assignmentType: "primary", effectiveFrom: "2016-05-01", effectiveTo: "", notes: "" },
  { id: "pa-ceo-primary", positionId: "pos-ceo", employeeId: "emp-ceo", assignmentType: "primary", effectiveFrom: "2015-03-01", effectiveTo: "", notes: "" },
  { id: "pa-exec-ops-primary", positionId: "pos-exec-ops", employeeId: "emp-michael", assignmentType: "primary", effectiveFrom: "2018-01-10", effectiveTo: "", notes: "" },
  { id: "pa-gm-ops-primary", positionId: "pos-gm-ops", employeeId: "emp-staff-133", assignmentType: "primary", effectiveFrom: "2021-09-06", effectiveTo: "", notes: "" },
  { id: "pa-rostering-mgr-primary", positionId: "pos-rostering-manager", employeeId: "emp-rostering-manager", assignmentType: "primary", effectiveFrom: "2020-03-01", effectiveTo: "", notes: "" },
  { id: "pa-rostering-off-primary", positionId: "pos-rostering-officer", employeeId: "emp-rostering-officer", assignmentType: "primary", effectiveFrom: "2022-07-01", effectiveTo: "", notes: "" },
  { id: "pa-exec-hr-primary", positionId: "pos-exec-hr", employeeId: "emp-exec-hr", assignmentType: "primary", effectiveFrom: "2017-06-01", effectiveTo: "", notes: "" },
  { id: "pa-hr-mgr-primary", positionId: "pos-hr-manager", employeeId: "emp-hr-manager", assignmentType: "primary", effectiveFrom: "2019-04-01", effectiveTo: "", notes: "" },
  { id: "pa-hr-off-primary", positionId: "pos-hr-officer", employeeId: "emp-staff-146", assignmentType: "primary", effectiveFrom: "2022-10-19", effectiveTo: "", notes: "" },
  { id: "pa-exec-fin-primary", positionId: "pos-exec-finance", employeeId: "emp-exec-finance", assignmentType: "primary", effectiveFrom: "2016-01-15", effectiveTo: "", notes: "" },
  { id: "pa-fin-mgr-primary", positionId: "pos-finance-manager", employeeId: "emp-finance-manager", assignmentType: "primary", effectiveFrom: "2018-11-01", effectiveTo: "", notes: "" },
  { id: "pa-exec-ict-primary", positionId: "pos-exec-ict", employeeId: "emp-exec-ict", assignmentType: "primary", effectiveFrom: "2018-09-01", effectiveTo: "", notes: "" },
  { id: "pa-ict-mgr-primary", positionId: "pos-ict-manager", employeeId: "emp-ict-manager", assignmentType: "primary", effectiveFrom: "2020-01-10", effectiveTo: "", notes: "" },
  { id: "pa-ict-off-primary", positionId: "pos-ict-officer", employeeId: "emp-ict-officer", assignmentType: "primary", effectiveFrom: "2021-05-01", effectiveTo: "", notes: "" },
  { id: "pa-exec-quality-primary", positionId: "pos-exec-quality", employeeId: "emp-exec-quality", assignmentType: "primary", effectiveFrom: "2017-02-01", effectiveTo: "", notes: "" },
  { id: "pa-quality-mgr-primary", positionId: "pos-quality-manager", employeeId: "emp-quality-manager", assignmentType: "primary", effectiveFrom: "2019-08-01", effectiveTo: "", notes: "" },
  { id: "pa-quality-off-primary", positionId: "pos-quality-officer", employeeId: "emp-staff-145", assignmentType: "primary", effectiveFrom: "2021-09-18", effectiveTo: "", notes: "" },
];
