/**
 * Reference data — configurable dropdown options used across the app.
 *
 * **Database target (when you add Supabase or similar):**
 * - `reference_list` — id, key, label, group, description, sort_order
 * - `reference_option` — id, list_id, value, label, sort_order, active, org_id
 *
 * Seed `reference_list` / `reference_option` from `defaultReferenceData`, then load via API.
 * Admin edits write to the DB; the UI keeps using `useReferenceData().getOptions(key)`.
 * localStorage overrides in `config-store.tsx` are a dev-only stand-in until then.
 */

export type ReferenceDataGroup =
  | "Shared"
  | "Client"
  | "Enquiry"
  | "Support plan"
  | "People"
  | "Workforce"
  | "Tasks"
  | "Locations"
  | "Products & services"
  | "Contracts"
  | "Incidents"
  | "Fleet"
  | "Maintenance";

export type ReferenceDataMeta = {
  label: string;
  group: ReferenceDataGroup;
  description?: string;
};

export const referenceDataMeta: Record<string, ReferenceDataMeta> = {
  // Shared (edited under System → Admin)
  yesNo: { label: "Yes / No", group: "Shared", description: "Used across clients, employees, locations, and plans" },
  showAsAlert: { label: "Show as alert", group: "Shared", description: "Yes / No on alert lines" },
  gender: { label: "Gender", group: "Shared", description: "Clients, enquiries, and employees" },
  fundingBody: { label: "Funding body", group: "Shared", description: "Clients and enquiries" },
  disability: { label: "Disability", group: "Shared", description: "Clients and enquiries" },
  addressType: { label: "Address type", group: "Shared", description: "Client, employee, and location addresses" },
  australianState: { label: "State / territory", group: "Shared" },
  country: { label: "Country", group: "Shared" },
  primaryLanguage: { label: "Primary language", group: "Shared", description: "Support plans and profiles" },
  contactRelationship: { label: "Contact relationship", group: "Shared", description: "Client contacts and employee emergency contacts" },
  // Client
  clientStatus: { label: "Client status", group: "Client" },
  clientLifecycleStatus: { label: "Client lifecycle", group: "Client" },
  lifecycleExitReason: { label: "Lifecycle exit reason", group: "Client" },
  ndisSupportBudget: { label: "NDIS support budget", group: "Client" },
  ndisSupportCategory: { label: "NDIS support category", group: "Client" },
  decisionMaking: { label: "Decision making", group: "Client" },
  livingArrangement: { label: "Living arrangement", group: "Client" },
  salesRepresentative: { label: "Sales representative", group: "Client" },
  aboriginalTorresStraitIslander: { label: "Aboriginal / Torres Strait Islander", group: "Client" },
  culturalAffiliation: { label: "Cultural affiliation", group: "Client" },
  businessPartnerGroup: { label: "Business partner group", group: "Client" },
  lgbtiqa: { label: "LGBTIQA+", group: "Client" },
  alertType: { label: "Alert type", group: "Client" },
  restrictivePracticeType: { label: "Restrictive practice type", group: "Client" },
  consentType: { label: "Consent type", group: "Client" },
  consentStatus: { label: "Consent status", group: "Client" },
  riskType: { label: "Risk type", group: "Client" },
  bpAssociationType: { label: "BP association type", group: "Client" },
  planManagementType: { label: "Plan management type", group: "Client" },
  invoiceDeliveryMethod: { label: "Invoice delivery method", group: "Client" },
  statementDeliveryMethod: { label: "Statement delivery method", group: "Client" },
  businessPartnerType: { label: "Business partner type", group: "Shared" },
  businessPartnerStatus: { label: "Business partner status", group: "Shared" },
  paymentTerms: { label: "Payment terms", group: "Shared" },
  contactActivityType: { label: "Contact activity type", group: "Client" },
  needRuleCategory: { label: "Need / rule category", group: "Client" },
  animalType: { label: "Animal type", group: "Client" },
  animalRole: { label: "Animal role", group: "Client" },
  animalStatus: { label: "Animal status", group: "Client" },
  animalCareResponsibility: { label: "Animal care responsibility", group: "Client" },
  animalIncidentType: { label: "Animal incident type", group: "Client" },
  activityType: { label: "Activity type", group: "Client" },
  // Enquiry
  enquiryStatus: { label: "Enquiry status", group: "Enquiry" },
  enquiryLossReason: { label: "Enquiry loss reason", group: "Enquiry" },
  enquiryPlanStatus: { label: "Enquiry plan status", group: "Enquiry" },
  enquiryPlanManagement: { label: "Enquiry plan management", group: "Enquiry" },
  enquiryUrgency: { label: "Enquiry urgency", group: "Enquiry" },
  enquirySource: { label: "Enquiry source", group: "Enquiry" },
  isEnquiryForSelf: { label: "Is enquiry for self", group: "Enquiry" },
  thirdPartyConsent: { label: "3rd party consent", group: "Enquiry" },
  relationshipType: { label: "Relationship type", group: "Enquiry" },
  preferredCommunicationMethod: { label: "Preferred communication method", group: "Enquiry" },
  enquiryQuery: { label: "Enquiry saved queries", group: "Enquiry", description: "List filters" },
  // Support plan
  financialArrangement: { label: "Financial arrangement", group: "Support plan" },
  goalNumber: { label: "Goal number", group: "Support plan" },
  goalTerm: { label: "Goal term", group: "Support plan" },
  goalType: { label: "Goal type", group: "Support plan" },
  ndisGoalCategory: { label: "NDIS goal category", group: "Support plan" },
  riskLikelihood: { label: "Risk likelihood", group: "Client" },
  riskConsequence: { label: "Risk consequence", group: "Client" },
  healthPlanType: { label: "Health plan type", group: "Support plan" },
  supportRequirementArea: { label: "Support requirement area", group: "Support plan" },
  supportAssistanceLevel: { label: "Level of assistance", group: "Support plan" },
  supportFrequency: { label: "Support frequency", group: "Support plan" },
  documentType: { label: "Plan document type", group: "Support plan" },
  planType: { label: "Plan type", group: "Support plan" },
  documentStatus: { label: "Document status", group: "Support plan" },
  assessmentType: { label: "Assessment type", group: "Support plan" },
  progressReviewType: { label: "Progress review type", group: "Support plan" },
  goalProgress: { label: "Goal progress", group: "Support plan" },
  // People
  employeeAlertType: { label: "Employee alert type", group: "People" },
  employeeSkillType: { label: "Employee skill type", group: "People" },
  skillProficiency: { label: "Skill proficiency", group: "People" },
  employeeDocumentType: { label: "Employee document type", group: "People" },
  employeeActivityType: { label: "Employee activity type", group: "People" },
  employeeDocumentStatus: { label: "Employee document status", group: "People" },
  emergencyContactType: { label: "Emergency contact type", group: "People" },
  employmentType: { label: "Employment type", group: "People" },
  contractedHoursPeriod: { label: "Contracted hours period", group: "People" },
  schadsClassificationLevel: { label: "SCHADS classification", group: "People" },
  payMethod: { label: "Pay method", group: "People" },
  credentialType: { label: "Credential type", group: "People" },
  credentialStatus: { label: "Credential status", group: "People" },
  department: { label: "Department", group: "People" },
  employmentStatus: { label: "Employment status", group: "People" },
  // Tasks
  taskPriority: { label: "Task priority", group: "Tasks", description: "Low, Normal, High — used on tasks and automations" },
  // Workforce
  leaveType: { label: "Leave type", group: "Workforce" },
  employeeLeaveStatus: { label: "Leave request status", group: "Workforce" },
  // Locations
  locationType: { label: "Location type", group: "Locations" },
  locationStatus: { label: "Location status", group: "Locations" },
  locationClientRole: { label: "Client assignment role", group: "Locations" },
  locationEmployeeRole: { label: "Employee assignment role", group: "Locations" },
  locationAlertType: { label: "Location alert type", group: "Locations" },
  locationActivityType: { label: "Location activity type", group: "Locations" },
  // Products & services
  productCategory: { label: "Product category", group: "Products & services" },
  uom: { label: "Unit of measure", group: "Products & services" },
  productType: { label: "Product type", group: "Products & services" },
  serviceAgreementTerm: { label: "Service agreement term", group: "Products & services" },
  serviceAgreementStatus: { label: "Service agreement status", group: "Products & services" },
  fundingType: { label: "Funding type", group: "Products & services" },
  fundingManagementType: { label: "Funding management type", group: "Products & services" },
  budgetRules: { label: "Budget rules", group: "Products & services" },
  registrationGroup: { label: "NDIS registration group", group: "Products & services" },
  claimType: { label: "Claim type", group: "Products & services" },
  bookingCancellationReason: { label: "Booking cancellation reason", group: "Products & services" },
  bookingCancellationInitiatedBy: { label: "Cancellation initiated by", group: "Products & services" },
  // Contracts
  contractType: { label: "Contract type", group: "Contracts" },
  contractTerm: { label: "Contract term", group: "Contracts" },
  auditAction: { label: "Audit action", group: "Contracts" },
  // Incident reports
  partyType: { label: "Party type", group: "Incidents" },
  partyRole: { label: "Party role", group: "Incidents" },
  incidentActionType: { label: "Incident action type", group: "Incidents" },
  notificationTarget: { label: "Notification target", group: "Incidents" },
  notificationMethod: { label: "Notification method", group: "Incidents" },
  incidentStatus: { label: "Incident status", group: "Incidents" },
  incidentSeverity: { label: "Incident severity", group: "Incidents" },
  ndisReportableType: { label: "NDIS reportable type", group: "Incidents" },
  incidentCategory: { label: "Incident category", group: "Incidents" },
  incidentServiceType: { label: "Incident service type", group: "Incidents" },
  fleetServiceType: { label: "Fleet service type", group: "Fleet" },
  fleetServiceCostStatus: { label: "Fleet service cost status", group: "Fleet" },
  fleetInspectionResult: { label: "Fleet inspection result", group: "Fleet" },
  fleetVehicleStatus: { label: "Fleet vehicle status", group: "Fleet" },
  maintenanceCategory: { label: "Maintenance category", group: "Maintenance" },
  maintenancePriority: { label: "Maintenance priority", group: "Maintenance" },
  maintenanceStatus: { label: "Maintenance status", group: "Maintenance" },
  maintenanceCostStatus: { label: "Maintenance cost status", group: "Maintenance" },
  maintenancePhotoType: { label: "Maintenance photo type", group: "Maintenance" },
};

export type ReferenceDataKey = keyof typeof referenceDataMeta;

export type ReferenceDataCatalog = Record<string, string[]>;

const ndisRegistrationGroups = [
  "Assistance Animals",
  "Assistance In Coordinating Or Managing Life Stages And Trans",
  "Assistance With Daily Life Tasks In A Group Or Shared Living",
  "Assistance With Travel/Transport Arrangements",
  "Assistance to Access and Maintain Employment or higher educa",
  "Assistive Equipment For Recreation",
  "Assistive Products For Household Tasks",
  "Assistive Products For Personal Care And Safety",
  "Communication And Information Equipment",
  "Community Nursing Care",
  "Customised Prosthetics (includes Orthotics)",
  "Daily Personal Activities",
  "Development Of Daily Living And Life Skills",
  "Early Intervention Supports For Early Childhood",
  "Exercise Physiology & Personal Well-being Activities",
  "Group And Centre Based Activities",
  "Hearing Equipment",
  "Hearing Services",
  "High Intensity Daily Personal Activities",
  "Home Modification Design And Construction",
  "Household Tasks",
  "Innovative Community Participation",
  "Interpreting And Translation",
  "Management of Funding for Supports",
  "Participation In Community And Social And Civic Activities",
  "Personal Mobility Equipment",
  "Specialised Disability Accommodation",
  "Specialised Driver Training",
  "Specialised Hearing Services",
  "Specialised Supported Employment",
  "Specialist Positive Behaviour Support",
  "Supported Independent Living",
  "Support Coordination",
  "Therapeutic Supports",
  "Vehicle Modifications",
  "Vision Equipment",
];

export const defaultReferenceData: ReferenceDataCatalog = {
  clientStatus: [
    "1_Prospect",
    "2_Active receiving support",
    "3_Active with additional service request",
    "4_Actively exiting",
    "5_Inactive",
    "6_Deceased",
  ],
  clientLifecycleStatus: ["intake", "onboarding", "active", "plan_review", "exit"],
  lifecycleExitReason: [
    "Plan review — transitioned to new provider",
    "Voluntary withdrawal",
    "Relocated out of service area",
    "Plan ended — age out",
    "Deceased",
    "Other",
  ],
  ndisSupportBudget: ["Core", "Capacity building", "Capital"],
  ndisSupportCategory: [
    "Assistance with Daily Life",
    "Social and Community Participation",
    "Transport",
    "Consumables",
    "Home and Living",
    "Support Coordination",
    "Improved Living Arrangements",
    "Improved Health and Wellbeing",
    "Improved Learning",
    "Improved Life Choices",
    "Improved Daily Living",
    "Assistive Technology",
    "Home Modifications",
    "Specialist Disability Accommodation",
  ],
  gender: ["Female", "Male", "Non-binary", "Prefer not to say", "Other"],
  decisionMaking: [
    "Legal order in place appointing guardian/decision maker",
    "Makes all decisions",
    "Supported to make decisions",
  ],
  livingArrangement: ["Lives Alone", "Lives with Family", "Lives with Friends/Housemates"],
  salesRepresentative: [
    "AbilityVua",
    "Gabriela Wilson",
    "Isla Robinson",
    "Michael Smith",
    "Oliver Williams",
    "Rose Dash",
  ],
  fundingBody: [
    "Commonwealth Home Support Programme (CHSP)",
    "DSOA - Disability Support for Older Australians",
    "NDIS - National Disability Insurance Scheme",
    "RTWSA - Return to Work SA",
    "Self-funded",
    "Other",
  ],
  aboriginalTorresStraitIslander: [
    "Aboriginal",
    "Aboriginal and Torres Straight Islander",
    "Neither",
    "Torres Straight Islander",
  ],
  culturalAffiliation: [
    "Australian",
    "Australian Aboriginal",
    "Australian South Sea Islander",
    "Cook Islander",
    "Fijian",
    "Hawaiian",
    "I-Kiribati",
    "Maori",
    "Melanesian and Papuan, nec",
    "Micronesian, nec",
    "Nauruan",
    "New Caledonian",
    "New Zealander",
    "Ni-Vanuatu",
    "Niuean",
    "Norfolk Islander",
    "Papua New Guinean",
    "Pitcairn",
    "Polynesian, nec",
    "Samoan",
    "Solomon Islander",
    "Tahitian",
    "Tokelauan",
    "Tongan",
    "Torres Strait Islander",
    "Tuvaluan",
    "Other",
  ],
  disability: [
    "PD - Spinal Cord Injury",
    "PD - Acquired Brain Injury",
    "PD - Multiple Sclerosis",
    "PD - Stroke",
    "PD - Absent Limb or Reduced Limb Function",
    "PD - Paraplegia",
    "SD - Hearing Impairment",
    "ID - Autism",
    "ID - Down Syndrome",
    "ID - Developmental Delay",
    "PSD - Bipolar Disorder",
  ],
  businessPartnerGroup: ["Support Receiver", "Support Provider", "Referrer", "Other"],
  lgbtiqa: ["Yes", "No", "Prefer not to say"],
  alertType: ["Allergy", "Choking Risk", "Incident", "Legal", "Other", "Temporary Alert"],
  restrictivePracticeType: [
    "Chemical restraint",
    "Environmental restraint",
    "Mechanical restraint",
    "Physical restraint",
    "Seclusion",
  ],
  consentType: [
    "Service delivery",
    "Information collection and sharing",
    "Photography and video",
    "Medical treatment",
    "Legal order / guardian",
    "NDIS plan sharing",
    "Transport",
    "Other",
  ],
  consentStatus: ["Pending", "Granted", "Refused", "Not required", "Expired"],
  riskType: ["Allergy", "Choking", "Falls", "Behaviour", "Medical", "Environmental", "Other"],
  bpAssociationType: ["Family / friend", "Guardian", "Plan manager", "Support coordinator", "Referrer", "Health provider", "Vendor", "Other"],
  planManagementType: ["Agency managed", "Plan managed", "Self managed"],
  invoiceDeliveryMethod: ["Email", "Post", "Portal", "In-system registry"],
  statementDeliveryMethod: ["Email", "Post", "Portal", "In-system registry"],
  businessPartnerType: ["Plan manager", "Vendor", "Referrer", "Support coordinator", "Health provider", "NDIS agency", "Other"],
  businessPartnerStatus: ["Active", "Inactive"],
  paymentTerms: ["7 days", "14 days", "30 days", "45 days", "Due on receipt"],
  contactActivityType: ["Phone call", "Email", "Meeting", "Visit", "Note", "Other"],
  needRuleCategory: ["Personal care", "Meals", "Mobility", "Communication", "Behaviour", "Household", "Other"],
  animalType: ["dog", "cat", "bird", "other"],
  animalRole: ["assistance", "companion", "therapy"],
  animalStatus: ["active", "deceased", "transferred"],
  animalCareResponsibility: ["self", "staff", "external"],
  animalIncidentType: [
    "Bite / scratch / injury",
    "Animal illness during shift",
    "Animal behaviour concern",
    "Animal escape",
    "Animal death",
  ],
  showAsAlert: ["No", "Yes"],
  activityType: ["Note", "Phone call", "Email", "Meeting", "Visit", "Complaint", "Feedback", "Incident", "Other"],
  addressType: ["Home", "Postal", "SIL residence", "Work", "Temporary accommodation", "Other"],
  australianState: ["SA", "NSW", "VIC", "QLD", "WA", "TAS", "NT", "ACT"],
  country: ["Australia", "New Zealand"],
  enquiryStatus: [
    "1_Enquiry received",
    "2_Qualification",
    "3_Proposal",
    "4_Converted",
    "5_Lost",
  ],
  enquiryLossReason: [
    "Chose another provider",
    "Funding not suitable",
    "Out of service area",
    "No response from enquirer",
    "Plan review — not ready yet",
    "Services not offered",
    "Duplicate enquiry",
    "Other",
  ],
  enquiryPlanStatus: ["Active", "Plan review within 3 months", "New to NDIS — plan pending", "Plan ended", "Unknown"],
  enquiryPlanManagement: ["Agency managed", "Plan managed", "Self managed"],
  enquiryUrgency: ["High — start within 2 weeks", "Normal — start within 1–3 months", "Low — exploring options"],
  enquirySource: ["Phone Call", "Email", "Website", "Referral", "Walk-in", "Other"],
  isEnquiryForSelf: ["Yes", "No"],
  thirdPartyConsent: ["Received", "Requested", "ReceivedRequested", "Not required"],
  relationshipType: ["Parent", "Guardian", "Carer", "Support coordinator", "Other"],
  preferredCommunicationMethod: ["Email", "Phone Call", "SMS"],
  enquiryQuery: ["Open Enquiries", "Closed Enquiries"],
  yesNo: ["No", "Yes"],
  primaryLanguage: [
    "English",
    "Auslan",
    "Arabic",
    "Cantonese",
    "Mandarin",
    "Vietnamese",
    "Hindi",
    "Greek",
    "Italian",
    "Other",
  ],
  financialArrangement: [
    "Manages own finances",
    "Plan managed",
    "Nominee manages finances",
    "NDIA manages",
  ],
  goalNumber: [
    "1-One",
    "2-Two",
    "3-Three",
    "4-Four",
    "5-Five",
    "6-Six",
    "7-Seven",
    "8-Eight",
    "9-Nine",
    "10-Ten",
  ],
  goalTerm: ["Short Term Goal", "Medium/Long Term Goal"],
  goalType: ["NDIS Goal", "Personal Goal"],
  ndisGoalCategory: [
    "Daily living",
    "Social and community participation",
    "Health and wellbeing",
    "Learning",
    "Work",
    "Home",
    "Assistive technology",
    "Relationships",
    "Choice and control",
  ],
  riskLikelihood: ["Low", "Medium", "High"],
  riskConsequence: ["Low", "Medium", "High", "Critical"],
  healthPlanType: [
    "Medication plan",
    "Seizure management plan",
    "Diabetes plan",
    "PEG plan",
    "Dysphagia plan",
    "Manual handling plan",
    "Other",
  ],
  supportRequirementArea: [
    "Personal care — showering",
    "Personal care — grooming",
    "Personal care — dressing",
    "Personal care — continence",
    "Personal care — toileting",
    "Daily living — cleaning",
    "Daily living — shopping",
    "Daily living — meal preparation",
    "Medication prompting",
    "Community access — transport",
    "Community access — social activities",
    "Community access — appointments",
    "Capacity building — skill development",
    "Capacity building — independence",
    "Employment supports",
  ],
  supportAssistanceLevel: ["Independent", "Prompting", "Partial assistance", "Full assistance"],
  supportFrequency: ["Daily", "Weekly", "Per shift", "As needed"],
  documentType: ["Plan", "Assessment"],
  planType: ["Support Plan", "Care Plan", "NDIS Plan"],
  documentStatus: ["Draft", "In Progress", "Published", "Archived"],
  assessmentType: [
    "Comprehensive Aged Care Assessment (ACAT)",
    "Functional Capacity Assessment",
    "Health Assessments",
    "Low-level Age Care assessment (RAS)",
    "Pedi-CAT Assessment",
    "Risk Assessment",
    "Risk Assessment - Restrictive Practice",
    "Social Assessments",
  ],
  progressReviewType: ["Progress Review", "Final Goal Review", "Self-assessment Review"],
  goalProgress: ["No Progress", "Some Progress", "Almost Achieved", "Achieved"],
  productCategory: [
    "Asistance with Self Care Activities",
    "Capacity Building Community, Social and Civic Activities",
    "Group and Centre Based Activities",
    "Short Term Accommodation",
    "Supported Independent Living",
    "Support Coordination",
    "Therapy",
    "Transport",
    "Administration",
  ],
  uom: ["Hour", "Each", "Day", "Week", "Month", "Km", "Minutes", "Work Day", "Working Month", "Year"],
  productType: ["Service", "Item", "Resource", "Asset"],
  serviceAgreementTerm: ["Fixed Term", "Ongoing"],
  serviceAgreementStatus: ["Draft", "Sent", "Signed", "Active", "Expiring", "Expired", "Terminated", "Cancelled"],
  fundingType: ["Funding Body", "Self Funded"],
  fundingManagementType: ["Portal Managed", "Plan Managed", "Self Managed"],
  budgetRules: ["Strict Limit", "Warning", "Allow over budget"],
  registrationGroup: ndisRegistrationGroups,
  claimType: ["NDIS", "Self Funded", "Other"],
  bookingCancellationReason: [
    "Participant unavailable",
    "Participant request",
    "Illness or hospitalisation",
    "Provider capacity",
    "Weather or emergency",
    "Plan suspended",
    "Other",
  ],
  bookingCancellationInitiatedBy: ["Participant", "Provider", "NDIA", "Mutual agreement"],
  contractType: [
    "Supplier Contract",
    "Tenancy Agreeement",
    "NDIS Service Agreement",
    "Employee Contract",
  ],
  contractTerm: ["Fixed", "Ongoing"],
  auditAction: ["Created", "Updated", "Reviewed", "Renewed", "Terminated"],
  employeeAlertType: ["Compliance", "Operational", "HR", "Safety", "Other"],
  employeeSkillType: ["Language", "Skill", "Specialisation"],
  skillProficiency: ["Basic", "Intermediate", "Advanced", "Native", "Fluent"],
  employeeDocumentType: [
    "Employment contract",
    "Position description",
    "Photo ID",
    "Right to work",
    "Signed policy",
    "Qualification",
    "Other",
  ],
  employeeActivityType: ["Note", "Onboarding", "Training", "Performance review", "Incident", "Other"],
  leaveType: ["Annual leave", "Personal / carer's leave", "Long service leave", "Parental leave", "Unpaid leave"],
  partyType: ["Client", "Employee", "Witness", "Other"],
  partyRole: ["Affected person", "Reporter", "Witness", "Staff involved", "Manager notified", "Other"],
  incidentActionType: [
    "Immediate response",
    "Investigation step",
    "Corrective action",
    "Evidence collected",
    "Risk review",
    "Other",
  ],
  notificationTarget: [
    "Internal manager",
    "NDIS Commission",
    "Participant / family",
    "Guardian",
    "Police",
    "Other regulator",
    "Other",
  ],
  notificationMethod: ["Phone", "Email", "NDIS portal", "In person", "Written letter", "Other"],
  incidentStatus: [
    "Draft",
    "Submitted",
    "Manager reviewed",
    "Commission notified",
    "Under investigation",
    "Actions in progress",
    "Closed",
  ],
  incidentSeverity: ["Low", "Medium", "High", "Critical"],
  ndisReportableType: [
    "Death",
    "Serious injury",
    "Abuse or neglect",
    "Unlawful sexual or physical contact or assault",
    "Sexual misconduct",
    "Unauthorised restrictive practice",
  ],
  employeeDocumentStatus: ["Current", "Expiring soon", "Expired", "Archived"],
  contactRelationship: ["Spouse", "Partner", "Parent", "Sibling", "Child", "Friend", "Other"],
  emergencyContactType: ["Emergency", "Next of kin"],
  employmentType: ["Full-time", "Part-time", "Casual", "Contractor", "Volunteer"],
  contractedHoursPeriod: ["fortnight", "week", "month"],
  schadsClassificationLevel: ["level-2.1", "level-2.2", "level-3.1"],
  payMethod: ["Bank", "Cash", "Cheque"],
  credentialType: [
    "NDIS Worker Screening",
    "Working with Children Check",
    "Police Check",
    "First Aid Certificate",
    "CPR Certificate",
    "Manual Handling",
    "Driver Licence",
    "Visa / work rights",
    "Qualification",
    "Insurance",
    "Other",
  ],
  credentialStatus: ["Current", "Expiring soon", "Expired", "Pending", "Pending review", "Rejected", "Revoked"],
  department: [
    "Executive",
    "Intake",
    "Client services",
    "Support coordination",
    "Finance",
    "HR",
    "IT",
    "Operations",
  ],
  employmentStatus: ["Active", "On leave", "Terminated"],
  taskPriority: ["Low", "Normal", "High"],
  employeeLeaveStatus: ["Draft", "Requested", "Approved", "Declined", "Cancelled", "Taken"],
  locationType: [
    "SIL house",
    "Day program",
    "Community hub",
    "Office",
    "Respite",
    "Therapy room",
    "Other",
  ],
  locationStatus: ["Active", "Inactive", "Planned", "Closed"],
  locationClientRole: ["Resident", "Regular attendee", "Occasional", "Visitor"],
  locationEmployeeRole: [
    "Site manager",
    "Support worker",
    "Team leader",
    "Relief staff",
    "Allied health",
    "Other",
  ],
  locationAlertType: ["Safety", "Access", "Operational", "Clinical", "Maintenance", "Other"],
  locationActivityType: [
    "Site visit",
    "Maintenance",
    "Incident follow-up",
    "Phone call",
    "Note",
    "Other",
  ],
  incidentCategory: [
    "Operational",
    "Near miss",
    "Injury",
    "Behaviour",
    "Restrictive practice",
    "Property damage",
    "Complaint",
    "Other",
  ],
  incidentServiceType: [
    "NDIS Support",
    "SIL",
    "Community Participation",
    "Therapy",
    "Transport",
    "Administration",
    "Unassigned",
  ],
  fleetServiceType: ["Scheduled", "Repair", "Inspection", "Tyres", "Other"],
  fleetServiceCostStatus: ["pending", "reviewed", "approved", "rejected"],
  fleetInspectionResult: ["pass", "fail"],
  fleetVehicleStatus: ["active", "inactive", "off_road", "disposed"],
  maintenanceCategory: ["plumbing", "electrical", "structural", "equipment", "general"],
  maintenancePriority: ["urgent", "high", "medium", "low"],
  maintenanceStatus: ["reported", "assigned", "in_progress", "resolved", "closed", "cancelled"],
  maintenanceCostStatus: ["pending", "reviewed", "approved", "rejected"],
  maintenancePhotoType: ["issue", "completion", "invoice"],
};

/** @deprecated Use useReferenceData().getOptions instead */
export const clientDropdowns = {
  clientStatus: defaultReferenceData.clientStatus,
  clientLifecycleStatus: defaultReferenceData.clientLifecycleStatus,
  lifecycleExitReason: defaultReferenceData.lifecycleExitReason,
  ndisSupportBudget: defaultReferenceData.ndisSupportBudget,
  ndisSupportCategory: defaultReferenceData.ndisSupportCategory,
  status: defaultReferenceData.clientStatus,
  gender: defaultReferenceData.gender,
  decisionMaking: defaultReferenceData.decisionMaking,
  livingArrangement: defaultReferenceData.livingArrangement,
  salesRepresentative: defaultReferenceData.salesRepresentative,
  fundingBody: defaultReferenceData.fundingBody,
  aboriginalTorresStraitIslander: defaultReferenceData.aboriginalTorresStraitIslander,
  culturalAffiliation: defaultReferenceData.culturalAffiliation,
  disability: defaultReferenceData.disability,
  alertType: defaultReferenceData.alertType,
  restrictivePracticeType: defaultReferenceData.restrictivePracticeType,
  consentType: defaultReferenceData.consentType,
  consentStatus: defaultReferenceData.consentStatus,
  riskType: defaultReferenceData.riskType,
  bpAssociationType: defaultReferenceData.bpAssociationType,
  planManagementType: defaultReferenceData.planManagementType,
  invoiceDeliveryMethod: defaultReferenceData.invoiceDeliveryMethod,
  statementDeliveryMethod: defaultReferenceData.statementDeliveryMethod,
  preferredCommunicationMethod: defaultReferenceData.preferredCommunicationMethod,
  contactActivityType: defaultReferenceData.contactActivityType,
  needRuleCategory: defaultReferenceData.needRuleCategory,
  animalType: defaultReferenceData.animalType,
  animalRole: defaultReferenceData.animalRole,
  animalStatus: defaultReferenceData.animalStatus,
  animalCareResponsibility: defaultReferenceData.animalCareResponsibility,
  showAsAlert: defaultReferenceData.showAsAlert,
  activityType: defaultReferenceData.activityType,
  contactRelationship: defaultReferenceData.contactRelationship,
  yesNo: defaultReferenceData.yesNo,
};

/** @deprecated Use useReferenceData().getOptions instead */
export const enquiryDropdowns = {
  enquiryStatus: defaultReferenceData.enquiryStatus,
  enquiryLossReason: defaultReferenceData.enquiryLossReason,
  enquiryPlanStatus: defaultReferenceData.enquiryPlanStatus,
  enquiryPlanManagement: defaultReferenceData.enquiryPlanManagement,
  enquiryUrgency: defaultReferenceData.enquiryUrgency,
  status: defaultReferenceData.enquiryStatus,
  enquirySource: defaultReferenceData.enquirySource,
  isEnquiryForSelf: defaultReferenceData.isEnquiryForSelf,
  thirdPartyConsent: defaultReferenceData.thirdPartyConsent,
  relationshipType: defaultReferenceData.relationshipType,
  preferredCommunicationMethod: defaultReferenceData.preferredCommunicationMethod,
  gender: defaultReferenceData.gender,
  fundingBody: defaultReferenceData.fundingBody,
  disability: defaultReferenceData.disability,
};

/** @deprecated Use useReferenceData().getOptions instead */
export const incidentDropdowns = {
  incidentStatus: defaultReferenceData.incidentStatus,
  status: defaultReferenceData.incidentStatus,
  incidentSeverity: defaultReferenceData.incidentSeverity,
  severity: defaultReferenceData.incidentSeverity,
  partyType: defaultReferenceData.partyType,
  partyRole: defaultReferenceData.partyRole,
  incidentActionType: defaultReferenceData.incidentActionType,
  notificationTarget: defaultReferenceData.notificationTarget,
  notificationMethod: defaultReferenceData.notificationMethod,
  ndisReportableType: defaultReferenceData.ndisReportableType,
};

export function referenceDataGroups(): ReferenceDataGroup[] {
  return [...new Set(Object.values(referenceDataMeta).map((m) => m.group))];
}

export function referenceDataKeys(): ReferenceDataKey[] {
  return Object.keys(referenceDataMeta) as ReferenceDataKey[];
}
