import type { HelpArticle } from "@/lib/help/types";

export const clientsArticle: HelpArticle = {
  id: "article-clients",
  slug: "clients",
  title: "Clients",
  summary: "Manage client profiles, compliance lines, locations, and service agreements.",
  category: "Core",
  keywords: [
    "client",
    "support receiver",
    "consent",
    "restrictive practice",
    "alerts",
    "service agreement",
    "support plan",
  ],
  relatedRoutes: ["/clients", "/service-agreements"],
  windowKeys: ["clients"],
  lastUpdated: "2026-06-30",
  sections: [
    {
      id: "client-list",
      title: "Clients list",
      body: "All clients lists every active client. Click a search key to open the client in the workspace. You can keep multiple clients open at once.",
      relatedRoutes: ["/clients"],
    },
    {
      id: "client-lifecycle",
      title: "Client lifecycle",
      body: "Lifecycle tracks where the participant is in your intake-to-exit workflow. Set it on Full profile and filter the Clients list by lifecycle.",
      steps: [
        "Open the client → Full profile.",
        "Set Lifecycle (intake, onboarding, active, plan review, or exit).",
        "When lifecycle is plan review, enter Plan review due.",
        "When lifecycle is exit, choose an Exit reason.",
        "Save the record. The list shows a lifecycle badge; use All lifecycles to filter.",
      ],
      windowKeys: ["client-full-profile", "clients"],
    },
    {
      id: "client-tab-groups",
      title: "Client tab groups",
      body: "Client records use grouped tabs on the left. Your role controls which tabs you see.",
      bullets: [
        "Core: Overview, Alerts, Activity, Calendar, Full profile, Service agreements, Service bookings",
        "Relationships: BP Associations, Locations, Contact Activity",
        "Care and compliance: Requests, Restrictive Practices, Consents and Legal Orders, Risks, Animal and Pet, Incidents",
        "Planning: Plan budget, Plan and Assessment, Support Plan, Goals, Progress Review, Support Receiver Needs and Rules",
      ],
    },
    {
      id: "overview",
      title: "Overview tab",
      body: "Overview shows the client summary card: lifecycle, status, funding, risk alerts, consent alert list, core consents, and plan utilisation. Use it for quick checks before drilling into line tabs.",
      relatedRoutes: ["/clients"],
      windowKeys: ["client-overview"],
    },
    {
      id: "plan-utilisation",
      title: "Plan utilisation on Overview",
      body: "When plan budget lines exist, Overview rolls up allocated, claimed, and remaining amounts across Core, Capacity building, and Capital. Click Open Plan budget to edit lines.",
      steps: [
        "Open the client → Overview.",
        "Review Plan utilisation totals and per-budget breakdown.",
        "Click Open Plan budget to add or edit budget lines.",
      ],
      windowKeys: ["client-overview", "client-plan-budget"],
    },
    {
      id: "plan-budget",
      title: "Plan budget tab",
      body: "Enter NDIS plan budget lines by support budget (Core, Capacity building, Capital), category, allocated amount, and claimed amount. Summary cards show totals and remainder.",
      steps: [
        "Open the client → Plan budget (your role needs Plan budget access).",
        "Review summary cards: total allocated, claimed, and remaining.",
        "Set Plan provider on each line when the participant receives budget from more than one NDIS provider (defaults to This organisation).",
        "Add rows manually, use Core supports starter / Full plan scaffold, or import a CSV.",
        "For CSV import: paste or upload columns support_budget, support_category, description, ndis_line_item, allocated_amount, claimed_amount. Use Load sample template or Replace existing lines when replacing all rows.",
        "For PDF copy: use Paste from plan PDF — one line per category (budget type, category name, allocated amount) copied from myplace or the plan PDF.",
        "For gateway pull: set the participant NDIS number on the profile, then use Pull plan from gateway when NDIS_GATEWAY_DRY_RUN is enabled (or live credentials are configured).",
        "Review Billing claimed rollup — compare manual claimed amounts to submitted claims and sent invoices; use Apply billing rollup, then save.",
        "Enter Support budget, Support category, description, allocated ($), and claimed ($) per line.",
        "Save the record. Changes appear in Overview plan utilisation, Multi-provider budget, and service booking compliance checks.",
      ],
      windowKeys: ["client-plan-budget"],
    },
    {
      id: "alerts-activity",
      title: "Alerts and Activity",
      body: "Alerts hold incident and care flags with valid-from and valid-to dates. Activity logs phone calls, visits, and case notes. Client line tabs use a summary list — click a row to open the line drawer for full fields (descriptions, controls, notes). Save the parent record to persist. Activity lines can only be removed by an administrator; other roles use Request deletion to send a task to the admin team.",
      windowKeys: ["client-alerts", "client-activity"],
    },
    {
      id: "record-calendar",
      title: "Calendar tab (client, employee, location)",
      body: "The Calendar tab sits under Activity on client, employee, and location records. Default view is **Fortnight** (14 days) to match the standard roster cycle. Live shifts, tasks, and activity notes always show; tick **Show RoC templates** to overlay master roster-of-care lines for comparison. On location calendars, tick **Show maintenance** for scheduled repairs and open requests, and **Show vehicle bookings** for fleet reservations linked to the site. Colour-coded chips link to the source record when your role has access.",
      steps: [
        "Open a client, employee, or location record → Calendar (below Activity in the sidebar).",
        "Use the Fortnight view (default) to plan the current roster cycle; switch Week, Month, or Day as needed.",
        "Tick Show RoC templates to compare master roster lines against published live shifts.",
        "On a location, tick Show maintenance or Show vehicle bookings when you need facilities or transport context.",
        "Click a chip to open the linked record when you have access.",
      ],
      windowKeys: ["client-calendar", "employee-calendar", "location-calendar", "rostering", "tasks"],
    },
    {
      id: "consents",
      title: "Consents and Legal Orders",
      body: "Track consent types, legal orders, expiry, and notes per line. Three core consent types — Service delivery, Information collection and sharing, and Photography and video — appear as summary tiles at the top of the tab.",
      steps: [
        "Open the client → Consents and Legal Orders.",
        "Review the three core consent tiles (Service, Information, Photo). Status comes from the most recent valid line for each type.",
        "Add or edit lines: pick Consent type, Status (Pending, Granted, Refused, Not required, Expired), valid-from and valid-to dates, and notes.",
        "Save the record. Refused or missing core consents roll up to the consent alert list on Overview.",
      ],
      windowKeys: ["client-consents-and-legal-orders"],
    },
    {
      id: "core-consents",
      title: "Core consents summary",
      body: "Overview includes a Core consents panel showing the current status of the three mandatory consent types. Keep this aligned with lines on Consents and Legal Orders.",
      windowKeys: ["client-overview", "client-consents-and-legal-orders"],
    },
    {
      id: "restrictive-practices",
      title: "Restrictive Practices",
      body: "Document authorised restrictive practices with type, dates, review schedule, and oversight details. Each line is editable in the table.",
      windowKeys: ["client-restrictive-practices"],
    },
    {
      id: "locations-tab",
      title: "Locations tab",
      body: "Client locations lists addresses linked to the participant: home, service delivery, invoice, and postal flags. Align location assignments with Support Location records under the Locations module.",
      windowKeys: ["client-locations"],
    },
    {
      id: "service-agreements",
      title: "Service agreements",
      body: "Open Service agreements from the client tab or from Clients → All service agreements in the sidebar. Agreements link products and funding lines to the client.",
      relatedRoutes: ["/service-agreements"],
      windowKeys: ["client-service-agreements", "service-agreements"],
    },
    {
      id: "service-bookings-tab",
      title: "Service bookings tab",
      body: "Lists service bookings linked to this client. Open a card to edit lines and compliance, or use New service booking to create one with the client pre-selected.",
      relatedRoutes: ["/service-bookings"],
      windowKeys: ["client-service-bookings", "service-bookings"],
    },
    {
      id: "support-plan-tab",
      title: "Support Plan tab",
      body: "The Support Plan tab holds the participant care plan: About me, communication, health, behaviour, daily living sections, goals, health records, support requirements, assistive technology, emergency procedures, and worker instructions. Use the sidebar to switch sections. Line sections — Goals, Medications, Diagnoses, Health plans, Support requirements, and Assistive technology — use a read-only summary list: click a row (or Add) to open the side panel with the full form, **Save** and **Cancel** in the panel footer, and Copy and Remove below. Save persists the support plan — you do not need to scroll to the page save bar.",
      steps: [
        "Open the client → Support Plan.",
        "Pick a section from the sidebar (About me, Communication and language, Health records, Goals, and so on).",
        "Edit fields or line tables; click Save support plan when the unsaved bar appears.",
        "Open Full audit trail on the client to confirm field-level changes.",
      ],
      windowKeys: ["client-support-plan"],
    },
    {
      id: "support-plan-print-send",
      title: "Print and send the support plan",
      body: "At the bottom of Support Plan, the Documents section holds Print, PDF, and Send. Expand Saved files to open registry copies with date and time. Expand Print log to see who printed or sent and when. Use How to print and send for full steps — AbilityVua does not send outbound email; use Open email draft after Send.",
      steps: [
        "Open the client → Support Plan; confirm sections are complete.",
        "Scroll to Documents at the bottom of the tab.",
        "Click Print or PDF — confirm the file appears under Saved files.",
        "Click Send — then Open email draft to hand off via your mail client.",
        "Use Print log to confirm who ran each action.",
      ],
      relatedRoutes: ["/clients", "/system/admin/document-registry"],
      windowKeys: ["client-support-plan"],
    },
    {
      id: "risks-tab",
      title: "Risks tab",
      body: "Formal risk register separate from Alerts. Mark Show as alert to roll up to the risk alerts field on Overview.",
      windowKeys: ["client-risks"],
    },
    {
      id: "animal-pet-tab",
      title: "Animal and Pet tab",
      body: "Register assistance animals and companion pets with care requirements, vet contacts, vaccination dates, and transport notes. Link each animal to a support location (and optional client address) so workers see the right pets on rostered shifts and on the location overview. Set an animal allergy alert for the profile header. Assistance and therapy roles may be NDIS-billable when in the support plan; companion pets are never billable.",
      windowKeys: ["client-animal-and-pet"],
    },
    {
      id: "billing-communication",
      title: "Billing & communication (Overview)",
      body: "Set preferred communication, plan management type, default plan manager from the business partner directory, and invoice or statement delivery method. Invoice generation uses the plan manager remittance email when plan-managed.",
      windowKeys: ["clients"],
    },
    {
      id: "bp-associations",
      title: "BP Associations tab",
      body: "Link guardians, family, referrers, plan managers, and vendors. Use Directory partner to pick from Business partners, or enter a free-text name. Record relationship, contact details, and primary contact flag.",
      windowKeys: ["client-bp-associations"],
    },
    {
      id: "contact-activity-tab",
      title: "Contact Activity tab",
      body: "Log outreach with associated contacts. Separate from the core Activity tab. Uses the same summary list and line drawer pattern — click a row to edit, then Save on the client record. Removal follows the same admin-only rule as Activity — use Request deletion if you are not an administrator.",
      windowKeys: ["client-contact-activity"],
    },
    {
      id: "goals-tab",
      title: "Goals tab",
      body: "View and edit goals from the active support plan without opening the full Support Plan panel. Goals show as a read-only summary list — click a row (or Add goal) to open the side panel with the full form. Save updates the support plan record.",
      windowKeys: ["client-goals"],
    },
    {
      id: "progress-review-tab",
      title: "Progress Review tab",
      body: "Record progress reviews linked to support plan goals. Pick a goal, review type, progress level, and next steps.",
      windowKeys: ["client-progress-review"],
    },
    {
      id: "needs-rules",
      title: "Support Receiver Needs and Rules tab",
      body: "Document daily living rules and support instructions staff must follow. Mark Show as alert when the rule must be visible before delivering support.",
      windowKeys: ["client-support-receiver-needs-and-rules"],
    },
    {
      id: "requests-tab",
      title: "Requests tab",
      body: "Participant portal service requests and tasks linked to this client. Portal submissions appear at the top with status and links to the review task or draft agreement variation. Assign and action AbilityVua tasks below.",
      windowKeys: ["clients"],
    },
  ],
};

export const locationsArticle: HelpArticle = {
  id: "article-locations",
  slug: "locations",
  title: "Locations",
  summary: "Manage SIL houses, day programs, and other sites with linked clients, staff, and services.",
  category: "Core",
  keywords: ["location", "support location", "SIL", "address", "assign client", "assign employee", "activity", "vehicle booking", "fleet", "transport"],
  relatedRoutes: ["/locations", "/locations/new"],
  windowKeys: ["locations"],
  lastUpdated: "2026-06-30",
  sections: [
    {
      id: "location-list",
      title: "Locations list",
      body: "All locations lists every support location. Open a row to edit site details and relationships.",
      relatedRoutes: ["/locations"],
    },
    {
      id: "create-location",
      title: "Create a location",
      steps: [
        "Open Locations and click New location.",
        "Complete Overview and Contact and address.",
        "Save the record.",
        "Add Clients, Employees, and Products and services lines as needed.",
      ],
      relatedRoutes: ["/locations/new"],
    },
    {
      id: "location-tabs",
      title: "Location tabs",
      bullets: [
        "Location: Overview, Contact and address",
        "Relationships: Alerts, Clients, Employees, Incidents, Maintenance, Vehicle bookings",
        "Services: Products and services",
        "History: Activity, Calendar",
      ],
    },
    {
      id: "location-activity",
      title: "Activity tab",
      body: "Log visits, maintenance, and operational notes for this location. The Activity tab uses the same summary list and line drawer pattern as client records: the table shows date, type, subject, and created by — click a row to open the editor for the full fields, including description. Use Add activity to create a new entry. Activity lines can only be removed by an administrator; other roles use Request deletion inside the editor to send a task to the admin team. Changes save with the parent location record.",
      windowKeys: ["location-activity"],
    },
    {
      id: "assignments",
      title: "Link clients, staff, and services",
      body: "The Alerts, Clients, Employees, and Products and services tabs all use the same summary list and side panel as Activity: the table is read-only, and clicking a row (or Add) opens the side panel with the full form, **Save** and **Cancel** in the panel footer, and Copy and Remove below. Save persists the parent location record — you do not need to scroll to the page save bar. Search still works, and changes save with the parent location record. Your role needs the matching assign-location process.",
      bullets: [
        "assign-location-client: link support receivers",
        "assign-location-employee: link staff",
        "assign-location-product: link products and services",
      ],
    },
    {
      id: "location-vehicle-bookings",
      title: "Book a vehicle for this site",
      body: "The Vehicle bookings tab reserves a fleet vehicle for this location without leaving the record. It uses the same form as Fleet → Bookings, with this location prefilled. Pick a vehicle, driver, optional client, start/end times, and purpose, then Save booking. Overlapping confirmed bookings for the same vehicle are blocked, and vehicle/driver compliance is checked before saving. Saved bookings appear in the list below the form and on this location's Calendar tab (tick Show vehicle bookings). The tab is shown to roles with Fleet → Bookings access.",
      steps: [
        "Open the location → Vehicle bookings (under Relationships).",
        "Pick a vehicle and driver; the location is prefilled. Add an optional client and a purpose.",
        "Set the start and end times for the reservation.",
        "Click Save booking. A clash with another confirmed booking or a compliance issue is shown inline.",
        "Open the Calendar tab and tick Show vehicle bookings to see it alongside shifts and maintenance.",
      ],
      relatedRoutes: ["/fleet"],
      windowKeys: ["fleet-bookings"],
    },
  ],
};
