import type { HelpArticle } from "@/lib/help/types";

export const deliveryArticle: HelpArticle = {
  id: "article-delivery",
  slug: "delivery",
  title: "Delivery — service bookings, rostering, and timesheets",
  summary: "Schedule NDIS service delivery, then roster staff and generate timesheets.",
  category: "Services",
  keywords: ["service booking", "rostering", "timesheet", "NDIS", "delivery", "schedule"],
  lastUpdated: "2026-06-19",
  sections: [
    {
      id: "overview",
      title: "Delivery stack",
      body: "Delivery covers service bookings, rostering, timesheets, and claiming. Service bookings and rostering are live — create shifts on the week calendar and link them to clients, workers, locations, and bookings.",
    },
    {
      id: "service-bookings",
      title: "Service bookings",
      body: "Each booking links to a client (business partner) and service agreement. Open from Delivery → Service bookings or from the client’s Service bookings tab. Lines hold products, weekly periods, quantities, and amounts — matching AbilityERP Service Booking Line.",
      relatedRoutes: ["/service-bookings", "/service-bookings/new"],
      windowKeys: ["service-bookings"],
    },
    {
      id: "booking-cancellation",
      title: "Cancellation policy",
      body: "When document status is Cancelled, complete cancellation details. The policy panel calculates notice given against the required period (default 7 clear days per NDIS) and estimates claimable amounts for short-notice participant cancellations.",
      steps: [
        "Set document status to Cancelled on the service booking Overview.",
        "Enter cancellation date, who initiated it, and a reason.",
        "Adjust required notice (days) if your service agreement differs from the 7-day default.",
        "Review the Cancellation policy panel for short-notice and estimated claimable amount.",
        "Save when compliance checks pass — missing cancellation fields block save.",
      ],
      relatedRoutes: ["/service-bookings"],
      windowKeys: ["service-bookings"],
      bullets: [
        "Participant short-notice cancellation may be claimable up to 100% if supports could have been delivered.",
        "Provider-initiated cancellations are not typically NDIS claimable.",
        "Cancellation date after the booking period ends is blocked — use Completed instead.",
        "Cancellation after an earlier line started but before a later line may show a short-notice warning.",
      ],
    },
    {
      id: "booking-compliance",
      title: "Booking compliance checks",
      body: "When you open or edit a service booking, the compliance panel lists pass, warning, and error checks. Errors block Save until resolved.",
      steps: [
        "Open Service bookings and select a booking, or create a new one.",
        "Select a business partner (client). The panel checks client lifecycle, dates, lines, and plan budget.",
        "Fix any red errors — for example start date after end date, booking after support ceased, or total exceeding remaining plan budget.",
        "Review yellow warnings (empty lines, intake/exit lifecycle, budget near limit) before confirming.",
        "Save when the panel shows no blocking errors.",
      ],
      relatedRoutes: ["/service-bookings", "/service-bookings/new"],
      windowKeys: ["service-bookings"],
      bullets: [
        "Client required — select a business partner.",
        "Dates — start on or before end; booking must not extend past support ceased date.",
        "Plan budget — booking total compared to client remaining plan budget (requires Plan budget lines on the client).",
        "Service agreement — must be Active and match the client; booking dates within agreement term.",
        "Consents — service delivery consent must not be refused.",
        "Lines — product required; line dates within booking period; amount should match price × quantity.",
        "Cancellation — required fields when status is Cancelled.",
      ],
    },
    {
      id: "booking-compliance-extended",
      title: "Extended compliance rules",
      body: "Additional checks run automatically with the compliance panel: service agreement linkage, core service delivery consent, line product and date validation, and completed-status rules.",
      steps: [
        "Link an Active service agreement on the booking Overview.",
        "Confirm the client has service delivery consent granted on Consents and Legal Orders.",
        "Add lines with products, dates inside the booking period, and matching amounts.",
        "Review warnings (missing agreement, pending consent, line amount mismatch) before save.",
        "Fix errors — refused consent, inactive agreement, or missing products block save.",
      ],
      relatedRoutes: ["/service-bookings"],
      windowKeys: ["service-bookings"],
    },
    {
      id: "rostering",
      title: "Rostering",
      body: "Build and review the week calendar. Each shift links to a client, worker, support location, and optional service booking. Use New shift or Add on a day to create one-off or weekly recurring shifts.",
      steps: [
        "Open Rostering and navigate weeks with Previous / Next week.",
        "Click New shift or Add on a day column.",
        "Select client, worker, location, and service booking.",
        "Review Staff–client matching hints — prior roster history, credentials, client risks, and suggested workers (advisory only).",
        "Optional: tick Repeat weekly, choose weekdays, and set number of weeks.",
        "Save — shifts appear on the calendar and persist after refresh.",
        "Click an existing shift card to edit.",
        "Drag a shift card to another day column to reschedule — conflict rules still apply for Published shifts.",
        "If a worker is double-booked, save is blocked and the shift card shows a Conflict badge.",
        "Publishing a shift (status Published, Publish week, RoC publish, or open-shift claim) hard-blocks worker double-booking and client time overlap — resolve conflicts before publish.",
        "On the Week tab, use Publish week to publish all staffed draft shifts at once — blocked shifts are listed with reasons.",
        "Switch to Forward plan to see roster hours by client across 4–12 weeks.",
        "Open Capacity to compare roster demand to active worker supply — flag weeks with unstaffed hours or workers over their weekly limit.",
        "Open Gaps to review vacant shifts and weeks where active bookings have no staffed coverage.",
        "Open Open shifts to browse the marketplace — coordinators assign cover; workers claim from My workplace → Open shifts.",
        "Workers check in from My workplace → My shifts — Verified badges, GPS links, and Geofence badges appear on staffed shift cards when check-in/out is outside the site radius.",
        "Open Rostering → RoC to import weekly roster-of-care CSV or generate a draft from a service agreement.",
        "On an Active RoC card, use Publish to roster — pick week start, number of weeks, and Draft status to create vacant shifts on the calendar.",
        "Assign workers on the week view, then set status to Published before generating timesheets.",
        "Use Add shift from a coverage gap to pre-fill the client and booking.",
      ],
      relatedRoutes: ["/rostering"],
      windowKeys: ["rostering"],
    },
    {
      id: "timesheets",
      title: "Timesheets",
      body: "Generate draft timesheets from published roster shifts for a pay period. Supervisors verify each line against worker check-in/out before approving for payroll export.",
      steps: [
        "Open Generate timesheets and set the pay period start and end dates.",
        "Review the preview — eligible Published or Completed shifts with a worker assigned are included.",
        "Click Generate timesheets — one draft timesheet is created per worker.",
        "Open Timesheets, select a record, and review shift lines linked to roster shifts.",
        "Review the Shift verification panel — verified lines match worker check-in/out; geofence warnings are advisory only.",
        "Set status to Submitted or Approved when all linked shifts are verified (or manually reviewed).",
        "On Timesheets, select approved records and use Payroll export to download a CSV for Keypay or Xero.",
        "When Keypay API credentials are configured (or KEYPAY_DRY_RUN=true in dev), use Export to Keypay API to post verified lines server-side.",
        "After pay run in Keypay or Xero, open Payroll reconciliation on Timesheets — enter paid hours and pay run reference for each exported record.",
        "Review Matched vs Variance status — variance within 0.05h counts as matched; larger gaps flag for audit before closing the pay period.",
        "Re-run generation for the same period to append new shifts to an existing Draft timesheet.",
      ],
      relatedRoutes: ["/timesheets", "/generate-timesheets"],
      windowKeys: ["timesheets", "generate-timesheets"],
    },
  ],
  relatedRoutes: [
    "/service-bookings",
    "/service-bookings/new",
    "/rostering",
    "/timesheets",
    "/generate-timesheets",
  ],
  windowKeys: ["service-bookings", "rostering", "timesheets", "generate-timesheets"],
};

export const servicePlanningArticle: HelpArticle = {
  id: "article-service-planning",
  slug: "service-planning",
  title: "Monthly service planning",
  summary: "Build monthly service plans from NDIS plan budget — planned hours and spend before rostering.",
  category: "Services",
  keywords: ["service planning", "monthly plan", "utilisation", "budget", "NDIS"],
  relatedRoutes: ["/service-planning", "/clients"],
  windowKeys: ["service-planning", "client-monthly-service-plan", "client-plan-budget"],
  lastUpdated: "2026-06-18",
  sections: [
    {
      id: "overview",
      title: "What monthly service plans do",
      body: "Monthly service plans translate a participant's NDIS plan budget into planned hours and spend for a calendar month. Use them before rostering and service bookings to check utilisation against allocated funding.",
    },
    {
      id: "hub",
      title: "Service planning hub",
      steps: [
        "Open Service planning in the Services menu.",
        "Click From plan budget to scaffold lines from the client's Plan budget tab.",
        "Enter planned hours and planned spend on each line.",
        "Set status to Approved when coordinators sign off the month.",
        "Open a plan to review summary cards — planned totals vs plan budget remaining.",
      ],
      relatedRoutes: ["/service-planning"],
    },
    {
      id: "client-tab",
      title: "On the client record",
      steps: [
        "Open the client → Monthly service plan tab.",
        "Generate from plan budget for a new month (requires Plan budget lines first).",
        "Select an existing plan from the dropdown or open the full plan view.",
      ],
      relatedRoutes: ["/clients"],
    },
    {
      id: "burn-rate-alerts",
      title: "Burn rate and forecast alerts",
      body: "Each plan shows utilisation, burn rate (claimed spend vs plan period elapsed), and projected utilisation at the current pace. Warnings flag underserviced participants, overspend risk, monthly plans above pace, and plan reviews due within 30 days.",
      steps: [
        "Open a monthly plan — review the Burn rate and forecast panel above the line table.",
        "On the Service planning list, check the Alerts column for plans that need review.",
        "Set plan review due on the client Full profile so period progress is calculated correctly.",
      ],
      relatedRoutes: ["/service-planning", "/clients"],
    },
    {
      id: "schads-cost-prediction",
      title: "SCHADS cost prediction",
      body: "Compare planned NDIS revenue to an estimated SCHADS labour cost from planned hours. This is a planning tool only — it uses weekday ordinary award rates and does not replace payroll.",
      steps: [
        "Open a monthly plan with planned hours on each line.",
        "Review the SCHADS cost prediction panel — totals and per-line margin.",
        "Change assumed employment type (e.g. Casual with 25% loading) to stress-test margin.",
      ],
      relatedRoutes: ["/service-planning"],
    },
  ],
};
