import type { HelpArticle } from "@/lib/help/types";

export const deliveryArticle: HelpArticle = {
  id: "article-delivery",
  slug: "delivery",
  title: "Delivery — service bookings, rostering, and timesheets",
  summary: "Schedule NDIS service delivery, roster staff, review open shift requests, and generate timesheets.",
  category: "Services",
  keywords: [
    "service booking",
    "rostering",
    "timesheet",
    "NDIS",
    "delivery",
    "schedule",
    "open shifts",
    "shift request",
    "critical fill",
    "fill board",
    "marketplace",
    "approve shift request",
  ],
  lastUpdated: "2026-06-28",
  sections: [
    {
      id: "overview",
      title: "Delivery stack",
      body: "Delivery covers service bookings, rostering, timesheets, and claiming. Service bookings and rostering are live — create shifts on the week calendar and link them to clients, workers, locations, and bookings.",
    },
    {
      id: "service-bookings",
      title: "Service bookings",
      body: "Each booking links to a client (business partner) and service agreement. Open from Delivery → Service bookings or from the client’s Service bookings tab. Lines hold products, weekly periods, quantities, and amounts — matching AbilityERP Service Booking Line.",
      relatedRoutes: ["/service-bookings", "/service-bookings/new"],
      windowKeys: ["service-bookings"],
    },
    {
      id: "booking-cancellation",
      title: "Cancellation policy",
      body: "When document status is Cancelled, complete cancellation details. The policy panel calculates notice given against the required period (default 7 clear days per NDIS) and estimates claimable amounts for short-notice participant cancellations.",
      steps: [
        "Set document status to Cancelled on the service booking Overview.",
        "Enter cancellation date, who initiated it, and a reason.",
        "Adjust required notice (days) if your service agreement differs from the 7-day default.",
        "Review the Cancellation policy panel for short-notice and estimated claimable amount.",
        "Save when compliance checks pass — missing cancellation fields block save.",
      ],
      relatedRoutes: ["/service-bookings"],
      windowKeys: ["service-bookings"],
      bullets: [
        "Participant short-notice cancellation may be claimable up to 100% if supports could have been delivered.",
        "Provider-initiated cancellations are not typically NDIS claimable.",
        "Cancellation date after the booking period ends is blocked — use Completed instead.",
        "Cancellation after an earlier line started but before a later line may show a short-notice warning.",
      ],
    },
    {
      id: "booking-compliance",
      title: "Booking compliance checks",
      body: "When you open or edit a service booking, the compliance panel lists pass, warning, and error checks. Errors block Save until resolved.",
      steps: [
        "Open Service bookings and select a booking, or create a new one.",
        "Select a business partner (client). The panel checks client lifecycle, dates, lines, and plan budget.",
        "Fix any red errors — for example start date after end date, booking after support ceased, or total exceeding remaining plan budget.",
        "Review yellow warnings (empty lines, intake/exit lifecycle, budget near limit) before confirming.",
        "Save when the panel shows no blocking errors.",
      ],
      relatedRoutes: ["/service-bookings", "/service-bookings/new"],
      windowKeys: ["service-bookings"],
      bullets: [
        "Client required — select a business partner.",
        "Dates — start on or before end; booking must not extend past support ceased date.",
        "Plan budget — booking total compared to client remaining plan budget (requires Plan budget lines on the client).",
        "Service agreement — must be Active and match the client; booking dates within agreement term.",
        "Consents — service delivery consent must not be refused.",
        "Lines — product required; line dates within booking period; amount should match price × quantity.",
        "Cancellation — required fields when status is Cancelled.",
      ],
    },
    {
      id: "booking-compliance-extended",
      title: "Extended compliance rules",
      body: "Additional checks run automatically with the compliance panel: service agreement linkage, core service delivery consent, line product and date validation, and completed-status rules.",
      steps: [
        "Link an Active service agreement on the booking Overview.",
        "Confirm the client has service delivery consent granted on Consents and Legal Orders.",
        "Add lines with products, dates inside the booking period, and matching amounts.",
        "Review warnings (missing agreement, pending consent, line amount mismatch) before save.",
        "Fix errors — refused consent, inactive agreement, or missing products block save.",
      ],
      relatedRoutes: ["/service-bookings"],
      windowKeys: ["service-bookings"],
    },
    {
      id: "rostering",
      title: "Rostering",
      body: "Build and review the week calendar. Service-delivery shifts can hold one or more client billing lines and worker payroll lines. Use New shift or Add on a day to create one-off or weekly recurring shifts.",
      steps: [
        "Open Rostering and navigate weeks with Previous / Next week.",
        "On the Week tab, click Export week CSV to download the visible week for payroll handoff or external scheduling tools.",
        "Click New shift or Add on a day column.",
        "For service delivery, add clients under Clients (billing), set ratios such as 1:4, then add workers under Workers (payroll).",
        "Review Staff–client matching hints — prior roster history, credentials, client risks, and suggested workers (advisory only).",
        "Optional: tick Repeat weekly, choose weekdays, and set number of weeks.",
        "Save — shifts appear on the calendar and persist after refresh.",
        "Click an existing shift card to edit.",
        "Drag a shift card to another day column to reschedule — conflict rules still apply for Published shifts.",
        "If a worker is double-booked, save is blocked and the shift card shows a Conflict badge.",
        "Publishing a shift (status Published, Publish week, RoC publish, or approving an open shift request) hard-blocks worker double-booking and client time overlap — resolve conflicts before publish.",
        "On the Week tab, use Publish week to publish all staffed draft shifts at once — blocked shifts are listed with reasons.",
        "Switch to Forward plan to see roster hours by client across 4–12 weeks.",
        "Open Fortnight review and select the pay period — compare active RoC template lines with the live roster for that fortnight. Missing actuals, draft shifts, vacant shifts, worker changes, and extra actuals are listed as actions.",
        "Open Capacity to compare roster demand to active worker supply — flag weeks with unstaffed hours or workers over their weekly limit.",
        "On Capacity, pick a pay period — the capacity grid aligns to that fortnight and the Contracted hours table shows employees below their contracted minimum; find-and-fill prioritises them when assigning open shifts.",
        "Open Gaps to review vacant shifts and weeks where active bookings have no staffed coverage.",
        "On a vacant shift in Gaps, click Request agency to start an agency coverage request — see Help → How to manage agency staff for the full vendor → shift pack → confirm workflow.",
        "Agency-confirmed shifts show the worker name with an Agency badge on the week calendar.",
        "Register and maintain agency workers under People → Agency workers — each must be linked to who they work for (staffing vendor business partner).",
        "Open Open shifts to browse the vacant shift marketplace — see worker requests, assign cover directly, or review applicants.",
        "Workers submit requests from My workplace → Open shifts — see Help → My workplace self-service for the employee workflow.",
        "Workers check in from My workplace → My shifts — Verified badges, GPS links, and Geofence badges appear on staffed shift cards when check-in/out is outside the site radius.",
        "Open Rostering → RoC to import weekly roster-of-care CSV or generate a draft from a service agreement.",
        "Review Organisation → Roster rollover defaults — maintain ahead defaults to 2 weeks (one fortnight), plus Draft/Published status and skip-existing behaviour.",
        "On an Active RoC card, use Publish to roster — it rolls master RoC lines into live shifts using those defaults; matching session keys at the same time/location become one multi-client session.",
        "When a template worker is on approved leave for a shift date, rollover creates a vacant fill slot (open shifts / marketplace) and a separate leave-pay worker line for planned roster payroll — the preview warns how many leave splits were applied.",
        "To roll forward many templates at once, use Rostering → RoC → Bulk rollover: choose All active rosters of care, By client, or By location, set the week range and status, then Publish — shared session keys merge into one session and Skip dates already published prevents duplicates.",
        "After a bulk rollover, the panel shows a publish summary and Undo last rollover, which cancels the shifts from the most recent batch if the range or scope was wrong.",
        "When leave is approved after rollover (including mid-fortnight), Workforce planning → Review queue releases rolled shifts in the leave date range: the worker is removed from the fill slot, the shift stays available for cover, and a leave-pay line is added for timesheet generation. Shifts with check-in are skipped.",
        "By location publishes only the lines delivered at the selected location (for example a SIL house), not the day-program lines those participants attend elsewhere.",
        "Assign workers on the week view, then set status to Published before generating timesheets.",
        "For shared sessions, every assigned worker line appears in that worker's My shifts, check-in, employee Schedule, and timesheet generation — not just the primary worker displayed on the shift header.",
        "Use Add shift from a coverage gap to pre-fill the client and booking.",
        "Open a client → Roster of care tab to review weekly care templates, hour totals, and rostered vs required hours.",
        "Open an employee → Schedule tab for their week calendar; Schedule template for weekly availability (coordinators with Workforce planning access).",
        "On a staffed shift card, click Add buddy shift to roster a shadow/orientation shift linked to the primary worker.",
        "Set participant billing (billable or non-billable) and worker pay (paid or non-payable) — org policy may default or ask each time (System → Organisation → Buddy shifts).",
        "Buddy shifts show Buddy, Non-payable, and Non-billable badges on the calendar. Cancelling the primary shift also cancels linked buddy shifts.",
      ],
      relatedRoutes: ["/rostering"],
      windowKeys: ["rostering"],
    },
    {
      id: "open-shift-requests",
      title: "Open shift marketplace and requests",
      body: "Vacant published shifts appear on Rostering → Open shifts and on each worker's My workplace → Open shifts. Workers submit requests; rostering reviews applicants and assigns one worker. Direct assignment without a request is still available via Assign worker on the coordinator view.\n\nEach shift shows a fill status badge: Open (no pending requests), Requested (one or more pending applications), or Filled once a worker is assigned. Critical fill shifts show a red Critical fill label — workers can respond with Available if critical or Decline in addition to a normal request.",
      steps: [
        "Open Rostering → Open shifts to see all vacant marketplace shifts across locations you can access.",
        "Shifts with pending applications show a request count badge — click Review requests to open the review panel.",
        "Review each applicant: response type (Requested shift vs Available if critical), availability match, hours free this week, staff–client matching hints, and prior rejected requests on other shifts.",
        "Click Approve & assign on a full Request shift to assign that worker, publish the shift if Draft, and auto-reject other pending requests for the same shift.",
        "Available if critical responses appear in the panel for context — use Assign worker on the shift card or approve a full Request shift to roster them.",
        "Click Reject to decline an applicant — optional reason is stored on the audit trail.",
        "Prior responses lists withdrawn, declined, and previously rejected applications for the same shift.",
        "Use Assign worker to roster someone directly without going through the request queue.",
        "Mark critical fill when a shift is urgent — workers see it first on Open shifts with extra response options. Remove critical fill when urgency passes.",
      ],
      relatedRoutes: ["/rostering", "/my/open-shifts", "/workforce-planning#fill-board"],
      windowKeys: ["rostering", "my-open-shifts"],
    },
    {
      id: "fill-board-requests",
      title: "Workforce planning fill board",
      body: "Workforce planning → Roster fill board lists vacant shifts for the selected focus week with employee requests, critical fill flags, and suggested workers ranked by client match and remaining weekly capacity.\n\nUse filter chips to triage cover: All vacant, Open — no requests, Open with requests, Awaiting decision (shifts with pending applications), and Critical fill. Each card shows pending request count and Review requests opens the same panel as Rostering → Open shifts.\n\nSuggested workers appear when the system finds active staff with remaining hours — click Assign to roster directly. Combine fill board triage with Rostering → Open shifts when you need the full marketplace list beyond the focus week.",
      steps: [
        "Open Workforce planning and scroll to Roster fill board (or use the Fill board quick link).",
        "Set Focus week starting to the roster week you are filling.",
        "Choose a filter — start with Critical fill or Open with requests when cover is urgent.",
        "Click Review requests on a shift card to approve, reject, or toggle critical fill.",
        "Or click Assign on a suggested worker when you already know who should take the shift.",
        "Open rostering from the card link to edit shift details on the week calendar.",
      ],
      relatedRoutes: ["/workforce-planning#fill-board", "/rostering"],
      windowKeys: ["workforce-planning", "rostering"],
    },
    {
      id: "open-shift-coordinator-faq",
      title: "Open shifts — coordinator questions",
      body: "Common rostering questions about the request workflow.",
      bullets: [
        "How do workers apply? — My workplace → Open shifts → Request shift. They need a linked employee record and rostering window access is not required.",
        "Can I assign without waiting for requests? — Yes. Assign worker on Rostering → Open shifts or Assign on the fill board suggested worker list.",
        "What happens when I approve one request? — That worker is assigned, the shift leaves the marketplace, and other pending requests for the same shift are rejected automatically.",
        "Why is Approve & assign missing? — Only full Request shift responses can be approved in one click. Available if critical is informational — assign manually or wait for a full request.",
        "Where is audit history? — Request rows store submitted, decided, and rejection fields. Shift cards and review panels show prior declined/rejected responses.",
        "Location security — workers only request at assigned locations by default; coordinators with Can see all locations see the full marketplace.",
      ],
      relatedRoutes: ["/rostering", "/workforce-planning#fill-board", "/my/open-shifts"],
      windowKeys: ["rostering", "workforce-planning"],
    },
    {
      id: "rostering-communication",
      title: "Rostering Communication tasks",
      body: "Employees can contact rostering from My workplace → Open shifts or My workplace → My shifts. Each submission creates a Rostering Communication task assigned to the Rostering Officer role. The task is also visible to the employee who created it, so both sides can continue the conversation on the same task until it is resolved.\n\nThe initial task description stores category, priority, sender, optional related shift, and the message. Task updates act as the conversation history; completing or cancelling the task closes the communication.",
      steps: [
        "Rostering Officer: open Tasks → To my role.",
        "Filter or scan for task type Rostering communication.",
        "Open the task to read the subject, category, priority, sender, message, and related shift if present.",
        "Use Update to reply or ask for more detail — the employee sees the update in the same task.",
        "Use In progress while the item is being worked.",
        "Use Task completed when the rostering question is resolved.",
      ],
      relatedRoutes: ["/tasks", "/my/open-shifts", "/my/shifts"],
      windowKeys: ["tasks-for-my-role", "tasks-assigned-to-me", "my-open-shifts", "my-shifts"],
    },
    {
      id: "timesheets",
      title: "Timesheets",
      body: "Generate draft timesheets from published roster shifts for a pay period. Supervisors verify each line against worker check-in/out before approving for payroll export.",
      steps: [
        "Open Generate timesheets and select the pay period (defaults to the current open period from Admin → Pay periods). Archived periods show as payroll archived in the picker.",
        "Review the preview — eligible Published or Completed shifts with a worker assigned are included.",
        "Click Generate timesheets — one draft timesheet is created per worker.",
        "Open Timesheets, select a record, and review shift lines linked to roster shifts.",
        "Review the Shift verification panel — verified lines match worker check-in/out; geofence warnings are advisory only.",
        "Set status to Submitted or Approved when all linked shifts are verified (or manually reviewed).",
        "On Timesheets, select approved records and use Payroll export to download a CSV for Keypay or Xero.",
        "When Keypay API credentials are configured (or KEYPAY_DRY_RUN=true in dev), use Export to Keypay API to post verified lines server-side.",
        "After pay run in Keypay or Xero, open Payroll reconciliation on Timesheets — enter paid hours and pay run reference for each exported record.",
        "Use summary cards to see exported vs paid hours, pending count, and matched records for the pay period.",
        "Select multiple timesheets and Reconcile at exported hours when payroll matches exported totals — one pay run reference for the batch.",
        "Filter the reconciliation table or timesheet list by Pending, Matched, or Variance.",
        "Before archiving a pay period, open Payroll period close on Timesheets — select the pay period, confirm approve, export, and reconcile checks pass, then Mark period closed with the pay run reference.",
        "Review Matched vs Variance status — variance within 0.05h counts as matched; larger gaps flag for audit before closing the pay period.",
        "Re-run generation for the same period to append new shifts to an existing Draft timesheet.",
      ],
      relatedRoutes: ["/timesheets", "/generate-timesheets"],
      windowKeys: ["timesheets", "generate-timesheets"],
    },
    {
      id: "claims",
      title: "NDIS claims",
      body: "Generate draft claim batches from approved timesheet lines that passed shift verification. PAPL validation checks support items, prices, and booking readiness before gateway submission.",
      steps: [
        "Approve timesheets only after shift verification passes (check-in/out matches scheduled hours).",
        "Open Generate claims and set the claim period start and end dates.",
        "Review the preview — eligible lines come from Approved timesheets with verified roster links.",
        "Click Generate claims — one Draft claim is created per participant for the period.",
        "Open Claims, select a batch, and review the PAPL validation panel.",
        "Fix blocking errors (missing product, price over limit, cancelled booking) before setting status to Submitted.",
        "Fix blocking errors before saving.",
        "Use Submit to gateway on the claim detail page — sets status to Submitted with a gateway reference.",
        "Set NDIS_GATEWAY_DRY_RUN=true in Amplify for dry-run gateway testing without live PRODA credentials.",
        "After NDIA payment advice arrives, open Claims → Remittance import — paste or upload the CSV.",
        "Preview matches against submitted claims, then Apply remittance to mark claims Paid and Accepted.",
        "Download template from the remittance panel to test with existing gateway-submitted claims.",
      ],
      relatedRoutes: ["/claims", "/generate-claims", "/claim-reconciliation"],
      windowKeys: ["claims", "generate-claims", "claim-reconciliation"],
    },
    {
      id: "claim-reconciliation",
      title: "Claim reconciliation dashboard",
      body: "Review submitted and accepted NDIS claims against remittance payments. Find unmatched batches and payment variances before financial close.",
      steps: [
        "Open Claim reconciliation from the Claims menu or sidebar.",
        "Filter by claim period month and remittance status.",
        "Review Not imported rows — import remittance CSV from the Claims list when payment advice arrives.",
        "Investigate Variance rows — open the claim to compare line amounts to paid totals.",
        "Export CSV for finance or audit review.",
      ],
      relatedRoutes: ["/claim-reconciliation", "/claims"],
      windowKeys: ["claim-reconciliation", "claims"],
    },
    {
      id: "invoice-reconciliation",
      title: "Invoice reconciliation dashboard",
      body: "Review sent participant invoices against recorded payments. Flag unpaid and overdue invoices before month-end financial close.",
      steps: [
        "Open Invoice reconciliation from the Invoices menu or Financial close page.",
        "Filter by invoice period month and reconcile status.",
        "Review Unpaid and Overdue rows — open the invoice to record payment or follow up.",
        "Export CSV for finance review.",
      ],
      relatedRoutes: ["/invoice-reconciliation", "/invoices", "/financial-close"],
      windowKeys: ["invoice-reconciliation", "invoices", "financial-close"],
    },
    {
      id: "plan-budget-claimed-rollup",
      title: "Plan budget billing claimed rollup",
      body: "Sync plan budget claimed amounts from submitted NDIS claims and sent participant invoices.",
      steps: [
        "Open the client record → Plan budget tab.",
        "Review the Billing claimed rollup panel — compare manual claimed to billing totals by category.",
        "Click Apply billing rollup when billing differs from manual entries.",
        "Save the client record to persist updated claimed amounts.",
      ],
      relatedRoutes: ["/clients"],
      windowKeys: ["clients"],
    },
    {
      id: "multi-provider-budget",
      title: "Multi-provider budget view",
      body: "Compare NDIS plan budget allocations across providers when a participant receives support from more than one organisation.",
      steps: [
        "Set Plan provider on each budget line on the client Plan budget tab.",
        "Open Service planning → Multi-provider budget.",
        "Filter by provider and export CSV for coordination meetings.",
      ],
      relatedRoutes: ["/multi-provider-budget", "/service-planning"],
      windowKeys: ["multi-provider-budget", "service-planning", "clients"],
    },
    {
      id: "timesheet-submit-approval",
      title: "Timesheet submit and approval",
      body: "Workers submit draft timesheets from My workplace. Supervisors approve submitted timesheets after shift verification passes.",
      steps: [
        "Worker: My workplace → My timesheets → Submit on a draft timesheet.",
        "Supervisor: Timesheets → open the submitted record → Approve timesheet when verification is green.",
        "Approved timesheets feed Generate claims and payroll export.",
      ],
      relatedRoutes: ["/my/timesheets", "/timesheets"],
      windowKeys: ["my-timesheets", "timesheets"],
    },
    {
      id: "timesheet-approval",
      title: "Timesheet approval queue",
      body: "Supervisors approve submitted timesheets in scope — management line (all reports), direct reports, assigned sites, or all submitted for coordinators. Ready timesheets can be bulk-approved; blocked rows need shift verification first.",
      steps: [
        "Open Timesheet approval from the sidebar (Service delivery).",
        "Choose scope: My management line, My direct reports, My site(s), a specific location, or All submitted (coordinators).",
        "Review Ready, Review, and Blocked tabs — ready rows are safe to bulk approve.",
        "Use Approve all ready or select rows and Approve selected.",
        "Open blocked or review rows to fix check-in/out or roster links on the full timesheet record.",
      ],
      relatedRoutes: ["/timesheet-approval", "/timesheets"],
      windowKeys: ["timesheet-approval", "approve-timesheet"],
    },
    {
      id: "document-templates",
      title: "Document templates and generated documents",
      body: "System operators manage print layouts; workspace users print or generate HTML stored in the document registry. For step-by-step edit, duplicate, save, and process binding instructions, see [Document templates](/system/guides/document-templates) in System setup guides.",
      steps: [
        "System → Tasks → Document templates — edit title, footer, and active; duplicate to create a copy; set default templates per print process.",
        "System → Organisation → Document branding — bank details and default footer (see Organisation setup guide).",
        "System → Tasks → Document registry — view generated documents.",
        "Invoices → Send via Email — saves to registry, generates PDF, and opens your email app.",
        "Invoices → Print invoice or Batch print; Enquiries → Print acknowledgement; Clients → Print statement or consent schedule.",
        "Claims → Print claim batch; Incidents → Print notification; NDIS audit pack → Print audit pack.",
        "Employees → Documents → Generate contract, offer letter, or separation letter.",
      ],
      relatedRoutes: [
        "/system/admin/document-templates",
        "/system/admin/document-registry",
        "/invoices",
        "/enquiries",
        "/invoice-reconciliation",
        "/clients",
        "/board-reporting",
        "/service-agreements",
        "/system/organization",
      ],
      windowKeys: [
        "admin-document-templates",
        "invoices",
        "enquiries",
        "invoice-reconciliation",
        "clients",
        "board-reporting",
        "service-agreements",
        "admin-organization",
      ],
    },
    {
      id: "financial-close",
      title: "Financial close checklist",
      body: "Month-end sign-off across plan delivery, NDIS remittance, participant invoices, and payroll reconciliation.",
      steps: [
        "Open Financial close from the sidebar or Reports area.",
        "Select the close month to review.",
        "Resolve any blocked checks — plan variance, claim remittance gaps, draft invoices, or payroll items.",
        "Review invoice payment warnings on the checklist — open Invoice reconciliation when unpaid invoices remain.",
        "When all checks pass, use Mark month closed to lock the calendar month.",
        "Use Review links to open plan reconciliation, claim reconciliation, invoices, or timesheets.",
        "Export CSV when all checks pass for audit records.",
        "Run the Financial close summary report from Reports for a CSV archive.",
      ],
      relatedRoutes: ["/financial-close", "/plan-reconciliation", "/claim-reconciliation", "/invoice-reconciliation", "/reports/financial-close-summary"],
      windowKeys: ["financial-close", "plan-reconciliation", "claim-reconciliation", "invoice-reconciliation", "claims", "invoices", "timesheets"],
    },
    {
      id: "ndis-audit-pack",
      title: "NDIS audit pack export",
      body: "Prepare audit evidence for a selected month — participants, agreements, timesheets, claims, invoices, incidents, plan reconciliation, financial close, and worker credentials.",
      steps: [
        "Open NDIS audit pack from the sidebar or Reports area.",
        "Select the audit month to review.",
        "Resolve blocked sections before handoff to auditors.",
        "Export the manifest CSV for the section summary.",
        "Export individual section CSVs for evidence attachments.",
        "Print audit pack — printable readiness report saved to the document registry.",
        "Run the NDIS audit pack summary report from Reports for an archive copy.",
      ],
      relatedRoutes: ["/ndis-audit-pack", "/financial-close", "/reports/ndis-audit-pack-summary"],
      windowKeys: ["ndis-audit-pack", "financial-close", "plan-reconciliation", "claim-reconciliation", "incidents"],
    },
    {
      id: "board-reporting",
      title: "NDIS board reporting",
      body: "Generate monthly board report packs with configurable sections, data-driven metrics from AbilityVua, executive commentary, and a printable board-ready export.",
      steps: [
        "Open Board reporting from Reports or the sidebar.",
        "Create a new report and choose the reporting period (for example June 2026).",
        "Use Configure sections to include, exclude, or reorder report sections.",
        "Click Generate report to refresh data-driven content from clients, claims, incidents, rostering, and finance.",
        "Add executive summary, CEO commentary, and section commentary where needed.",
        "Save draft, then mark reviewed, approve, and publish when ready for the board.",
        "Board members with read access see published reports only.",
        "Use Print / export for a clean board pack without app navigation.",
      ],
      relatedRoutes: ["/board-reporting", "/reports"],
      windowKeys: ["board-reporting"],
    },
    {
      id: "cancellation-claims",
      title: "Cancellation claim generation",
      body: "Generate draft NDIS claim lines from cancelled service bookings where the participant cancelled with insufficient notice. Uses the same cancellation policy as the booking compliance panel.",
      steps: [
        "Cancel a service booking with status Cancelled, cancellation date, initiator Participant, and a short-notice reason.",
        "Open Generate claims → Cancellation claims panel.",
        "Review eligible bookings, claimable total, and already-linked count.",
        "Click Generate cancellation claims — one draft claim per participant for the booking period.",
        "Open the draft claim, review PAPL validation, and submit when ready.",
      ],
      relatedRoutes: ["/generate-claims", "/service-bookings", "/claims"],
      windowKeys: ["generate-claims", "claims", "service-bookings"],
    },
    {
      id: "invoices",
      title: "Participant invoices",
      body: "Generate draft invoices for plan-managed and self-managed participants from verified timesheet lines. Agency-managed participants are billed via NDIS claims instead.",
      steps: [
        "Set the client Funding body to a plan-managed or self-managed option on the client record.",
        "Approve timesheets with verified shift check-ins for the billing period.",
        "Open Generate invoices and set the invoice period start and end dates.",
        "Review the preview — agency-managed lines are skipped automatically.",
        "Click Generate invoices — one Draft invoice is created per participant.",
        "Open the invoice, confirm Invoice to and due date, and fix any PAPL validation errors.",
        "Mark as sent when the invoice is issued to the plan manager or participant.",
        "Use Print invoice on the invoice detail page to open a printable tax invoice for email or post.",
        "Record payment status and paid amount when payment is received.",
      ],
      relatedRoutes: ["/invoices", "/generate-invoices"],
      windowKeys: ["invoices", "generate-invoices"],
    },
  ],
  relatedRoutes: [
    "/service-bookings",
    "/service-bookings/new",
    "/rostering",
    "/timesheets",
    "/generate-timesheets",
    "/claims",
    "/generate-claims",
    "/claim-reconciliation",
    "/invoice-reconciliation",
    "/multi-provider-budget",
    "/financial-close",
    "/ndis-audit-pack",
    "/invoices",
    "/generate-invoices",
  ],
  windowKeys: [
    "service-bookings",
    "rostering",
    "timesheets",
    "generate-timesheets",
    "claims",
    "generate-claims",
    "claim-reconciliation",
    "invoice-reconciliation",
    "multi-provider-budget",
    "financial-close",
    "ndis-audit-pack",
    "invoices",
    "generate-invoices",
  ],
};

export const servicePlanningArticle: HelpArticle = {
  id: "article-service-planning",
  slug: "service-planning",
  title: "Monthly service planning",
  summary: "Build monthly service plans from NDIS plan budget — planned hours and spend before rostering.",
  category: "Services",
  keywords: ["service planning", "monthly plan", "utilisation", "budget", "NDIS"],
  relatedRoutes: ["/service-planning", "/plan-reconciliation", "/clients"],
  windowKeys: ["service-planning", "plan-reconciliation", "client-monthly-service-plan", "client-plan-budget"],
  lastUpdated: "2026-06-21",
  sections: [
    {
      id: "overview",
      title: "What monthly service plans do",
      body: "Monthly service plans translate a participant's NDIS plan budget into planned hours and spend for a calendar month. Use them before rostering and service bookings to check utilisation against allocated funding.",
    },
    {
      id: "hub",
      title: "Service planning hub",
      steps: [
        "Open Service planning in the Services menu.",
        "Click From plan budget to scaffold lines from the client's Plan budget tab.",
        "Enter planned hours and planned spend on each line.",
        "Set status to Approved when coordinators sign off the month.",
        "Open a plan to review summary cards — planned totals vs plan budget remaining.",
      ],
      relatedRoutes: ["/service-planning"],
    },
    {
      id: "client-tab",
      title: "On the client record",
      steps: [
        "Open the client → Monthly service plan tab.",
        "Generate from plan budget for a new month (requires Plan budget lines first).",
        "Select an existing plan from the dropdown or open the full plan view.",
      ],
      relatedRoutes: ["/clients"],
    },
    {
      id: "burn-rate-alerts",
      title: "Burn rate and forecast alerts",
      body: "Each plan shows utilisation, burn rate (claimed spend vs plan period elapsed), and projected utilisation at the current pace. Warnings flag underserviced participants, overspend risk, monthly plans above pace, and plan reviews due within 30 days.",
      steps: [
        "Open a monthly plan — review the Burn rate and forecast panel above the line table.",
        "On the Service planning list, check the Alerts column for plans that need review.",
        "Set plan review due on the client Full profile so period progress is calculated correctly.",
      ],
      relatedRoutes: ["/service-planning", "/clients"],
    },
    {
      id: "schads-cost-prediction",
      title: "SCHADS cost prediction",
      body: "Compare planned NDIS revenue to an estimated SCHADS labour cost from planned hours. This is a planning tool only — it uses weekday ordinary award rates and does not replace payroll.",
      steps: [
        "Open a monthly plan with planned hours on each line.",
        "Review the SCHADS cost prediction panel — totals and per-line margin.",
        "Change assumed employment type (e.g. Casual with 25% loading) to stress-test margin.",
      ],
      relatedRoutes: ["/service-planning"],
    },
    {
      id: "plan-reconciliation",
      title: "Plan vs actual reconciliation",
      body: "Compare monthly service plan hours and spend to approved timesheet delivery and billed claim or invoice amounts. Flag variance before month-end close.",
      steps: [
        "Open Plan reconciliation from the Service planning menu.",
        "Select the plan month to review.",
        "Review Scheduled h (rostered hours), Actual h, Billed $, Rejected $, and variance columns.",
        "Check Matched vs Variance rows — hours tolerance is 0.5h and amount tolerance is $1.",
        "Investigate Rejected $ when NDIS claims were rejected or gateway-paid amounts differ.",
        "Open the linked monthly plan or client record to investigate variance.",
        "Export CSV for finance or audit review.",
      ],
      relatedRoutes: ["/plan-reconciliation", "/service-planning"],
      windowKeys: ["plan-reconciliation"],
    },
  ],
};
