import type { HelpArticle } from "@/lib/help/types";

export const documentTemplatesArticle: HelpArticle = {
  id: "article-document-templates",
  slug: "document-templates",
  title: "Document templates: edit, duplicate, and assign to processes",
  summary:
    "Manage print layouts in System — update title and footer, duplicate templates, set which layout runs for each print action, and configure org branding.",
  category: "System setup",
  keywords: [
    "document template",
    "print invoice",
    "document registry",
    "duplicate template",
    "process binding",
    "footer",
    "branding",
    "save template",
    "how to",
    "admin document templates",
  ],
  relatedRoutes: [
    "/system/admin/document-templates",
    "/system/admin/document-registry",
    "/system/organization",
    "/invoices",
    "/claims",
    "/incidents",
    "/clients",
  ],
  windowKeys: ["admin-document-templates", "admin-organization"],
  lastUpdated: "2026-06-22",
  sections: [
    {
      id: "what-templates-are",
      title: "What document templates are",
      body: "Document templates control the look of printable documents — invoices, agreements, HR letters, enquiry acknowledgements, and more. Every template shares the same org header and footer from your organisation profile.\n\nAbilityAPP stores generated HTML in the document registry. Users print or download in the workspace; use Save as PDF from the browser print dialog when you need a file. Delivery stays in-system — there is no outbound email for invoices or documents.",
      relatedRoutes: ["/system/admin/document-templates", "/system/admin/document-registry"],
      windowKeys: ["admin-document-templates"],
    },
    {
      id: "who-can-edit",
      title: "Who can edit templates vs who can print",
      body: "Two different permissions apply:",
      bullets: [
        "Edit templates — System → Tasks → Document templates. Requires the admin-document-templates window (typically System Admin).",
        "Print or generate documents — workspace actions such as Print invoice or Generate contract. Requires the matching print process on the user's role (for example print-invoice, print-employee-offer).",
        "Finance staff can print invoices without access to the template editor.",
        "Only System operators change layouts, footers, and process bindings.",
      ],
      relatedRoutes: ["/system/admin/document-templates", "/admin/roles"],
      windowKeys: ["admin-document-templates", "admin-roles"],
    },
    {
      id: "open-templates-page",
      title: "Open the document templates page",
      steps: [
        "Sign in to System (not the main workspace login if your tenant separates them).",
        "Open System → Tasks → Document templates.",
        "The left panel lists all templates. Select one to edit.",
        "Use the link to Document registry to review generated files.",
      ],
      relatedRoutes: ["/system/admin/document-templates"],
    },
    {
      id: "update-and-save",
      title: "Update a template and save",
      body: "You can change these fields on each template. After editing, use the Save bar at the bottom of the screen — bindings save separately (see below).",
      bullets: [
        "Document title — heading shown on the printed document.",
        "Description — internal note for operators; not printed.",
        "Footer override — replaces the org default footer on this template only. Leave blank to use System → Organisation → Document branding.",
        "Active — only Active templates appear in process dropdowns and print pickers.",
        "Default for class — marks the template as the class default; process bindings are the main control.",
      ],
      steps: [
        "Select a template from the list.",
        "Edit Document title, Description, or Footer override.",
        "Tick or untick Active as needed.",
        "Confirm changes in Preview (sample record) at the bottom.",
        "Click Save on the unsaved-changes bar.",
        "Refresh the page to confirm your edits persisted.",
      ],
      relatedRoutes: ["/system/admin/document-templates"],
    },
    {
      id: "what-you-cannot-edit",
      title: "What you cannot edit in the UI yet",
      body: "The template editor does not yet include a clause or block editor. These are fixed by the document class (invoice, service agreement, HR letter, etc.):",
      bullets: [
        "Template name in the list — use Duplicate to create a copy named \"… (copy)\".",
        "Legal clause / body HTML — rich-text blocks are seeded with scaffold wording.",
        "Line tables, signatures, and layout structure — driven by the document class render engine.",
        "Creating a wholly new document type — requires a development change and database migration.",
      ],
      relatedRoutes: ["/system/admin/document-templates"],
    },
    {
      id: "duplicate-template",
      title: "Create a new variant (duplicate)",
      body: "There is no blank \"New template\" button. To create your own variant, duplicate an existing template of the same type.",
      steps: [
        "Select the closest seeded template (for example NDIS participant invoice).",
        "Click Duplicate template — a copy appears in the list with \"(copy)\" in the name.",
        "Set Document title and Footer override on the copy.",
        "Ensure Active is ticked.",
        "Save the template.",
        "In Default templates by process (top of page), select your copy for the relevant action (for example Print invoice).",
        "Test print from the workspace and confirm a row appears in Document registry.",
      ],
      relatedRoutes: ["/system/admin/document-templates"],
    },
    {
      id: "process-bindings",
      title: "Assign templates to print actions",
      body: "Default templates by process controls which Active template runs when a user clicks Print invoice, Print claim batch, Generate offer letter, and so on. Changing a dropdown saves immediately — no separate Save click.",
      bullets: [
        "Print invoice (detail) and Batch print invoices — invoice class templates.",
        "Print service agreement / variation — agreement class templates.",
        "Generate employee contract / offer / separation — HR class templates.",
        "Print enquiry acknowledgement, remittance cover, participant statement, board report.",
        "Print claim batch, incident notification, audit pack, consent schedule.",
      ],
      steps: [
        "Open Default templates by process at the top of Document templates.",
        "For each action your organisation uses, pick the Active template from the dropdown.",
        "Wait for the save to complete (no error message).",
        "Ask a user with the matching print process to test from the workspace.",
      ],
      relatedRoutes: ["/system/admin/document-templates"],
    },
    {
      id: "org-branding",
      title: "Organisation header, footer, and bank details",
      body: "Templates pull org header (logo, ABN, NDIS registration) and default footer from the organisation profile. Set these once — they apply to all templates unless a template has a footer override.",
      steps: [
        "Open System → Organisation → Organisation profile.",
        "Complete provider details, contact, and NDIS registration.",
        "Open the Document branding section on the same page.",
        "Set bank BSB, account number, account name, remittance email, document footer text, and GST registered if applicable.",
        "Save. Re-open Document templates → Preview to confirm header and footer.",
      ],
      relatedRoutes: ["/system/organization"],
      windowKeys: ["admin-organization"],
    },
    {
      id: "document-registry",
      title: "Document registry",
      body: "Every print, issue, or generate action can write a copy to the registry. Use it to find what was produced, for whom, and when.",
      steps: [
        "Open System → Tasks → Document registry.",
        "Search by entity type, document class, or batch id.",
        "Open View document to read the stored HTML.",
        "Use this for audit trails — not as a full document management system.",
      ],
      relatedRoutes: ["/system/admin/document-registry"],
    },
    {
      id: "print-from-workspace",
      title: "Where users print or generate documents",
      body: "After templates and bindings are set, workspace users run these actions (when their role includes the process):",
      bullets: [
        "Invoices → Print invoice, Download HTML, Issue invoice; list → Batch print.",
        "Enquiries → Print acknowledgement.",
        "Invoice reconciliation → Print remittance cover.",
        "Clients → Overview → Print statement or Print consent schedule.",
        "Claims → Print claim batch.",
        "Incidents → Print notification.",
        "NDIS audit pack → Print audit pack.",
        "Board reporting → Print / export.",
        "Service agreements → Print agreement.",
        "Employees → Documents → Generate contract, offer letter, or separation letter.",
      ],
      relatedRoutes: [
        "/invoices",
        "/enquiries",
        "/clients",
        "/claims",
        "/incidents",
        "/ndis-audit-pack",
        "/board-reporting",
        "/service-agreements",
        "/employees",
      ],
    },
    {
      id: "faq-common-questions",
      title: "Common questions",
      body: "Quick answers operators ask:",
      bullets: [
        "Why doesn't my edit appear on print? — Did you Save the template? Is it Active? Is the correct template selected in Default templates by process?",
        "Why can't I see Duplicate or Save? — You need admin-document-templates write access in System.",
        "Why can't finance print? — Grant the print process (for example print-invoice) on their role under Admin → Roles.",
        "Can we email invoices? — No. Issue invoice saves to the registry and marks Sent; hand off via print or registry view.",
        "How do we get PDF? — Print opens HTML; choose Save as PDF in the browser print dialog.",
        "Can we edit legal clauses? — Not in the UI yet; duplicate and change title/footer today, or request a block editor slice.",
        "Server PDF / email later? — Deferred until a PDF host is decided; HTML print is the current production path.",
        "Why did localhost stop responding? — Dev server may restart after memory pressure; use http://localhost:3000 and wait for Ready.",
      ],
    },
  ],
};
