import type { HelpArticle } from "@/lib/help/types";
import { MOBILE_APP_NAME } from "@/lib/mobile/constants";

export const employeeMobileArticle: HelpArticle = {
  id: "article-employee-mobile",
  slug: "employee-mobile",
  title: `${MOBILE_APP_NAME} (PWA)`,
  summary:
    `Install ${MOBILE_APP_NAME} on your phone for today's shifts, check-in with GPS, pay-period schedule, timesheets, assigned tasks, credentials, profile updates, and your Digital Worker ID.`,
  category: "People",
  keywords: [
    "mobile",
    "pwa",
    "my workplace",
    "check in",
    "check out",
    "gps",
    "today",
    "schedule",
    "digital id",
    "install",
    "iphone",
    "home screen",
    "tasks",
    "animal alert",
    "credentials",
    "profile",
  ],
  relatedRoutes: [
    "/m/today",
    "/m/schedule",
    "/m/timesheets",
    "/m/tasks",
    "/m/more",
    "/m/id",
    "/m/install",
    "/m/messages",
    "/m/open-shifts",
    "/m/leave",
    "/m/availability",
    "/m/notifications",
    "/m/credentials",
    "/m/profile",
    "/m/login",
  ],
  windowKeys: [
    "my-workplace",
    "my-shifts",
    "my-timesheets",
    "tasks-assigned-to-me",
    "my-open-shifts",
    "my-leave",
    "my-availability",
    "my-credentials",
    "my-profile",
  ],
  lastUpdated: "2026-07-01",
  sections: [
    {
      id: "open",
      title: `Open ${MOBILE_APP_NAME}`,
      body: `Go to **/m/today** on your phone (or tap the link from My workplace). Sign in with your usual AbilityVua username and password — the sign-in form stays in the mobile app. You need My workplace access and an employee link on your user record.`,
      relatedRoutes: ["/m/today", "/m/login"],
    },
    {
      id: "install",
      title: "Install on iPhone",
      body: "Open the app in Safari, then **More → Install on iPhone** for step-by-step **Add to Home Screen** instructions. Android Chrome may offer **Install app** from the browser menu.",
      relatedRoutes: ["/m/install", "/m/more"],
    },
    {
      id: "today",
      title: "Today and check-in",
      body: "The **Today** tab shows your current shift first. Tap **Check in now** (floating button) or the card button. GPS is captured only when you check in or out — not continuously. Animal and pet alerts appear on the shift card when relevant.\n\nUse **Get directions** to open maps for the support location.",
      relatedRoutes: ["/m/today"],
    },
    {
      id: "schedule",
      title: "Pay period schedule",
      body: "The **Schedule** tab lists all shifts in the current pay period. Swipe from Today via **Pay period →** at the top of the Today screen.",
      relatedRoutes: ["/m/schedule"],
    },
    {
      id: "tasks",
      title: "Assigned tasks",
      body: "The **Tasks** tab lists work items assigned directly to you (not compliance reminders). Tap a task to open it, add updates, or mark it complete.",
      relatedRoutes: ["/m/tasks"],
    },
    {
      id: "privacy",
      title: "Location privacy",
      body: "On first open you see a one-time notice: location is used only at check-in and check-out to verify attendance at the support site.",
      relatedRoutes: ["/m/today"],
    },
    {
      id: "offline",
      title: "Offline check-in",
      body: "When you have no signal, check-in and check-out are saved on your phone and sync automatically when you reconnect. Use **Sync now** on the banner if needed. Approximate location may be used when offline (up to 30 minutes old).",
      relatedRoutes: ["/m/today", "/m/schedule"],
    },
    {
      id: "more",
      title: "More — leave, open shifts, and messages",
      body: `Open **More** for self-service pages that stay in ${MOBILE_APP_NAME}:\n\n- **Messages** — contact rostering about a shift\n- **Open shifts** — browse vacant shifts and apply\n- **Leave** — submit and track leave requests\n- **Availability** — set your weekly pattern\n- **Credentials** — submit licences and evidence for HR review\n- **Personal info** — update contact details and emergency contacts\n- **Notifications** — enable push reminders for shifts and credentials`,
      relatedRoutes: [
        "/m/more",
        "/m/messages",
        "/m/open-shifts",
        "/m/leave",
        "/m/availability",
        "/m/credentials",
        "/m/profile",
        "/m/notifications",
      ],
    },
    {
      id: "push",
      title: "Push notifications",
      body: "From **More** or **Notifications**, tap **Enable notifications** and allow the browser prompt. Choose shift reminders and credential expiry alerts.\n\nOn iPhone you must add the app to your home screen first (Safari → Share → Add to Home Screen). Push may not work in a normal Safari tab.",
      relatedRoutes: ["/m/notifications", "/m/install"],
    },
  ],
};
