import type { HelpArticle } from "@/lib/help/types";
import { MOBILE_APP_NAME } from "@/lib/mobile/constants";

export const employeeMobileArticle: HelpArticle = {
  id: "article-employee-mobile",
  slug: "employee-mobile",
  title: `${MOBILE_APP_NAME} (PWA)`,
  summary:
    `Install ${MOBILE_APP_NAME} on your phone for today's shifts, check-in with GPS, pay-period schedule, timesheets, assigned tasks, credentials, profile updates, and your Digital Worker ID.`,
  category: "People",
  keywords: [
    "mobile",
    "pwa",
    "my workplace",
    "check in",
    "check out",
    "gps",
    "today",
    "schedule",
    "digital id",
    "install",
    "iphone",
    "home screen",
    "tasks",
    "animal alert",
    "credentials",
    "profile",
  ],
  relatedRoutes: [
    "/m/today",
    "/m/schedule",
    "/m/timesheets",
    "/m/tasks",
    "/m/more",
    "/m/id",
    "/m/install",
    "/m/messages",
    "/m/open-shifts",
    "/m/services",
    "/m/leave",
    "/m/availability",
    "/m/notifications",
    "/m/credentials",
    "/m/profile",
    "/m/login",
  ],
  windowKeys: [
    "my-workplace",
    "my-shifts",
    "my-timesheets",
    "tasks-assigned-to-me",
    "my-open-shifts",
    "my-leave",
    "my-availability",
    "my-credentials",
    "my-profile",
  ],
  lastUpdated: "2026-07-01",
  sections: [
    {
      id: "open",
      title: `Open ${MOBILE_APP_NAME}`,
      body: `Go to **/m/today** on your phone (or tap the link from My workplace). Sign in with your usual AbilityVua username and password — the sign-in form stays in the mobile app. You need My workplace access and an employee link on your user record.`,
      relatedRoutes: ["/m/today", "/m/login"],
    },
    {
      id: "install",
      title: "Install on iPhone",
      body: "Open the app in Safari, then **More → Install on iPhone** for step-by-step **Add to Home Screen** instructions. Android Chrome may offer **Install app** from the browser menu.",
      relatedRoutes: ["/m/install", "/m/more"],
    },
    {
      id: "today",
      title: "Today and check-in",
      body: "The **Today** tab shows your current shift first. Tap **Check in now** (floating button) or the card button. GPS is captured only when you check in or out — not continuously. Animal and pet alerts appear on the shift card when relevant.\n\nUse **Get directions** to open maps for the support location.",
      relatedRoutes: ["/m/today"],
    },
    {
      id: "schedule",
      title: "Pay period schedule",
      body: "The **Schedule** tab lists all shifts in the current pay period. Swipe from Today via **Pay period →** at the top of the Today screen.\n\nWhen you are offline, the app shows the last saved copy of your schedule with a timestamp. Times and assignments may be out of date — connect to refresh before relying on it.",
      relatedRoutes: ["/m/schedule", "/m/today"],
    },
    {
      id: "tasks",
      title: "Assigned tasks",
      body: "The **Tasks** tab lists work items assigned directly to you (not compliance reminders). Tap a task to open it, add updates, or mark it complete.",
      relatedRoutes: ["/m/tasks"],
    },
    {
      id: "privacy",
      title: "Location privacy",
      body: "On first open you see a one-time notice: location is used only at check-in and check-out to verify attendance at the support site.",
      relatedRoutes: ["/m/today"],
    },
    {
      id: "offline",
      title: "Offline check-in",
      body: "When you have no signal, check-in and check-out are saved on your phone and sync automatically when you reconnect. Use **Sync now** on the banner if needed. Approximate location may be used when offline (up to 30 minutes old).\n\nOpen the app while online at least once so your pay-period schedule is saved for offline browsing.",
      relatedRoutes: ["/m/today", "/m/schedule"],
    },
    {
      id: "more",
      title: "More — leave, open shifts, and messages",
      body: `Open **More** for self-service pages that stay in ${MOBILE_APP_NAME}:\n\n- **Services I can work at** — qualified sites and high-demand advisory\n- **Messages** — contact rostering about a shift\n- **Open shifts** — browse vacant shifts, apply, and track application status\n- **Leave** — submit and track leave requests\n- **Availability** — set your weekly pattern\n- **Credentials** — submit licences and evidence for HR review\n- **Personal info** — update contact details and emergency contacts\n- **Notifications** — enable push reminders for shifts and credentials`,
      relatedRoutes: [
        "/m/more",
        "/m/services",
        "/m/messages",
        "/m/open-shifts",
        "/m/leave",
        "/m/availability",
        "/m/credentials",
        "/m/profile",
        "/m/notifications",
      ],
    },
    {
      id: "services",
      title: "Services I can work at",
      body: "From **More → Services I can work at**, see sites where you have an active assignment, current mandatory credentials, and site orientation. High-demand services are highlighted with a prompt to contact rostering. The list is read-only.",
      relatedRoutes: ["/m/services", "/m/more"],
    },
    {
      id: "open-shift-applications",
      title: "Open shift applications",
      body: "On **Open shifts**, **My applications** lists your recent requests with status (Applied, Approved, Rejected). Rejection reasons appear in the app only — not on the lock screen. Enable **Open shift applications** under Notifications for a push when rostering decides.",
      relatedRoutes: ["/m/open-shifts", "/m/notifications"],
    },
    {
      id: "profile-photo",
      title: "Profile photo",
      body: "From **More → Personal info**, upload or change your profile photo. It appears on your **Digital Worker ID** and on your employee record in the main app.\n\nUse a clear head-and-shoulders photo. JPG, PNG, or WebP up to 5 MB.",
      relatedRoutes: ["/m/profile", "/m/id"],
    },
    {
      id: "passkey",
      title: "Face ID / fingerprint sign-in",
      body: "After your first password sign-in, tap **Enable Face ID** (or Fingerprint on Android). Next time your session expires, use **Sign in with Face ID** on the sign-in screen — no password needed.\n\nOn iPhone, add My Workplace to your home screen first for reliable biometrics. If you have more than one role, sign in with password once and pick your role so Face ID remembers it.",
      relatedRoutes: ["/m/login", "/m/more"],
    },
    {
      id: "push",
      title: "Push notifications",
      body: "From **More** or **Notifications**, tap **Enable notifications** and allow the browser prompt. You can turn on:\n\n- **Critical shifts available** — when rostering marks an open shift as critical at your location\n- **Open shift applications** — when rostering approves or updates your application (details stay in the app)\n- **Rostering replies** — when rostering responds to a message you sent\n- **Shift updates and reminders** — when your assigned shift changes, plus upcoming shift reminders\n- **Credential expiry** — before a licence or check expires\n\nOn iPhone you must add the app to your home screen first (Safari → Share → Add to Home Screen). Push may not work in a normal Safari tab.",
      relatedRoutes: ["/m/notifications", "/m/install"],
    },
  ],
};
