import type { HelpArticle } from "@/lib/help/types";

function moduleSetupArticle(
  slug: string,
  title: string,
  summary: string,
  setupRoute: string,
  refSection: string,
  checklist: string[]
): HelpArticle {
  return {
    id: `article-${slug}`,
    slug,
    title,
    summary,
    category: "System setup",
    keywords: [slug, "system setup", "reference data", "module setup"],
    relatedRoutes: [setupRoute, `/system/reference-data/${refSection}`],
    windowKeys: [],
    lastUpdated: "2026-06-26",
    sections: [
      {
        id: "open",
        title: `Open ${title.toLowerCase()}`,
        steps: [
          "Sign in to System setup.",
          `Open ${setupRoute} from Setup guides on the System home page, or use the direct link.`,
          "Work through the checklist, then open Reference data for dropdown lists.",
        ],
        relatedRoutes: [setupRoute],
      },
      {
        id: "checklist",
        title: "Checklist",
        bullets: checklist,
      },
    ],
  };
}

export const moduleSetupGuideArticles: HelpArticle[] = [
  moduleSetupArticle(
    "enquiries-setup",
    "Enquiries setup",
    "Configure enquiry statuses, sources, and intake options before coordinators use the pipeline.",
    "/system/setup/enquiries",
    "enquiries",
    [
      "Review enquiry pipeline status values (received → qualification → proposal → converted / lost).",
      "Configure enquiry loss reasons, plan status, plan management, and urgency lists.",
      "Grant the Qualification tab under Enquiries for intake roles.",
      "Create a test enquiry and confirm the qualification score updates on save.",
      "Optional: set WEB_TO_LEAD_SECRET and HUBSPOT_DRY_RUN=true — POST a test payload to /api/public/web-to-lead and sync an enquiry from the CRM panel.",
      "For live HubSpot sync: create a private app with crm.objects.contacts.read + crm.objects.contacts.write scopes, set HUBSPOT_ACCESS_TOKEN (unset HUBSPOT_DRY_RUN), and map optional custom properties via HUBSPOT_PROPERTY_* env vars if needed.",
      "Confirm cross-sell alerts appear on the Enquiries list for underserviced active clients (e.g. Bern).",
    ]
  ),
  moduleSetupArticle(
    "clients-setup",
    "Clients setup",
    "Client lifecycle, plan budget reference lists, consents, and role access before coordinators use client records.",
    "/system/setup/clients",
    "clients",
    [
      "Align Client status with your onboarding workflow.",
      "Review Client lifecycle status (intake → exit) and Lifecycle exit reason lists.",
      "Configure NDIS support budget and NDIS support category for Plan budget lines.",
      "Set Plan provider on budget lines when participants use external plan managers — required for Multi-provider budget reporting.",
      "Set Consent status options and consent, alert, risk, and activity types.",
      "Review support plan lists (goals, documents, assessments).",
      "Grant print-support-plan and send-support-plan on coordinator, intake, quality, and team leader roles (seeded on admin).",
      "Complete a test support plan on a demo client; print and send to confirm document registry rows.",
      "Under Admin → Roles, grant Clients module, Plan budget tab (client-plan-budget), Service agreements (client-service-agreements), and Service bookings (client-service-bookings) at Read or Write for each role that needs them.",
      "Create a test client: set lifecycle, add plan budget lines (manual, wizard, CSV import, PDF paste, or gateway pull on Plan budget tab), record core consents, then save and verify Overview summaries.",
      "On Plan budget tab: set Plan provider on a line, save, refresh — confirm Multi-provider budget lists the provider.",
      "Apply Billing claimed rollup on a client with submitted claims or sent invoices; save and confirm claimed amounts persist after refresh.",
      "Set NDIS_GATEWAY_DRY_RUN=true in Amplify to test plan gateway pull without live PRODA credentials.",
      "Participant portal sign-in (demo): https://app.abilityvua.com/portal/login — not linked from the staff sidebar.",
      "Set a participant email on the client record — it must match the address they use at portal login (demo: Bernie@email).",
      "Roster future shifts to the client and confirm they appear on /portal/services after magic-link sign-in.",
      "Test a portal service request with Bernie@email — confirm a coordinator task appears and approve creates a draft agreement variation.",
    ]
  ),
  moduleSetupArticle(
    "locations-setup",
    "Locations setup",
    "Site types, statuses, and location alert options.",
    "/system/setup/locations",
    "locations",
    ["Set location type and status lists.", "Configure location alert types.", "Enter latitude, longitude, and geofence radius (m) on each site for shift check-in alerts.", "Create a test location in the workspace."]
  ),
  moduleSetupArticle(
    "people-setup",
    "People setup",
    "Employee employment, credential, and profile reference lists.",
    "/system/setup/people",
    "people",
    [
      "Set employment status, type, and department lists.",
      "Configure credential types and statuses for compliance.",
      "Link employees to System access after roles are configured.",
    ]
  ),
  moduleSetupArticle(
    "workforce-setup",
    "Workforce planning setup",
    "Leave types and organisation structure pointers.",
    "/system/setup/workforce",
    "workforce",
    [
      "Set leave type and leave request status options.",
      "Configure org chart tiers under Organisation.",
      "Maintain positions under Workforce planning → Organisation structure.",
      "Seed task automations for leave and credential review (see Task automations guide).",
      "Leave calendar and review queue stay in the workspace at Workforce planning.",
      "Grant Training and meetings (`training-meetings`) at Write for HR managers, team leaders, or rostering roles that schedule non-service sessions.",
      "Review training categories, meeting categories, cost centres, and attendance statuses with finance before go-live.",
      "Create a test training session in Workforce planning → Training and meetings, confirm it appears on Rostering, then sign off one attendee and verify the cost summary.",
    ]
  ),
  moduleSetupArticle(
    "incidents-setup",
    "Incidents setup",
    "Statuses, severity, role visibility, parties, and automation hooks.",
    "/system/setup/incidents",
    "incidents",
    [
      "Align incident status and severity with your quality framework.",
      "Set investigation SLA days under System → Incidents → Incident management.",
      "Grant Can see all incidents on coordinator, quality, and manager roles; leave it off for support workers (they see My incidents only).",
      "Grant report-incident process and Incidents module Write for frontline staff who submit incidents.",
      "Set party and NDIS reportable types.",
      "Configure task automations for reportable and SLA workflows.",
    ]
  ),
  moduleSetupArticle(
    "services-setup",
    "Services setup",
    "Products, agreements, contracts, and service booking access before delivery staff create bookings.",
    "/system/setup/services",
    "services",
    [
      "Configure product categories and units of measure.",
      "Set service agreement and contract status options.",
      "Configure NDIS products and price lists before building schedules of supports.",
      "Grant Service agreements and Service bookings windows at Write for delivery roles.",
      "Review Booking cancellation reason and Cancellation initiated by reference lists.",
      "Ensure client Plan budget lines exist for participants — booking compliance compares totals to remaining budget.",
      "Confirm clients have service delivery consent and Active service agreements before bookings go live.",
      "Create a test booking, cancel it with full details, and confirm the cancellation policy panel before go-live.",
      "Grant Rostering, Timesheets, and Generate timesheets windows at Write for coordinators.",
      "Grant My shifts to support workers and coordinators who check in on rostered work.",
      "Publish roster shifts with workers assigned before running Generate timesheets for a pay period.",
      "Import or generate roster of care (RoC) weekly schedules on Rostering → RoC before building shifts.",
      "Review each client's Roster of care tab — weekly hours should align with Forward plan before go-live.",
      "Workers complete My workplace → Availability; coordinators review templates on Workforce planning → Worker schedule templates.",
      "Use Workforce planning → Fill board to review vacant shifts, employee requests, and critical fill before publishing — approve requests or assign suggested workers.",
      "Grant My workplace → Open shifts to support workers who request cover; coordinators use Rostering → Open shifts to review applications.",
      "Publish RoC lines to the roster calendar as Draft shifts, assign workers, then publish before timesheet generation.",
      "Review Rostering → Capacity weekly — unstaffed demand and over-capacity workers should be cleared before go-live.",
      "Keep employee credentials and Skills & languages up to date — matching hints use WWCC, NDIS screening, and specialisations.",
      "Maintain Plan budget on each active client before generating monthly service plans.",
      "Resolve roster conflict badges on the week calendar before using Publish week or setting shifts to Published.",
      "Test Export week CSV on Rostering → Week — confirm client and worker search keys appear for payroll or external tools.",
      "Workers should check out and verify shifts on My workplace before coordinators approve timesheets.",
      "Export approved timesheets to CSV from the Timesheets payroll export panel before running pay in Keypay or Xero.",
      "For Keypay API export, set KEYPAY_API_KEY and KEYPAY_BUSINESS_ID on the server (Amplify env vars). Use KEYPAY_DRY_RUN=true to test without posting.",
      "After each pay run, reconcile exported timesheets — enter paid hours and pay run reference on Timesheets and clear Variance rows before closing payroll.",
      "When payroll paid hours match exported totals, use batch reconcile at exported hours with one pay run reference for multiple timesheets.",
      "Mark pay periods closed on Timesheets after reconciliation — closed periods block new draft timesheet generation for the same dates.",
      "Grant Claims and Generate claims windows at Write for billing coordinators.",
      "Grant Generate claims for cancellation claim batches from cancelled bookings with short-notice participant cancellations.",
      "Generate claims only after timesheets are Approved and shift verification passes.",
      "Review PAPL validation on each claim batch before gateway submit.",
      "Set NDIS_GATEWAY_DRY_RUN=true on Amplify for dry-run gateway testing.",
      "Import NDIA remittance CSV on Claims after payment advice — preview matches before applying.",
      "Grant Invoices and Generate invoices for plan-managed and self-managed billing.",
      "Grant print-invoice, batch-print-invoices, and send-invoice (issue in registry) for finance roles.",
      "Grant print-enquiry-acknowledgement for enquiry coordinators.",
      "Grant print-remittance-cover and print-participant-statement for finance follow-up.",
      "Grant print-board-report for executives preparing board packs.",
      "Grant print-service-agreement and print-agreement-variation for coordinators managing NDIS agreements.",
      "Grant print-employee-contract, print-employee-offer, and print-employee-separation on HR roles that generate employment documents.",
      "Grant print-claim-batch on finance roles that review NDIS claim batches.",
      "Grant print-incident-notification on incident manager and coordinator roles.",
      "Grant print-audit-pack on quality and finance roles that prepare NDIS audit evidence.",
      "Grant print-consent-schedule on client coordinator roles.",
      "System → Organisation → Document branding — set bank BSB, account, remittance email, and footer.",
      "System → Tasks → Document templates — confirm templates are Active; set default template for each print process (see System guide: Document templates).",
      "Invoices list — grant batch-print-invoices process for month-end ZIP export.",
      "Set client Funding body to plan-managed or self-managed before generating invoices.",
      "Grant Plan reconciliation for coordinators reviewing monthly plan vs delivery.",
      "Grant Multi-provider budget when participants receive support from more than one NDIS provider.",
      "Grant Claim reconciliation for finance and billing coordinators reviewing remittance matches.",
      "Grant Invoice reconciliation for finance follow-up on unpaid participant invoices.",
      "Grant Financial close for month-end sign-off across plan, billing, and payroll.",
      "Use Mark month closed on Financial close after the checklist passes — requires `financial_closed_month` migration on Supabase.",
      "Grant My timesheets for workers submitting draft timesheets from My workplace.",
      "Grant NDIS audit pack for quality and compliance audit evidence exports.",
      "Grant Board reporting for executives preparing monthly NDIS board report packs — board members receive read-only access to published reports.",
      "Grant Timesheet approval for team leaders and coordinators — use approve-timesheet process with the timesheet-approval window.",
    ]
  ),
  moduleSetupArticle(
    "reports-setup",
    "Reports setup",
    "Role access to the report catalogue and Reports Advance.",
    "/system/setup/reports",
    "reports",
    [
      "Grant standard report windows per role under Admin → Roles.",
      "Use Reports Advance only for trusted administrators.",
    ]
  ),
];
