import type { HelpArticle } from "@/lib/help/types";

export const myWorkplaceArticle: HelpArticle = {
  id: "article-my-workplace",
  slug: "my-workplace",
  title: "My workplace self-service",
  summary:
    "Submit leave, update your profile, add credentials with evidence, set availability, and acknowledge contracts from your own login.",
  category: "People",
  keywords: [
    "my workplace",
    "self service",
    "leave",
    "availability",
    "about me",
    "contracts",
    "credentials",
    "compliance",
    "profile",
    "kiosk",
    "mobility",
    "staff portal",
  ],
  relatedRoutes: ["/my", "/my/leave", "/my/profile", "/my/availability", "/my/contracts", "/my/credentials"],
  windowKeys: ["my-workplace", "my-leave", "my-profile", "my-availability", "my-contracts", "my-credentials"],
  lastUpdated: "2026-06-18",
  sections: [
    {
      id: "overview",
      title: "What My workplace is",
      body: "My workplace is the staff self-service hub. The overview dashboard shows credentials and documents expiring or overdue, profile gaps, and items awaiting HR review. Coordinators and HR still use Employees and Workforce planning for organisation-wide views.",
      relatedRoutes: ["/my"],
    },
    {
      id: "access",
      title: "Who can use it",
      body: "You need the My workplace windows on your role and a user account linked to your employee record (Employee → System access). Support workers, team leaders, and most staff with logins have access by default.",
      windowKeys: ["my-workplace"],
    },
    {
      id: "leave",
      title: "Submit and track leave",
      steps: [
        "Open My workplace → Leave.",
        "Choose leave type, dates, and optional notes.",
        "Submit — status shows as Requested until a manager approves or declines in the HR employee record.",
      ],
      relatedRoutes: ["/my/leave"],
      windowKeys: ["my-leave"],
    },
    {
      id: "profile",
      title: "Update About me",
      body: "Edit contact details, emergency contacts, and home address. The page highlights missing core information so you can complete your profile. Payroll, bank, and tax fields stay on the HR record.",
      relatedRoutes: ["/my/profile"],
      windowKeys: ["my-profile"],
    },
    {
      id: "credentials",
      title: "Credentials and evidence",
      steps: [
        "Open My workplace → Credentials.",
        "Add a credential with type, dates, and an evidence reference.",
        "Submit — status shows as Pending review until HR verifies and signs off as Current.",
        "Expired or expiring credentials appear on your dashboard so you can renew in time.",
      ],
      relatedRoutes: ["/my/credentials"],
      windowKeys: ["my-credentials"],
    },
    {
      id: "availability",
      title: "Working availability",
      body: "Set your preferred weekly pattern so rostering can see when you are available, preferred, or unavailable.",
      relatedRoutes: ["/my/availability"],
      windowKeys: ["my-availability"],
    },
    {
      id: "contracts",
      title: "Contracts and policies",
      body: "View employment contracts and policy documents. Items marked as requiring acknowledgement must be confirmed before they are complete.",
      relatedRoutes: ["/my/contracts"],
      windowKeys: ["my-contracts"],
    },
    {
      id: "future",
      title: "Coming later",
      body: "Roster, timesheets, and pay slips will be added to My workplace and the mobility app using the same self-service foundation.",
    },
  ],
};
