import type { HelpArticle } from "@/lib/help/types";

export const myWorkplaceArticle: HelpArticle = {
  id: "article-my-workplace",
  slug: "my-workplace",
  title: "My workplace self-service",
  summary:
    "Submit leave, update your profile, upload credentials, set availability, and view or acknowledge employment contracts — with tasks (not email) when HR or your manager needs to act.",
  category: "People",
  keywords: [
    "my workplace",
    "self service",
    "leave",
    "availability",
    "about me",
    "contracts",
    "credentials",
    "compliance",
    "profile",
    "kiosk",
    "mobility",
    "staff portal",
    "task",
    "how to",
  ],
  relatedRoutes: ["/my", "/my/leave", "/my/profile", "/my/availability", "/my/open-shifts", "/my/shifts", "/my/contracts", "/my/credentials"],
  windowKeys: ["my-workplace", "my-leave", "my-profile", "my-availability", "my-open-shifts", "my-shifts", "my-contracts", "my-credentials"],
  lastUpdated: "2026-06-20",
  sections: [
    {
      id: "overview",
      title: "What My workplace is",
      body: "My workplace is the staff self-service hub. The overview dashboard shows credentials and documents expiring or overdue, profile gaps, contracts needing acknowledgement, and items awaiting HR review.\n\nAbilityAPP does not send workforce notifications by email. When you submit leave or a credential, the system creates a task for your manager or HR. You can track status on My workplace and in your Tasks list.",
      relatedRoutes: ["/my"],
    },
    {
      id: "access",
      title: "Who can use it",
      body: "You need the My workplace windows on your role and a user account linked to your employee record (Employee → System access). Support workers, coordinators, and most staff with logins have access by default.",
      windowKeys: ["my-workplace"],
    },
    {
      id: "leave",
      title: "Submit and track leave",
      steps: [
        "Open My workplace → Leave.",
        "Choose leave type, start and end dates, and optional notes.",
        "The system checks your leave balance before submit.",
        "Submit — status shows as Requested until a manager or HR approves or declines.",
        "A task is assigned to your reports-to manager (or HR manager as fallback).",
        "When approved, your leave balance is reduced by the days requested.",
      ],
      relatedRoutes: ["/my/leave"],
      windowKeys: ["my-leave"],
    },
    {
      id: "leave-calendar",
      title: "Your leave calendar",
      body: "My workplace → Leave includes a personal calendar of your requests. Approved and pending leave appear by date so you can plan around time off.",
      relatedRoutes: ["/my/leave"],
    },
    {
      id: "profile",
      title: "Update About me",
      body: "Edit contact details, emergency contacts, and home address. The page highlights missing core information so you can complete your profile. Payroll, bank, and tax fields stay on the HR record.",
      relatedRoutes: ["/my/profile"],
      windowKeys: ["my-profile"],
    },
    {
      id: "credentials",
      title: "Credentials and evidence",
      steps: [
        "Open My workplace → Credentials.",
        "Add a credential with type, dates, number, and evidence (link or uploaded file reference).",
        "Submit — status shows as Pending review until HR verifies and signs off as Current.",
        "A Review task is assigned to the HR officer role.",
        "Expired or expiring credentials appear on your dashboard so you can renew in time.",
      ],
      relatedRoutes: ["/my/credentials"],
      windowKeys: ["my-credentials"],
    },
    {
      id: "availability",
      title: "Working availability",
      body: "Set your preferred weekly pattern so rostering can see when you are available, preferred, or unavailable.",
      relatedRoutes: ["/my/availability"],
      windowKeys: ["my-availability"],
    },
    {
      id: "open-shifts",
      title: "Claim open shifts",
      body: "When rostering posts vacant shifts to the marketplace, you can browse and claim cover from My workplace → Open shifts. The system checks for double-booking before accepting your claim.",
      steps: [
        "Open My workplace → Open shifts.",
        "Review date, time, client, and location on each card.",
        "Click Claim shift — your user must be linked to your employee record.",
        "If you are already rostered at that time, the claim is blocked with a message.",
      ],
      relatedRoutes: ["/my/open-shifts", "/rostering"],
      windowKeys: ["my-open-shifts"],
    },
    {
      id: "my-shifts",
      title: "Check in to your shifts",
      body: "Workers check in and out of assigned roster shifts from My workplace. GPS location is captured when the browser allows it. If the site has geofence coordinates configured, check-in/out more than the allowed radius shows an amber alert for workers and coordinators. Verified shifts show on the roster week view and feed timesheet generation.",
      steps: [
        "Open My workplace → My shifts.",
        "Find today's or upcoming assigned shift — check-in opens on the shift date.",
        "Tap Check in when you start the shift — your browser may ask to share location.",
        "If you are outside the site geofence, an amber warning appears — coordinators see the same on the roster.",
        "Add optional notes, then tap Check out & verify when you finish — the shift moves to Completed.",
        "Coordinators see Checked in or Verified badges, GPS links, and Geofence badges on the roster week calendar.",
      ],
      relatedRoutes: ["/my/shifts", "/rostering"],
      windowKeys: ["my-shifts"],
    },
    {
      id: "contracts",
      title: "Contracts and policies",
      body: "Only documents marked staff-visible by HR appear here. Employment contracts can use a viewable PDF URL stored on the employee record.",
      steps: [
        "Open My workplace → Contracts & policies.",
        "Click View document — PDF links open in the viewer; other refs show as reference-only.",
        "When an item requires acknowledgement, click I have read and agree.",
      ],
      relatedRoutes: ["/my/contracts"],
      windowKeys: ["my-contracts"],
    },
    {
      id: "tasks-not-email",
      title: "Tasks, not email",
      body: "Workforce comms use task automations (Review and Approve task types), not email. Managers and HR also use the Workforce planning review queue as a convenience UI. Completing a review in that queue closes the matching automation task.",
      bullets: [
        "Leave submitted → Approve task for reports-to manager",
        "Credential submitted → Review task for HR officer role",
        "Open Tasks → Assigned to me or My role to action your work",
      ],
      relatedRoutes: ["/tasks", "/workforce-planning#reviews", "/help/workforce-leave-calendar"],
    },
    {
      id: "future",
      title: "Coming later",
      body: "Offline mobile and pay slips will extend the same My workplace self-service foundation.",
    },
  ],
};
