import type { HelpArticle } from "@/lib/help/types";

export const myWorkplaceArticle: HelpArticle = {
  id: "article-my-workplace",
  slug: "my-workplace",
  title: "My workplace self-service",
  summary:
    "Submit leave, request open shifts, track shift applications, set availability, upload credentials, and manage your profile — with tasks (not email) when HR or rostering needs to act.",
  category: "People",
  keywords: [
    "my workplace",
    "self service",
    "leave",
    "availability",
    "about me",
    "contracts",
    "credentials",
    "compliance",
    "profile",
    "open shifts",
    "shift request",
    "request shift",
    "critical fill",
    "available if critical",
    "decline shift",
    "withdraw request",
    "my shifts",
    "kiosk",
    "mobility",
    "staff portal",
    "task",
    "how to",
    "services i can work at",
    "high demand",
    "qualified sites",
  ],
  relatedRoutes: ["/my", "/my/leave", "/my/profile", "/my/availability", "/my/open-shifts", "/my/shifts", "/my/timesheets", "/my/contracts", "/my/credentials"],
  windowKeys: ["my-workplace", "my-leave", "my-profile", "my-availability", "my-open-shifts", "my-shifts", "my-timesheets", "my-contracts", "my-credentials"],
  lastUpdated: "2026-06-29",
  sections: [
    {
      id: "overview",
      title: "What My workplace is",
      body: "My workplace is the staff self-service hub. The overview dashboard shows credentials and documents expiring or overdue, profile gaps, contracts needing acknowledgement, and items awaiting HR review.\n\nAt the top of the overview, **Services I can work at** lists sites where you are assigned, credentialed, and site-oriented. High-demand services are highlighted with a friendly prompt to contact rostering — use **Contact Rostering** below to start a conversation.\n\nAbilityVua does not send workforce notifications by email. When you submit leave or a credential, the system creates a task for your manager or HR. You can track status on My workplace and in your Tasks list.",
      relatedRoutes: ["/my"],
    },
    {
      id: "access",
      title: "Who can use it",
      body: "You need the My workplace windows on your role and a user account linked to your employee record (Employee → System access). Support workers, coordinators, and most staff with logins have access by default.",
      windowKeys: ["my-workplace"],
    },
    {
      id: "leave",
      title: "Submit and track leave",
      steps: [
        "Open My workplace → Leave.",
        "Choose leave type, start and end dates, and optional notes.",
        "The system checks your leave balance and minimum notice before submit.",
        "Submit at least the configured hours before your first affected roster shift (see the notice on the form). Inside that window you must phone HR or your manager — online submit is blocked.",
        "Submit — status shows as Requested until a manager or HR approves or declines.",
        "A task is assigned to your reports-to manager (or HR manager as fallback).",
        "When approved, your leave balance is reduced by the days requested.",
      ],
      relatedRoutes: ["/my/leave"],
      windowKeys: ["my-leave"],
    },
    {
      id: "leave-calendar",
      title: "Your leave calendar",
      body: "My workplace → Leave includes a personal calendar of your requests. Approved and pending leave appear by date so you can plan around time off.",
      relatedRoutes: ["/my/leave"],
    },
    {
      id: "profile",
      title: "Update About me",
      body: "Edit contact details, emergency contacts, and home address. The page highlights missing core information so you can complete your profile. Payroll, bank, and tax fields stay on the HR record.",
      relatedRoutes: ["/my/profile"],
      windowKeys: ["my-profile"],
    },
    {
      id: "credentials",
      title: "Credentials and evidence",
      steps: [
        "Open My workplace → Credentials.",
        "Add a credential with type, dates, number, and evidence (link or uploaded file reference).",
        "Submit — status shows as Pending review until HR verifies and signs off as Current.",
        "A Review task is assigned to the HR officer role.",
        "Expired or expiring credentials appear on your dashboard so you can renew in time.",
      ],
      relatedRoutes: ["/my/credentials"],
      windowKeys: ["my-credentials"],
    },
    {
      id: "availability",
      title: "Working availability",
      body: "Set your preferred weekly pattern so rostering can see when you are available, preferred, or unavailable. The default pattern is Monday to Friday. Save availability stays disabled until your weekly pattern has finished loading, so an empty form can never overwrite and clear your saved days.\n\nYour weekly total must meet or exceed your contracted minimum hours (from your employment contract on your employee record). It must also stay within the organisation maximum unless a manager approves extra hours.\n\nIf a day spans overnight (end time before start time), the organisation setting controls whether those hours count: always included, always excluded, or you are asked each time you save.",
      relatedRoutes: ["/my/availability"],
      windowKeys: ["my-availability"],
    },
    {
      id: "open-shifts",
      title: "Request open shifts",
      body: "When rostering posts vacant shifts to the marketplace, you browse cover from My workplace → Open shifts and submit a request. Rostering reviews all applicants and assigns one worker — requesting a shift does not assign you automatically.\n\nBy default you see shifts at your assigned support locations. Use Show all available shifts to browse other sites (read-only — call rostering if you want to work there). Shifts matching your saved weekly availability show Within your availability; others show Outside your availability and ask you to confirm before submitting.\n\nCritical fill shifts appear at the top with a red Critical fill label. On those shifts you can Request shift, mark Available if critical (standby if rostering cannot find cover), or Decline.",
      steps: [
        "Set your weekly pattern on My workplace → Availability so shifts can be matched to your hours.",
        "Open My workplace → Open shifts. Cards at your assigned locations show Request shift and Decline.",
        "Optional: Show all available shifts — other locations appear read-only; you cannot request from those cards.",
        "If a shift is outside your saved availability, confirm Request anyway? before submitting.",
        "On critical fill shifts, choose Request shift, Available if critical, or Decline.",
        "After submit, the card shows Applied — awaiting rostering and Withdraw request until rostering decides.",
        "When rostering approves your request, the shift moves to My shifts → Scheduled shifts.",
      ],
      relatedRoutes: ["/my/open-shifts", "/my/availability", "/my/shifts"],
      windowKeys: ["my-open-shifts", "my-availability"],
    },
    {
      id: "open-shifts-actions",
      title: "Open shift actions explained",
      body: "Each vacant shift card offers different actions depending on whether it is a normal open shift or marked critical fill by rostering.",
      bullets: [
        "Request shift — registers your interest. Status becomes Applied — awaiting rostering. Rostering may approve and assign you, or reject with a reason.",
        "Available if critical — only on critical fill shifts. Registers standby availability without a full request. Rostering sees this in the review panel but must use Assign worker or approve a full Request shift to roster you.",
        "Decline — records that you do not want the shift. Declined responses stay on the audit trail for rostering context.",
        "Withdraw request — removes your pending request before rostering decides. Available on the shift card and on My shifts → Shift requests.",
        "You cannot request if your login is not linked to an employee record, the shift is no longer vacant, or the request would double-book you against another published shift.",
      ],
      relatedRoutes: ["/my/open-shifts", "/my/shifts"],
      windowKeys: ["my-open-shifts", "my-shifts"],
    },
    {
      id: "shift-requests",
      title: "Track shift requests",
      body: "Every open shift you request, withdraw, mark available-if-critical, or decline appears under My workplace → My shifts → Shift requests. The tab badge shows how many applications you have on file.\n\nStatuses include Applied — awaiting rostering (pending), Approved (rostering assigned you), Rejected (not selected — reason shown when provided), and Withdrawn (you cancelled before a decision). Approved shifts also appear under Scheduled shifts for check-in.",
      steps: [
        "Open My workplace → My shifts → Shift requests.",
        "Review date, time, location, client, response type, and critical fill badge on each row.",
        "Pending requests show Withdraw request until rostering approves, rejects, or fills the shift another way.",
        "After approval, open Scheduled shifts to check in on the shift date.",
      ],
      relatedRoutes: ["/my/shifts", "/my/open-shifts"],
      windowKeys: ["my-shifts", "my-open-shifts"],
    },
    {
      id: "contact-rostering",
      title: "Contact Rostering",
      body: "Use Contact Rostering when you need to ask about a shift, availability, leave, open shifts, or another roster question. The message becomes a Rostering Communication task assigned to the Rostering Officer role, so the conversation keeps the same governance, audit trail, and task workflow as other work items.\n\nThe Contact Rostering panel appears on My workplace overview, Open shifts, and My shifts. You can message about anything; related shift is optional. If you choose a related shift, the task links back to that roster shift for context.",
      steps: [
        "Open My workplace → Open shifts or My workplace → My shifts.",
        "Click Contact Rostering at the top of the page.",
        "Enter Subject and Message.",
        "Choose Category: Shift Change, Availability, Leave, Open Shift, or General Enquiry.",
        "Set Priority to Normal or Urgent.",
        "Optional: choose a Related shift from your visible shifts.",
        "Submit — the modal closes and a confirmation with the task reference appears.",
        "Find the new row under Rostering communication history and open it to continue the conversation.",
      ],
      bullets: [
        "Urgent priority displays as an urgent task badge; it does not change leave or roster approval rules.",
        "Attachments are planned for a later enhancement.",
        "Rostering replies on the same task. Continue the conversation by opening the communication from history or from Tasks.",
      ],
      relatedRoutes: ["/my", "/my/open-shifts", "/my/shifts", "/tasks"],
      windowKeys: ["my-open-shifts", "my-shifts", "tasks-assigned-to-me", "tasks-for-my-role"],
    },
    {
      id: "open-shifts-faq",
      title: "Open shifts — common questions",
      body: "Answers to frequent worker questions about the request workflow.",
      bullets: [
        "Why was I not assigned when I requested? — Rostering chooses one applicant per shift. Other pending requests are rejected when someone else is approved, or rostering assigns directly without using requests.",
        "Can I request shifts at another location? — You can browse them with Show all available shifts but cannot submit from read-only cards. Use Contact Rostering to express interest.",
        "What is critical fill? — Rostering marks urgent vacant shifts. They sort to the top and show extra response options (Available if critical, Decline).",
        "What if I change my mind? — Withdraw request while status is still Applied — awaiting rostering.",
        "Will I get an email? — Not in the current release. Track status on Open shifts, My shifts → Shift requests, and your Tasks list when automations are added.",
        "Does requesting publish the shift? — No. Rostering publishes shifts on the week calendar. Your request only registers interest.",
      ],
      relatedRoutes: ["/my/open-shifts", "/my/shifts", "/my/availability"],
      windowKeys: ["my-open-shifts", "my-shifts"],
    },
    {
      id: "my-shifts",
      title: "Check in to your shifts",
      body: "Workers check in and out of assigned roster shifts from My workplace. Use Scheduled shifts for your roster and Shift requests to track open-shift applications. GPS location is captured when the browser allows it. If the site has geofence coordinates configured, check-in/out more than the allowed radius shows an amber alert for workers and coordinators. Verified shifts show on the roster week view and feed timesheet generation.",
      steps: [
        "Open My workplace → My shifts.",
        "Scheduled shifts: use Today, Upcoming, or All for assigned work.",
        "Shift requests: track pending, approved, rejected, and withdrawn applications.",
        "Switch to Week calendar for a seven-day grid of your assigned shifts.",
        "Draft shifts appear with a Draft badge; check-in opens after your coordinator publishes the shift.",
        "The Next action banner highlights today's shift when you can check in or out.",
        "Find your shift under the day heading — check-in opens on the shift date.",
        "Tap Check in when you start the shift — your browser may ask to share location.",
        "If you are outside the site geofence, an amber warning appears — coordinators see the same on the roster.",
        "Add optional notes, then tap Check out & verify when you finish — the shift moves to Completed.",
        "Coordinators see Checked in or Verified badges, GPS links, and Geofence badges on the roster week calendar.",
      ],
      relatedRoutes: ["/my/shifts", "/rostering"],
      windowKeys: ["my-shifts"],
    },
    {
      id: "my-timesheets",
      title: "My timesheets",
      body: "Workers review draft timesheets generated from verified shifts and submit them for supervisor approval. Submit is blocked when shift verification is incomplete.",
      steps: [
        "Open My workplace → My timesheets.",
        "Open a Draft timesheet for the current pay period.",
        "Review shift lines and verification status.",
        "Click Submit — status moves to Submitted and supervisors can approve on Timesheets.",
        "If submit is blocked, complete check-out and verification on My shifts first.",
      ],
      relatedRoutes: ["/my/timesheets", "/timesheets"],
      windowKeys: ["my-timesheets", "timesheets"],
    },
    {
      id: "contracts",
      title: "Contracts and policies",
      body: "Only documents marked staff-visible by HR appear here. Employment contracts can use a viewable PDF URL stored on the employee record.",
      steps: [
        "Open My workplace → Contracts & policies.",
        "Click View document — PDF links open in the viewer; other refs show as reference-only.",
        "When an item requires acknowledgement, click I have read and agree.",
      ],
      relatedRoutes: ["/my/contracts"],
      windowKeys: ["my-contracts"],
    },
    {
      id: "tasks-not-email",
      title: "Tasks, not email",
      body: "Workforce comms use task automations (Review and Approve task types), not email. Managers and HR also use the Workforce planning review queue as a convenience UI. Completing a review in that queue closes the matching automation task.",
      bullets: [
        "Leave submitted → Approve task for reports-to manager",
        "Credential submitted → Review task for HR officer role",
        "Open Tasks → Assigned to me or My role to action your work",
      ],
      relatedRoutes: ["/tasks", "/workforce-planning#reviews", "/help/workforce-leave-calendar"],
    },
    {
      id: "services-advisory",
      title: "Services I can work at",
      body: "The overview shows sites where you have an active location assignment, current mandatory credentials (Working with Children Check and NDIS Worker Screening), and a valid site orientation.\n\nSites with high demand — two or more open shifts in the next two weeks, or a rostering manager flag on the location — show an amber highlight and a short advisory to contact rostering. The list is read-only; you cannot assign yourself to new services from My workplace.",
      steps: [
        "Open My workplace → Overview.",
        "Review **Services I can work at** at the top of the page.",
        "For high-demand sites, use **Contact Rostering** below to ask about extra shifts.",
      ],
      relatedRoutes: ["/my"],
      windowKeys: ["my-workplace"],
    },
    {
      id: "future",
      title: "Coming later",
      body: "Offline mobile and pay slips will extend the same My workplace self-service foundation.",
    },
  ],
};
