import type { HelpArticle } from "@/lib/help/types";

export const employeesArticle: HelpArticle = {
  id: "article-employees",
  slug: "employees",
  title: "Employees",
  summary: "HR records, credentials, leave, documents, compliance, and workforce review for staff.",
  category: "People",
  keywords: [
    "employee",
    "business partner",
    "credential",
    "document",
    "compliance",
    "work rights",
    "payroll",
    "leave approval",
    "credential review",
    "how to",
  ],
  relatedRoutes: ["/employees", "/employees/new", "/workforce-planning#reviews"],
  windowKeys: ["employees"],
  lastUpdated: "2026-06-19",
  sections: [
    {
      id: "employee-list",
      title: "Employees list",
      body: "The Employees list shows every staff member. Open a row to view or edit their file.",
      relatedRoutes: ["/employees"],
    },
    {
      id: "create-employee",
      title: "Create an employee",
      steps: [
        "Open People → Employees.",
        "Click New employee.",
        "Complete Overview, Contact, and Employment tabs.",
        "Save the record.",
        "Add credentials and documents on the Compliance and HR file tabs.",
      ],
      relatedRoutes: ["/employees/new"],
    },
    {
      id: "tab-groups",
      title: "Employee tab groups",
      bullets: [
        "Employee: Overview, Contact, Address, Emergency contacts, Employment, Work rights, Payroll, Leave",
        "Compliance: Credentials Assigned, Alerts",
        "HR file: Documents, Activity, Skills and languages",
        "Organisation: System access",
      ],
    },
    {
      id: "leave",
      title: "Leave tab (HR view)",
      body: "Shows leave entitlements, balances, and requests. Staff submit from My workplace; managers and HR approve in Workforce planning → Review queue or on this tab. Approved leave reduces the matching entitlement balance.",
      windowKeys: ["employee-leave"],
      relatedRoutes: ["/workforce-planning#reviews", "/help/workforce-leave-calendar"],
    },
    {
      id: "credentials",
      title: "Credentials Assigned",
      body: "Track certifications, checks, and licences with issue and expiry dates. Staff can submit from My workplace with status Pending review until HR sets Current or Rejected. Expiry dates appear on Home calendar when the record is linked to your user account.",
      windowKeys: ["employee-credentials-assigned"],
    },
    {
      id: "documents",
      title: "Documents",
      body: "Store HR documents with type, reference or PDF URL, and expiry. Set Staff visible and Requires acknowledgement for items that should appear in My workplace → Contracts. Document expiry feeds the Home personal calendar for your own employee record.",
      windowKeys: ["employee-documents"],
    },
    {
      id: "review-access",
      title: "Who approves leave and credentials",
      bullets: [
        "Credential review: CEO, HR executive, HR manager, HR officer",
        "Leave approval: HR roles above, plus rostering manager and team leader for direct reports",
        "Workforce planning review queue is the fastest path; tasks are also created for assignees",
      ],
      relatedRoutes: ["/workforce-planning#reviews"],
    },
    {
      id: "system-access",
      title: "System access",
      body: "Link the employee to an AbilityAPP user account. Administrators manage access under System → Admin → Roles and Employee → System access.",
      relatedRoutes: ["/system/admin/roles"],
      windowKeys: ["employee-system-access", "admin-roles"],
    },
  ],
};
