import type { HelpArticle } from "@/lib/help/types";

/** Task-focused guides: one common question per article for search and the future chatbot. */
export const quickTaskArticles: HelpArticle[] = [
  {
    id: "article-create-client",
    slug: "create-a-new-client",
    title: "How do I create a new client?",
    summary: "Clients are created by converting an approved enquiry, not from a blank New client button.",
    category: "Quick tasks",
    keywords: [
      "create client",
      "new client",
      "add client",
      "convert enquiry",
      "support receiver",
      "how do i",
    ],
    relatedRoutes: ["/enquiries", "/clients"],
    windowKeys: ["enquiries", "clients"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "before-you-start",
        title: "Before you start",
        body: "You need access to Enquiries and Clients, plus the enquiry-to-client process on your role. Most new clients start as enquiries during intake.",
      },
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Enquiries and find the intake record, or create a new enquiry first.",
          "Complete Participant, Support needs, and Activity so the record is ready for conversion.",
          "Open the enquiry and use Convert to client from the record actions.",
          "Review the new client on Overview and Full profile.",
          "Add Alerts, Locations, consents, or service agreements as needed.",
          "Save your changes.",
        ],
      },
      {
        id: "after-creation",
        title: "After the client exists",
        body: "The client keeps a link to the source enquiry. Continue setup on client tabs your role can access. For line tables such as Consents and Restrictive Practices, use Add row, edit, then Save on the record.",
        relatedRoutes: ["/clients"],
      },
      {
        id: "no-convert-button",
        title: "If you cannot see Convert to client",
        body: "Your role may not include the enquiry-to-client process, or the enquiry may not be in a status that allows conversion. Ask an administrator to check your role under Admin → Roles.",
        relatedRoutes: ["/admin/roles"],
        windowKeys: ["admin-roles"],
      },
    ],
  },
  {
    id: "article-create-employee",
    slug: "create-a-new-employee",
    title: "How do I create a new employee?",
    summary: "Add a staff record from the Employees list, then complete HR and compliance tabs.",
    category: "Quick tasks",
    keywords: ["create employee", "new employee", "add staff", "hire", "how do i"],
    relatedRoutes: ["/employees", "/employees/new"],
    windowKeys: ["employees"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open People → Employees in the sidebar.",
          "Click New employee.",
          "Fill in Overview: name, search key, employment status, and role title.",
          "Complete Contact, Address, and Employment tabs.",
          "Click Save on the unsaved changes bar.",
          "Open Credentials Assigned and Documents to add compliance lines.",
          "Use System access if this person needs an AbilityAPP login.",
        ],
        relatedRoutes: ["/employees/new"],
      },
      {
        id: "tips",
        title: "Tips",
        bullets: [
          "Search key should be short and unique; it appears in lists and links.",
          "Credential and document expiry dates show on Home calendar when the record is linked to the user's login.",
          "Administrators assign roles after System access is set up.",
        ],
      },
    ],
  },
  {
    id: "article-create-enquiry",
    slug: "create-a-new-enquiry",
    title: "How do I create a new enquiry?",
    summary: "Start intake with a new enquiry record from the Enquiries list.",
    category: "Quick tasks",
    keywords: ["create enquiry", "new enquiry", "intake", "referral", "how do i"],
    relatedRoutes: ["/enquiries", "/enquiries/new"],
    windowKeys: ["enquiries"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Enquiries from the sidebar.",
          "Click New enquiry.",
          "On Enquiry details, set source, status, and coordinator.",
          "On Participant, enter name, contact details, and demographics.",
          "On Support needs, describe disability, services sought, and notes.",
          "Save the record.",
          "Log calls and emails on the Activity tab as intake progresses.",
        ],
        relatedRoutes: ["/enquiries/new"],
      },
      {
        id: "next",
        title: "What happens next",
        body: "When intake is approved, convert the enquiry to a client. See How do I create a new client? for that workflow.",
        bullets: ["[How do I create a new client?](/help/create-a-new-client)"],
      },
    ],
  },
  {
    id: "article-create-location",
    slug: "create-a-new-location",
    title: "How do I create a new location?",
    summary: "Register a support site such as a SIL house or day program, then link clients and staff.",
    category: "Quick tasks",
    keywords: ["create location", "new location", "SIL", "site", "how do i"],
    relatedRoutes: ["/locations", "/locations/new"],
    windowKeys: ["locations"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Locations from the sidebar.",
          "Click New location.",
          "On Overview, set name, type, and capacity.",
          "On Contact and address, enter the site address and phone details.",
          "Save the record.",
          "Use the Clients, Employees, and Products and services tabs to add assignments.",
        ],
        relatedRoutes: ["/locations/new"],
      },
    ],
  },
  {
    id: "article-create-task",
    slug: "create-a-new-task",
    title: "How do I create a new task?",
    summary: "Create and assign work from the Tasks hub or from a linked record.",
    category: "Quick tasks",
    keywords: ["create task", "new task", "assign task", "request", "how do i"],
    relatedRoutes: ["/tasks", "/tasks/new"],
    windowKeys: ["tasks-assigned-to-me", "tasks-for-my-role", "tasks-all"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Tasks from the sidebar.",
          "Click New task.",
          "Enter a clear title and pick a task type.",
          "Set priority and due date if needed.",
          "Assign to a user, a role, or both.",
          "Link to an enquiry, client, employee, or location when the task relates to a record.",
          "Save the task.",
        ],
        relatedRoutes: ["/tasks/new"],
      },
      {
        id: "permissions",
        title: "If New task is missing",
        body: "Your role needs assign-task and create permission for that task type. An administrator can adjust this under Admin → Roles and Admin → Task management.",
        relatedRoutes: ["/admin/roles", "/admin/task-management"],
      },
    ],
  },
  {
    id: "article-convert-enquiry",
    slug: "convert-enquiry-to-client",
    title: "How do I convert an enquiry to a client?",
    summary: "Turn an approved intake enquiry into an active client record.",
    category: "Quick tasks",
    keywords: ["convert", "enquiry to client", "enrol", "activate client", "how do i"],
    relatedRoutes: ["/enquiries", "/clients"],
    windowKeys: ["enquiries", "clients"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open the enquiry from Enquiries or from an open workspace tab.",
          "Confirm Participant and Support needs are complete.",
          "Click Convert to client in the record actions.",
          "Open the new client from the prompt or from Clients → All clients.",
          "Review Overview and update Full profile fields.",
          "Save any further changes.",
        ],
      },
      {
        id: "requirements",
        title: "Requirements",
        body: "You need the enquiry-to-client process on your role. The enquiry should be in a status that allows conversion. If the action is missing, contact an administrator.",
      },
    ],
  },
];
