import type { HelpArticle } from "@/lib/help/types";

/** Task-focused guides: one common question per article for search and the future chatbot. */
export const quickTaskArticles: HelpArticle[] = [
  {
    id: "article-create-client",
    slug: "create-a-new-client",
    title: "How do I create a new client?",
    summary: "Clients are created by converting an approved enquiry, not from a blank New client button.",
    category: "Quick tasks",
    keywords: [
      "create client",
      "new client",
      "add client",
      "convert enquiry",
      "support receiver",
      "how do i",
    ],
    relatedRoutes: ["/enquiries", "/clients"],
    windowKeys: ["enquiries", "clients"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "before-you-start",
        title: "Before you start",
        body: "You need access to Enquiries and Clients, plus the enquiry-to-client process on your role. Most new clients start as enquiries during intake.",
      },
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Enquiries and find the intake record, or create a new enquiry first.",
          "Complete Participant, Support needs, and Activity so the record is ready for conversion.",
          "Open the enquiry and use Convert to client from the record actions.",
          "Review the new client on Overview and Full profile.",
          "Add Alerts, Locations, consents, or service agreements as needed.",
          "Save your changes.",
        ],
      },
      {
        id: "after-creation",
        title: "After the client exists",
        body: "The client keeps a link to the source enquiry. Continue setup on client tabs your role can access. For line tables such as Consents and Restrictive Practices, use Add row, edit, then Save on the record.",
        relatedRoutes: ["/clients"],
      },
      {
        id: "no-convert-button",
        title: "If you cannot see Convert to client",
        body: "Your role may not include the enquiry-to-client process, or the enquiry may not be in a status that allows conversion. Ask an administrator to check your role under System → Admin → Roles.",
        relatedRoutes: ["/system/admin/roles"],
        windowKeys: ["admin-roles"],
      },
    ],
  },
  {
    id: "article-create-employee",
    slug: "create-a-new-employee",
    title: "How do I create a new employee?",
    summary: "Add a staff record from the Employees list, then complete HR and compliance tabs.",
    category: "Quick tasks",
    keywords: ["create employee", "new employee", "add staff", "hire", "how do i"],
    relatedRoutes: ["/employees", "/employees/new"],
    windowKeys: ["employees"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open People → Employees in the sidebar.",
          "Click New employee.",
          "Fill in Overview: name, search key, employment status, and role title.",
          "Complete Contact, Address, and Employment tabs.",
          "Click Save on the unsaved changes bar.",
          "Open Credentials Assigned and Documents to add compliance lines.",
          "Use System access if this person needs an AbilityAPP login.",
        ],
        relatedRoutes: ["/employees/new"],
      },
      {
        id: "tips",
        title: "Tips",
        bullets: [
          "Search key should be short and unique; it appears in lists and links.",
          "Credential and document expiry dates show on Home calendar when the record is linked to the user's login.",
          "Administrators assign roles after System access is set up.",
        ],
      },
    ],
  },
  {
    id: "article-create-enquiry",
    slug: "create-a-new-enquiry",
    title: "How do I create a new enquiry?",
    summary: "Start intake with a new enquiry record from the Enquiries list.",
    category: "Quick tasks",
    keywords: ["create enquiry", "new enquiry", "intake", "referral", "how do i"],
    relatedRoutes: ["/enquiries", "/enquiries/new"],
    windowKeys: ["enquiries"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Enquiries from the sidebar.",
          "Click New enquiry.",
          "On Enquiry details, set source, status, and coordinator.",
          "On Participant, enter name, contact details, and demographics.",
          "On Support needs, describe disability, services sought, and notes.",
          "Save the record.",
          "Log calls and emails on the Activity tab as intake progresses.",
        ],
        relatedRoutes: ["/enquiries/new"],
      },
      {
        id: "next",
        title: "What happens next",
        body: "When intake is approved, convert the enquiry to a client. See How do I create a new client? for that workflow.",
        bullets: ["[How do I create a new client?](/help/create-a-new-client)"],
      },
    ],
  },
  {
    id: "article-create-location",
    slug: "create-a-new-location",
    title: "How do I create a new location?",
    summary: "Register a support site such as a SIL house or day program, then link clients and staff.",
    category: "Quick tasks",
    keywords: ["create location", "new location", "SIL", "site", "how do i"],
    relatedRoutes: ["/locations", "/locations/new"],
    windowKeys: ["locations"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Locations from the sidebar.",
          "Click New location.",
          "On Overview, set name, type, and capacity.",
          "On Contact and address, enter the site address and phone details.",
          "Save the record.",
          "Use the Clients, Employees, and Products and services tabs to add assignments.",
        ],
        relatedRoutes: ["/locations/new"],
      },
    ],
  },
  {
    id: "article-create-task",
    slug: "create-a-new-task",
    title: "How do I create a new task?",
    summary: "Create and assign work from the Tasks hub or from a linked record.",
    category: "Quick tasks",
    keywords: ["create task", "new task", "assign task", "request", "how do i"],
    relatedRoutes: ["/tasks", "/tasks/new"],
    windowKeys: ["tasks-assigned-to-me", "tasks-for-my-role", "tasks-all"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Tasks from the sidebar.",
          "Click New task.",
          "Enter a clear title and pick a task type.",
          "Set priority and due date if needed.",
          "Assign to a user, a role, or both.",
          "Link to an enquiry, client, employee, or location when the task relates to a record.",
          "Save the task.",
        ],
        relatedRoutes: ["/tasks/new"],
      },
      {
        id: "permissions",
        title: "If New task is missing",
        body: "Your role needs assign-task and create permission for that task type. An administrator can adjust this under System → Admin → Roles and System → Admin → Task management.",
        relatedRoutes: ["/system/admin/roles", "/system/admin/task-management"],
      },
    ],
  },
  {
    id: "article-convert-enquiry",
    slug: "convert-enquiry-to-client",
    title: "How do I convert an enquiry to a client?",
    summary: "Turn an approved intake enquiry into an active client record.",
    category: "Quick tasks",
    keywords: ["convert", "enquiry to client", "enrol", "activate client", "how do i"],
    relatedRoutes: ["/enquiries", "/clients"],
    windowKeys: ["enquiries", "clients"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open the enquiry from Enquiries or from an open workspace tab.",
          "Confirm Participant and Support needs are complete.",
          "Click Convert to client in the record actions.",
          "Open the new client from the prompt or from Clients → All clients.",
          "Review Overview and update Full profile fields.",
          "Save any further changes.",
        ],
      },
      {
        id: "requirements",
        title: "Requirements",
        body: "You need the enquiry-to-client process on your role. The enquiry should be in a status that allows conversion. If the action is missing, contact an administrator.",
      },
    ],
  },
  {
    id: "article-assign-client-location",
    slug: "assign-a-client-to-a-location",
    title: "How do I assign a client to a location?",
    summary: "Link a support receiver to a site from the location record or the client Locations tab.",
    category: "Quick tasks",
    keywords: ["assign client", "location", "link client", "SIL", "how do i"],
    relatedRoutes: ["/locations", "/clients"],
    windowKeys: ["locations", "clients", "location-clients"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "from-location",
        title: "From the location record",
        steps: [
          "Open Locations and open the site.",
          "Go to the Clients tab.",
          "Click Add row and select or enter the client.",
          "Set valid-from dates and save the location.",
        ],
        relatedRoutes: ["/locations"],
      },
      {
        id: "from-client",
        title: "From the client record",
        body: "On the client Locations tab, add an address row with service delivery flags. Align names and addresses with the support location record where the client receives services.",
        relatedRoutes: ["/clients"],
        windowKeys: ["client-locations"],
      },
    ],
  },
  {
    id: "article-export-report",
    slug: "export-a-report",
    title: "How do I export a report?",
    summary: "Download a CSV register from the Reports catalog.",
    category: "Quick tasks",
    keywords: ["export", "report", "csv", "download", "register", "how do i"],
    relatedRoutes: ["/reports"],
    windowKeys: ["reports"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Reports from the sidebar.",
          "Pick a report card your role can access.",
          "Read the description and column list.",
          "Click Export CSV.",
          "Open the downloaded file in Excel or your reporting tool.",
        ],
        relatedRoutes: ["/reports"],
      },
    ],
  },
  {
    id: "article-add-credential",
    slug: "add-a-credential-to-an-employee",
    title: "How do I add a credential to an employee?",
    summary: "Record checks, licences, and certifications on the employee file.",
    category: "Quick tasks",
    keywords: ["credential", "employee", "compliance", "expiry", "how do i"],
    relatedRoutes: ["/employees"],
    windowKeys: ["employees", "employee-credentials-assigned"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open People → Employees and open the staff member.",
          "Go to the Credentials Assigned tab under Compliance.",
          "Click Add credential.",
          "Enter type, number, issuing body, issue date, and expiry date.",
          "Save the employee record.",
        ],
        relatedRoutes: ["/employees"],
      },
      {
        id: "calendar",
        title: "Expiry on Home calendar",
        body: "When the employee record is linked to your user login, credential expiry dates appear on your Home calendar.",
        relatedRoutes: ["/"],
        windowKeys: ["home"],
      },
    ],
  },
  {
    id: "article-create-service-agreement",
    slug: "create-a-service-agreement",
    title: "How do I create a service agreement?",
    summary: "Link a client to funded service lines with products and quantities.",
    category: "Quick tasks",
    keywords: ["service agreement", "funding", "client", "NDIS", "how do i"],
    relatedRoutes: ["/service-agreements", "/clients"],
    windowKeys: ["service-agreements", "clients"],
    lastUpdated: "2025-06-16",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open the client and go to Service agreements, or open All service agreements under Clients in the sidebar.",
          "Click New service agreement.",
          "Complete Overview: client, dates, status, and funding.",
          "On Lines, add each service row with product and quantity.",
          "Save the agreement.",
        ],
        relatedRoutes: ["/service-agreements"],
      },
    ],
  },
  {
    id: "article-submit-leave",
    slug: "submit-leave-request",
    title: "How do I submit a leave request?",
    summary: "Staff submit leave from My workplace; managers approve via tasks and the review queue.",
    category: "Quick tasks",
    keywords: ["leave", "my workplace", "annual leave", "sick leave", "how do i", "submit leave"],
    relatedRoutes: ["/my/leave", "/workforce-planning#reviews"],
    windowKeys: ["my-leave"],
    lastUpdated: "2026-06-19",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open My workplace → Leave.",
          "Choose leave type and date range.",
          "Confirm you have enough balance for the leave type.",
          "Submit — status becomes Requested.",
          "Your manager receives an Approve task; track status on this page.",
        ],
        relatedRoutes: ["/my/leave"],
      },
      {
        id: "after",
        title: "After submit",
        body: "You are notified via tasks, not email. When approved, your balance updates. If declined, read the reason on My workplace → Leave.",
        relatedRoutes: ["/tasks"],
      },
    ],
  },
  {
    id: "article-approve-leave",
    slug: "approve-a-leave-request",
    title: "How do I approve a leave request?",
    summary: "HR and line managers approve or decline leave in Workforce planning or from an Approve task.",
    category: "Quick tasks",
    keywords: ["approve leave", "leave request", "manager", "HR", "how do i"],
    relatedRoutes: ["/workforce-planning#reviews", "/tasks"],
    windowKeys: ["workforce-planning", "approve-leave-request"],
    lastUpdated: "2026-06-19",
    sections: [
      {
        id: "queue",
        title: "From the review queue",
        steps: [
          "Open Workforce planning (or Home → Open review queue).",
          "Find the leave request under Leave requests pending approval.",
          "Approve or decline with an optional reason.",
        ],
        relatedRoutes: ["/workforce-planning#reviews"],
      },
      {
        id: "task",
        title: "From a task",
        body: "Open the Approve task from Tasks → Assigned to me. Use the Workforce review queue link, then approve or decline. The task closes automatically when you action the request.",
        relatedRoutes: ["/tasks"],
      },
      {
        id: "scope",
        title: "Who sees which requests",
        body: "HR roles see all pending leave. Team leaders and rostering managers see direct reports only.",
      },
    ],
  },
  {
    id: "article-review-credential",
    slug: "review-an-employee-credential",
    title: "How do I review a staff credential?",
    summary: "HR approves or rejects credentials submitted from My workplace.",
    category: "Quick tasks",
    keywords: ["credential", "review", "HR", "compliance", "pending review", "how do i"],
    relatedRoutes: ["/workforce-planning#reviews", "/employees"],
    windowKeys: ["review-employee-credential", "employee-credentials-assigned"],
    lastUpdated: "2026-06-19",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Workforce planning → Review queue, or open the Review task from Tasks.",
          "Find the credential under Credentials pending review.",
          "Check evidence on the employee Credentials tab if needed.",
          "Approve (Current) or reject with review notes.",
        ],
        relatedRoutes: ["/workforce-planning#reviews"],
      },
    ],
  },
  {
    id: "article-leave-on-behalf",
    slug: "submit-leave-on-behalf",
    title: "How do I submit leave for another employee?",
    summary: "Managers enter leave on Workforce planning when staff cannot use My workplace.",
    category: "Quick tasks",
    keywords: ["leave on behalf", "manager", "workforce planning", "how do i"],
    relatedRoutes: ["/workforce-planning#submit-leave"],
    windowKeys: ["workforce-planning", "submit-leave-on-behalf"],
    lastUpdated: "2026-06-19",
    sections: [
      {
        id: "steps",
        title: "Steps",
        steps: [
          "Open Workforce planning.",
          "Scroll to Submit leave on behalf.",
          "Select employee, leave type, dates, and notes.",
          "Submit — the request follows the normal approval path and creates an Approve task.",
        ],
        relatedRoutes: ["/workforce-planning#submit-leave"],
      },
    ],
  },
];
