import type { HelpArticle } from "@/lib/help/types";

export const taskAutomationsArticle: HelpArticle = {
  id: "article-task-automations",
  slug: "task-automations",
  title: "Task automations: configure in-app alerts",
  summary:
    "Create rules that automatically assign tasks when something happens in AbilityAPP. All record types are live, including org-position and accountable-manager assignment.",
  category: "System setup",
  keywords: [
    "task automation",
    "automation rule",
    "in-app alert",
    "trigger",
    "incident task",
    "NDIS overdue",
    "investigation SLA",
    "role task",
    "dedupe",
    "template",
    "admin task automations",
    "how to",
  ],
  relatedRoutes: [
    "/system/tasks/task-automations",
    "/system/tasks/task-management",
    "/system/admin/roles",
    "/tasks",
    "/tasks/my-role",
  ],
  windowKeys: ["admin-task-automations", "admin-task-management"],
  lastUpdated: "2026-06-17",
  sections: [
    {
      id: "what-are-task-automations",
      title: "What task automations are",
      body:     "Task automations replace external email for many operational alerts. Rules can assign to a security role, an org position holder, or the incident accountable manager.\n\nAll rule types are live: enquiry, client, location, employee (including scheduled credential expiry), and incident (including scheduled NDIS and investigation SLA checks).",
      bullets: [
        "Automations are rules, not one-off tasks.",
        "Each rule has a rule type (enquiry, client, location, employee, or incident).",
        "Assign to: Security role, Org position holder, or Incident accountable manager.",
        "Scheduled scans run once per browser day for overdue incidents and expiring credentials.",
      ],
      relatedRoutes: ["/system/tasks/task-automations"],
      windowKeys: ["admin-task-automations"],
    },
    {
      id: "who-can-configure",
      title: "Who can configure automations",
      body: "You need the Task automations window on your role. AbilityAPP Admin includes it by default. Other roles can be granted access under System → Admin → Roles by adding the Task automations window.\n\nUsers who receive automated tasks do not need the admin window. They only need task windows (for example My role) and permission to see the linked record type.",
      relatedRoutes: ["/system/admin/roles", "/system/tasks/task-automations"],
      windowKeys: ["admin-roles", "admin-task-automations"],
    },
    {
      id: "open-the-admin-page",
      title: "Open the task automations page",
      steps: [
        "Sign in to System with a user who can configure the tenant (typically the same as AbilityAPP Admin).",
        "Open System → Tasks → Task automations.",
        "The left panel lists rules grouped by rule type: Enquiry, Client, Location, Employee, Incident.",
        "Click a rule to edit it, or click Add rule to create a new one.",
      ],
      relatedRoutes: ["/system/tasks/task-automations"],
    },
    {
      id: "rule-types",
      title: "Rule types (record types)",
      body: "Every rule belongs to exactly one rule type. The type controls which triggers appear in the dropdown and how rules are sorted in the left panel.\n\nIn the rules panel, types appear in the order below. Within each type, rules sort by Sort order then name. Types marked (configure only) in the panel can be saved but will not create tasks until that engine is released.",
      bullets: [
        "Enquiry: intake events such as new enquiry or status change (configure only; engine coming later).",
        "Client: client record events such as new client or new alert line (configure only).",
        "Location: support location events such as new site or new alert (configure only).",
        "Employee: staff events such as new employee or credential expiry (configure only).",
        "Incident: reportable incidents, NDIS deadlines, and investigation SLA (live today).",
      ],
    },
    {
      id: "anatomy-of-a-rule",
      title: "Anatomy of a rule",
      body: "A complete rule has four parts: when (trigger), optional filters (conditions), what to create (task template), and who acts (role assignment).",
      bullets: [
        "Name: short label shown in the rules list and in the task Created by field.",
        "Active: inactive rules are ignored by the engine.",
        "Rule type: enquiry, client, location, employee, or incident.",
        "Trigger: the event that can fire the rule.",
        "Conditions: optional filters (incident rules support reportable, status, and severity).",
        "Task type: Review, Check, Approve, etc. from System → Tasks → Task management.",
        "Title and description templates: text with placeholders filled from the record.",
        "Priority: Low, Normal, or High.",
        "Due in (hours) or Due in (days): when the task is due from the moment it is created.",
        "Assign to role: every member of that role can pick up the task from My role.",
        "Dedupe policy: stops duplicate open tasks for the same record.",
        "Sort order: ordering within the same rule type when multiple rules match.",
      ],
    },
    {
      id: "incident-triggers-event",
      title: "Incident triggers (event-driven)",
      body: "These run when an incident is saved.",
      bullets: [
        "Incident created: fires when a new incident is saved.",
        "Incident updated: fires on any save; narrow with conditions if needed.",
        "Marked reportable: fires when Is reportable changes from No to Yes.",
        "Status changed: fires when status changes.",
      ],
      relatedRoutes: ["/incidents", "/incidents/new"],
      windowKeys: ["incidents"],
    },
    {
      id: "incident-triggers-scheduled",
      title: "Incident triggers (scheduled)",
      body: "These are checked when a user opens the app (at most once per 24 hours per browser session). They catch situations that become true over time without another save.",
      bullets: [
        "NDIS notification overdue: reportable incident, NDIS not yet recorded as notified, and past the report deadline.",
        "Investigation SLA breached: open incident past the organisation investigation SLA days (set under System → Organisation → Organisation profile).",
      ],
      relatedRoutes: ["/system/organization", "/incidents/dashboard"],
      windowKeys: ["admin-organization", "incidents-dashboard"],
    },
    {
      id: "placeholders",
      title: "Template placeholders (incidents)",
      body: "Use double curly braces in title and description templates. The engine replaces them when the task is created.",
      bullets: [
        "{{incident.documentNo}}: incident number, for example INC-1000003.",
        "{{incident.title}}: incident title or Untitled if empty.",
        "{{incident.status}}: current status.",
        "{{incident.severity}}: Low, Medium, High, or Critical.",
        "{{incident.reportDeadlineAt}}: formatted NDIS report deadline.",
        "{{incident.daysOpen}}: days since the incident was opened.",
        "{{org.investigationSlaDays}}: organisation investigation SLA from System → Organisation.",
      ],
    },
    {
      id: "due-dates",
      title: "How due dates work",
      body: "Set Due in (hours) or Due in (days), not both as the primary offset. If hours is set, the due date is that many hours from task creation. If hours is empty, days is used (zero means due today).\n\nExample: Reportable incident review with 24 hours due gives the role one day to open the linked incident and complete manager review.",
    },
    {
      id: "dedupe-policies",
      title: "Dedupe policies",
      bullets: [
        "One open task per record (recommended): if a task from this rule is already Open or In progress for that incident, do not create another.",
        "Once ever per record: never create a second task from this rule for the same incident, even after the first is completed.",
        "No deduplication: create a task every time the trigger fires (use sparingly).",
      ],
      body: "Dedupe uses a stable key per rule and record so the database can enforce one open task without scanning the entire task table.",
    },
    {
      id: "what-users-see",
      title: "What users see when a rule fires",
      steps: [
        "A new task appears with status Open.",
        "Created by shows System (rule name).",
        "The task links to the incident (or future record types).",
        "Assignee is the role you chose; any user with that role sees it under Tasks → My role.",
        "The user opens the task, follows the link to the record, does the work, then completes the task with resolution notes if required.",
      ],
      relatedRoutes: ["/tasks", "/tasks/my-role", "/tasks/assigned-to-me"],
    },
    {
      id: "preview-and-dry-run",
      title: "Preview and dry run (incident rules)",
      body: "For incident rules, the Preview section at the bottom of the rule editor shows how templates render for a sample incident from your database. Dry run tells you whether the current trigger and conditions would create a task for that sample, or whether dedupe would skip it.\n\nDry run does not create a task. It is safe to use while tuning conditions.",
      relatedRoutes: ["/system/tasks/task-automations"],
    },
    {
      id: "walkthrough-reportable",
      title: "Walkthrough: reportable incident manager review",
      steps: [
        "Open System → Tasks → Task automations.",
        "Add rule or edit Reportable incident — manager review.",
        "Set Rule type to Incident.",
        "Set Trigger to Marked reportable.",
        "Under Conditions, set Reportable only to Reportable only.",
        "Set Task type to Review, Priority to High, Due in (hours) to 24.",
        "Set Assign to role to AbilityAPP Admin or your quality manager role.",
        "Set Dedupe policy to One open task per record.",
        "Save rule.",
        "Test: open an incident, set Is reportable to Yes, save. Check Tasks → My role for the assigned role.",
      ],
      relatedRoutes: ["/incidents", "/system/tasks/task-automations"],
    },
    {
      id: "walkthrough-ndis-overdue",
      title: "Walkthrough: NDIS notification overdue",
      steps: [
        "Confirm investigation and NDIS settings under System → Organisation → Organisation profile.",
        "Edit or create a rule with Trigger NDIS notification overdue.",
        "Use task type Check and High priority; due today (Due in days = 0).",
        "Assign to the role responsible for Commission notification.",
        "Save the rule.",
        "For reportable incidents past deadline without NDIS notified date, tasks are created on the next scheduled check (after a user opens the app, at most once per 24 hours per browser).",
      ],
      relatedRoutes: ["/system/organization", "/incidents/compliance"],
    },
    {
      id: "walkthrough-investigation-sla",
      title: "Walkthrough: investigation SLA breached",
      body: "Set System → Organisation → Organisation profile → Investigation SLA (days) to match your policy (default 14). Create or edit a rule with Trigger Investigation SLA breached. Assign to your coordinator or quality role. The task description can reference {{incident.daysOpen}} and {{org.investigationSlaDays}} so the assignee sees how far over SLA the incident is.",
      relatedRoutes: ["/system/organization", "/incidents/dashboard"],
    },
    {
      id: "default-seeded-rules",
      title: "Default rules in new environments",
      body: "Three incident rules are seeded in the database: reportable manager review (admin role), NDIS overdue (admin role), and investigation SLA (coordinator role). You can edit, deactivate, or delete them. Re-run supabase/seed-task-automation.sql to restore defaults without duplicating rows.",
    },
    {
      id: "configure-only-types",
      title: "Enquiry, client, location, and employee rules",
      body: "You can create and save rules for these types today. Triggers available in the admin UI include enquiry created, client alert added, location alert added, and employee credential expiring. Automatic task creation for these types is not active yet; the rules panel shows (configure only) under those headings.\n\nWhen the engine for a type is released, saved rules will start running without re-entering templates, provided the trigger names stay the same.",
      bullets: [
        "Use the same task types and roles you already use for manual work.",
        "Write templates as if the record placeholders for that module already exist.",
        "Keep dedupe on One open task per record unless you have a strong reason not to.",
      ],
    },
    {
      id: "troubleshooting",
      title: "Troubleshooting",
      bullets: [
        "No task after saving an incident: confirm the rule is Active, rule type is Incident, trigger matches what you did (for example reportable set requires changing Is reportable to Yes).",
        "No task for overdue NDIS: scheduled rules run after app load, not every second; open Home once and wait for the next day if you already ran the check in this browser session.",
        "Duplicate tasks: check Dedupe policy; use One open task per record.",
        "Role cannot see task: confirm the user’s active role matches Assign to role, and that the role has Tasks → My role window access.",
        "Cannot open Task automations: confirm System access; in the workspace, confirm System → Admin → Roles includes the Task automations window for your role.",
        "Preview missing: preview is only for incident rules while the incident engine is live.",
      ],
      relatedRoutes: ["/system/admin/roles", "/tasks/my-role"],
    },
    {
      id: "related-admin",
      title: "Related administration",
      bullets: [
        "System → Tasks → Task management: define task types (Review, Check, Approve) and which roles can create them.",
        "System → Admin → Roles: grant task windows and the Task automations window.",
        "System → Organisation → Organisation profile: investigation SLA days for incident dashboard and automation.",
        "Tasks hub: where assignees work automated and manual tasks.",
      ],
      relatedRoutes: [
        "/system/tasks/task-management",
        "/system/admin/roles",
        "/system/organization",
        "/tasks",
      ],
    },
  ],
};
