import type { HelpArticle } from "@/lib/help/types";

export const workforceLeaveCalendarArticle: HelpArticle = {
  id: "article-workforce-leave-calendar",
  slug: "workforce-leave-calendar",
  title: "Workforce planning: leave calendar and reviews",
  summary:
    "View team leave, approve requests in the review queue, submit leave on behalf of staff, and track pending credentials — with tasks (not email) for assignees.",
  category: "People",
  keywords: [
    "workforce planning",
    "leave",
    "leave calendar",
    "review queue",
    "approve leave",
    "credential review",
    "submit on behalf",
    "annual leave",
    "roster",
    "how to",
  ],
  relatedRoutes: ["/workforce-planning", "/workforce-planning#reviews", "/workforce-planning#submit-leave"],
  windowKeys: ["workforce-planning"],
  lastUpdated: "2026-06-19",
  sections: [
    {
      id: "open",
      title: "Open workforce planning",
      steps: [
        "Sign in with a role that includes Workforce planning.",
        "Open Workforce planning in the sidebar.",
        "Review the pipeline summary cards: leave awaiting approval, approved upcoming, credentials pending.",
        "Scroll to Review queue (#reviews) if you can approve leave or sign off credentials.",
      ],
      relatedRoutes: ["/workforce-planning"],
    },
    {
      id: "review-queue",
      title: "Review queue (credentials and leave)",
      body: "HR roles see all pending credentials and leave requests. Line managers with approve-leave-request see leave for direct reports only — not the whole organisation.\n\nSupport coordinators do not receive review access unless explicitly granted HR processes.",
      steps: [
        "Open Workforce planning → Review queue (or Home → Open review queue when the banner shows).",
        "For credentials: approve (Current) or reject with review notes.",
        "For leave: approve or decline with an optional reason.",
        "Approved leave deducts days from the employee entitlement balance.",
        "The matching automation task closes when you action the item here.",
      ],
      relatedRoutes: ["/workforce-planning#reviews"],
      windowKeys: ["workforce-planning"],
    },
    {
      id: "who-reviews",
      title: "Who can review what",
      bullets: [
        "Credential review (review-employee-credential): CEO, HR executive, HR manager, HR officer",
        "Leave approval (approve-leave-request): HR roles above, plus rostering manager and team leader for direct reports",
        "Coordinators and general executives: submit leave for themselves; no org-wide review queue",
      ],
    },
    {
      id: "calendar",
      title: "Organisation leave calendar",
      body: "The month grid shows requested, approved, and taken leave across employees. Click a name to open the employee Leave tab. Use Prev/Next to change months.",
      relatedRoutes: ["/workforce-planning"],
    },
    {
      id: "upcoming-table",
      title: "Upcoming leave table",
      body: "Lists future leave and open requests sorted by start date. Open the employee from the name link to see entitlements and history.",
      relatedRoutes: ["/workforce-planning"],
    },
    {
      id: "submit-on-behalf",
      title: "Submit leave on behalf",
      body: "Managers and coordinators with submit-leave-on-behalf can enter leave for someone who cannot use My workplace. The request follows the same approval path and creates an Approve task for the employee's manager.",
      steps: [
        "Scroll to Submit leave on behalf on Workforce planning.",
        "Select employee, leave type, dates, and notes.",
        "Submit — the request appears on the employee record and in the review queue.",
      ],
      relatedRoutes: ["/workforce-planning#submit-leave"],
    },
    {
      id: "tasks",
      title: "Tasks, not email",
      body: "Review work is assigned via task automations. Assignees see Approve or Review tasks under Tasks → Assigned to me or My role. Task detail links to the review queue and the employee Leave or Credentials tab.",
      relatedRoutes: ["/tasks", "/help/task-automations"],
    },
    {
      id: "organisation",
      title: "Organisation structure",
      body: "Switch to Organisation structure to maintain the position tree, holders, and reporting lines. See [Workforce organisation structure](/help/workforce-organisation).",
      relatedRoutes: ["/workforce-planning/organisation", "/help/workforce-organisation"],
    },
    {
      id: "setup",
      title: "Configure leave types",
      body: "Leave type and status lists are maintained in System setup. See [Workforce planning setup](/system/guides/workforce-setup).",
      relatedRoutes: ["/system/setup/workforce", "/system/guides/workforce-setup"],
    },
  ],
};

export const workforceOrganisationArticle: HelpArticle = {
  id: "article-workforce-organisation",
  slug: "workforce-organisation",
  title: "Workforce planning: organisation structure and automations",
  summary:
    "Build and maintain the position tree, assign holders, filter by site, route tasks through org positions, and sign off reportable incidents as the accountable manager.",
  category: "People",
  keywords: [
    "organisation structure",
    "org chart",
    "position",
    "team leader",
    "support worker",
    "business area",
    "location filter",
    "acting holder",
    "primary holder",
    "accountable manager",
    "manager review",
    "task automation",
    "org position",
    "workforce planning",
    "how to",
  ],
  relatedRoutes: [
    "/workforce-planning/organisation",
    "/workforce-planning",
    "/system/admin/task-automations",
    "/incidents",
    "/help/task-automations",
  ],
  windowKeys: ["workforce-organisation", "workforce-planning", "workforce-org-edit", "workforce-org-chart-tier"],
  lastUpdated: "2026-06-19",
  sections: [
    {
      id: "overview",
      title: "What this module does",
      body: "Organisation structure is the position tree for your workforce. Each node is a position slot in the reporting tree — not a person and not a new security role. People are assigned as primary or acting holders.\n\nEvery position must link to exactly one role from System → Admin → Roles. That role controls app access (windows, tasks, processes). Many positions can share the same role — for example eleven Support Worker slots all map to the Support Worker role.\n\nThe tree drives escalation when a position is vacant and routes automated tasks to the right manager.",
      bullets: [
        "Security role — chosen from Admin → Roles; defines what holders can do in the app.",
        "Position title — optional site-specific label (for example Team Leader — Northern SIL).",
        "Positions can link to a business area and support location.",
        "Vacant positions escalate to the parent position holder.",
        "Acting assignments cover leave without changing reporting lines.",
        "Task automations can assign to a security role, an org position holder, or the incident accountable manager.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
      windowKeys: ["workforce-organisation"],
    },
    {
      id: "access",
      title: "Who can view and edit",
      body: "View the chart with the Organisation structure or Workforce planning window. Edit positions, holders, and reporting lines with Organisation structure — edit.\n\nIncident manager review is restricted separately: only the accountable manager (or someone with Override manager review) can sign off reportable incidents.",
      bullets: [
        "workforce-organisation — view the chart and position details",
        "workforce-org-edit — drag reparent, change holders, edit position fields",
        "workforce-org-chart-tier — change chart tier bands (typically admin only; assign in Admin → Roles)",
        "incident-manager-override — sign off reportable incidents when you are not the accountable manager (typically admin)",
      ],
      relatedRoutes: ["/admin/roles", "/workforce-planning/organisation"],
      windowKeys: ["workforce-organisation", "workforce-org-edit", "incident-manager-override"],
    },
    {
      id: "open-org-chart",
      title: "Open the organisation chart",
      steps: [
        "Sign in with a role that includes Workforce planning or Organisation structure.",
        "Open Workforce planning in the sidebar.",
        "Click Organisation structure.",
        "The chart shows tier bands from governance through delivery staff.",
        "Click a card to open the position editor on the right.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
    },
    {
      id: "filters",
      title: "Filter by business area or location",
      body: "Use the filter bar above the chart to narrow what you see. Filters keep matching positions plus every ancestor up to the root, so the tree stays connected.\n\nWhen filters are active, a summary shows how many positions are visible and how many primary holders are on leave today.",
      steps: [
        "Choose a business area (for example Operations) and/or a support location.",
        "Review the filtered subtree — site team leaders and their support workers appear under Operations nodes.",
        "Click Clear filters to return to the full tree.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
    },
    {
      id: "chart-layout",
      title: "Reading a large chart",
      body: "The chart uses manually managed tiers — horizontal bands labelled Tier 1 through Tier 7. Each position sits on the tier set in the Chart tier section of the position editor (right panel after you click a card).\n\nChanging tiers requires Organisation structure — chart tiers in System → Admin → Roles (seeded on AbilityAPP Admin only). Other editors can view the current tier but cannot change it.\n\nTypical bands: governance and board (tiers 1–2), CEO (3), executives (4), managers (5), team leaders (6), support workers (7). Peers on the same tier appear side by side; scroll sideways on wide rows.\n\nDrag the grip (⋮⋮) onto another card to change solid reporting (Reports to in the editor). Change Chart tier if a card is on the wrong row (admin permission).\n\nDotted lines (⋯→ on cards) show secondary accountability without moving the card tier.\n\nSupport workers (three or more on tier 7) collapse into Support Worker × N. Click Expand to see each holder.\n\nUse Chart view lenses to focus on executive council or functional delivery.",
      relatedRoutes: ["/workforce-planning/organisation"],
    },
    {
      id: "security-role",
      title: "Link a position to a security role",
      body: "Positions never create new security roles. When you add or edit a position, choose Security role from the dropdown — the list comes from System → Admin → Roles.\n\nThe position title is for display (often a site label). Holders still need the matching role assigned on their user record on Employee → System access.",
      steps: [
        "Open Admin → Roles and confirm the role you need exists (for example Team Leader, Support Worker).",
        "Select a position in the org chart.",
        "Choose Security role in the editor.",
        "Set Position title if you need a site-specific label.",
        "Assign primary and acting holders as needed.",
      ],
      relatedRoutes: ["/admin/roles", "/workforce-planning/organisation"],
    },
    {
      id: "holder-login-role",
      title: "Align holders with login roles",
      body: "A position’s security role defines what someone in that slot should be able to do in the app. The holder also needs a linked user on Employee → System access with that role assigned.\n\nAbilityAPP warns (but does not block) when these are out of sync — on the chart, in the position editor, and when you confirm a holder change. Use the fix button to add the missing role or create a login (default password welcome).",
      bullets: [
        "Chart cards show login role mismatch when the primary or acting holder’s user roles do not include the position security role.",
        "Employees with no linked user are flagged — common for staff who do not log in.",
        "Click Add role to login or Create login with role on the warning — requires Organisation structure — edit or Employee system-access access.",
        "Board chair Eleanor Wright (EleanorWright) and all manager/officer seed logins use password welcome unless noted.",
      ],
      relatedRoutes: ["/employees", "/workforce-planning/organisation"],
    },
    {
      id: "dotted-reporting",
      title: "Dotted (matrix) reporting lines",
      body: "Solid reporting (drag-and-drop reparent) drives escalation, accountable manager routing, and task automations. Dotted lines are secondary — they appear on the chart and in the position editor but do not change who receives escalations.\n\nExample: four board members sit side by side as peers under Board of Directors. Each member has a dotted line to the chair for board protocol, while the CEO remains on a solid line under the board container.",
      steps: [
        "Select a position in the chart.",
        "In Also reports to (dotted), choose a target position and click Add.",
        "Dotted connectors render on the chart; cards show ⋯→ target title.",
        "Remove a dotted line with Remove in the editor.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
    },
    {
      id: "reparent",
      title: "Change reporting lines (drag and confirm)",
      body: "Reporting lines are changed by dragging, not by editing a field. This prevents accidental hierarchy changes while updating titles or locations.",
      steps: [
        "On a position card, grip the ⋮⋮ handle on the right (edit access required).",
        "Drag the card onto the new parent position and release.",
        "Read the confirmation dialog — dependent positions under the moved node move with it.",
        "Click Confirm move to save.",
      ],
      bullets: [
        "You cannot drop a position onto its own descendant.",
        "Reparenting does not change who holds the position.",
      ],
    },
    {
      id: "primary-holder",
      title: "Assign or change the primary holder",
      body: "The primary holder is the person accountable for that position. Changing holder is a separate action from changing reporting lines.",
      steps: [
        "Select a position in the chart.",
        "In the editor, open the Primary holder dropdown and choose an employee or Vacant.",
        "Confirm in the dialog — assignment updates escalation and task routing.",
        "Use View employee or View location links for quick navigation.",
      ],
    },
    {
      id: "acting-holder",
      title: "Assign an acting holder",
      body: "Acting holders cover leave or temporary absence. While acting is set, escalation and task resolution use the acting person before escalating to the parent manager.",
      steps: [
        "Select the position.",
        "Choose an acting holder in the Acting holder dropdown.",
        "Confirm the assignment in the dialog.",
        "Clear acting by choosing — None — and confirming.",
      ],
      bullets: [
        "Cards show Acting: Name when an acting assignment is active.",
        "Primary holders on approved leave show (on leave) on the chart.",
      ],
    },
    {
      id: "bulk-support-workers",
      title: "Support worker positions (test data)",
      body: "Seed data maps 32 bulk support workers under three site team leaders: Northern SIL, Southern Respite, and Murray Bridge Day. Team leader positions are vacant in seed data so escalation flows up to the Team Leader — Support coordination (Michael Smith).\n\nTo reload workforce test data on Supabase, run npm run supabase:seed-workforce from the repository root (after employees and locations are present).",
      bullets: [
        "Northern SIL — support workers emp-sw-001 … emp-sw-011",
        "Southern Respite — emp-sw-012 … emp-sw-022",
        "Murray Bridge Day — emp-sw-023 … emp-sw-032",
      ],
    },
    {
      id: "accountable-manager",
      title: "Accountable manager on incidents",
      body: "On a reportable incident with an employee party, the Overview tab shows Accountable manager — resolved one level up the org tree from that employee's position. If the immediate manager position is vacant, escalation walks up until a holder is found.",
      steps: [
        "Open the incident and add an Employee party (or set primary employee).",
        "Check Overview for the Accountable manager banner.",
        "Submitted reportable incidents can only be signed off by that manager (or override).",
        "Mark manager reviewed, then proceed with commission notification and investigation.",
      ],
      relatedRoutes: ["/incidents"],
      windowKeys: ["incidents", "incident-manager-override"],
    },
    {
      id: "task-automations-org",
      title: "Task automations and org positions",
      body: "Task automation rules can assign work three ways:\n\n1. Security role — task appears in My role for everyone with that role.\n2. Org position holder — resolves the primary or acting holder of a chosen position; falls back to the fallback role if no login user is linked.\n3. Incident accountable manager — resolves the manager for the employee party on the incident.\n4. Employee reports-to manager — resolves the login user for the employee's reports-to manager (workforce leave tasks).\n\nLive engines: enquiry, client, location, employee (credential pending review, leave requested, scheduled credential expiry), and incident (scheduled NDIS and investigation SLA).",
      bullets: [
        "Reportable incident review → accountable manager",
        "NDIS overdue / investigation SLA → pos-gm-ops holder (Michael)",
        "New enquiry → Intake role",
        "Credential pending review → HR officer role",
        "Leave requested → reports-to manager (fallback HR manager role)",
        "Credential expiring within 30 days → scheduled scan",
        "Server scheduled run: POST /api/workforce/automation/scheduled (workforce-planning access)",
      ],
      relatedRoutes: ["/system/admin/task-automations", "/system/guides/task-automations"],
      windowKeys: ["admin-task-automations"],
    },
    {
      id: "test-scenarios",
      title: "Suggested test scenarios",
      body: "Use these flows after seeding workforce data.",
      bullets: [
        "Login as MichaelSmith — open a reportable incident with emp-sw-001 as party; sign off manager review.",
        "Login as AvaThomas (support worker) — confirm the same incident does not offer manager review.",
        "Login as SuperUser — override works via incident-manager-override on the admin role.",
        "Filter org chart to Northern SIL and confirm 11 support worker positions appear.",
        "Add a client alert line and check Tasks for the automation task.",
        "Open System → Admin → Task automations and dry-run a rule against a sample incident.",
      ],
    },
    {
      id: "seed-command",
      title: "Reload workforce seed data (Supabase)",
      steps: [
        "From the repo root: npm run supabase:seed-workforce",
        "This runs employees → locations → org structure → bulk positions → task automations in order.",
        "For local Supabase: npm run supabase:seed-workforce-local",
        "Regenerate bulk TypeScript/SQL after changing SW mapping: node scripts/generate-org-bulk-positions.mjs",
      ],
    },
  ],
};
