import type { HelpArticle } from "@/lib/help/types";

export const workforceOrganisationArticle: HelpArticle = {
  id: "article-workforce-organisation",
  slug: "workforce-organisation",
  title: "Workforce planning: organisation structure and automations",
  summary:
    "Build and maintain the position tree, assign holders, filter by site, route tasks through org positions, and sign off reportable incidents as the accountable manager.",
  category: "People",
  keywords: [
    "organisation structure",
    "org chart",
    "position",
    "team leader",
    "support worker",
    "business area",
    "location filter",
    "acting holder",
    "primary holder",
    "accountable manager",
    "manager review",
    "task automation",
    "org position",
    "workforce planning",
    "how to",
  ],
  relatedRoutes: [
    "/workforce-planning/organisation",
    "/workforce-planning",
    "/admin/task-automations",
    "/incidents",
    "/help/task-automations",
  ],
  windowKeys: ["workforce-organisation", "workforce-planning", "workforce-org-edit"],
  lastUpdated: "2026-06-17",
  sections: [
    {
      id: "overview",
      title: "What this module does",
      body: "Organisation structure is the position tree for your workforce. Each node is a role (position), not a person. People are assigned as primary or acting holders. The tree drives escalation when a position is vacant and routes automated tasks to the right manager.\n\nWorkforce planning also connects to incident accountability: when a reportable incident names an employee party, AbilityAPP resolves their line manager from this tree.",
      bullets: [
        "Positions can link to a business area and support location.",
        "Vacant positions escalate to the parent position holder.",
        "Acting assignments cover leave without changing reporting lines.",
        "Task automations can assign to a security role, an org position holder, or the incident accountable manager.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
      windowKeys: ["workforce-organisation"],
    },
    {
      id: "access",
      title: "Who can view and edit",
      body: "View the chart with the Organisation structure or Workforce planning window. Edit positions, holders, and reporting lines with Organisation structure — edit.\n\nIncident manager review is restricted separately: only the accountable manager (or someone with Override manager review) can sign off reportable incidents.",
      bullets: [
        "workforce-organisation — view the chart and position details",
        "workforce-org-edit — drag reparent, change holders, edit fields",
        "incident-manager-override — sign off reportable incidents when you are not the accountable manager (typically admin)",
      ],
      relatedRoutes: ["/admin/roles", "/workforce-planning/organisation"],
      windowKeys: ["workforce-organisation", "workforce-org-edit", "incident-manager-override"],
    },
    {
      id: "open-org-chart",
      title: "Open the organisation chart",
      steps: [
        "Sign in with a role that includes Workforce planning or Organisation structure.",
        "Open Workforce planning in the sidebar.",
        "Click Organisation structure.",
        "The chart shows the root organisation node at the top and dependent positions below.",
        "Click a card to open the position editor on the right.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
    },
    {
      id: "filters",
      title: "Filter by business area or location",
      body: "Use the filter bar above the chart to narrow what you see. Filters keep matching positions plus every ancestor up to the root, so the tree stays connected.\n\nWhen filters are active, a summary shows how many positions are visible and how many primary holders are on leave today.",
      steps: [
        "Choose a business area (for example Operations) and/or a support location.",
        "Review the filtered subtree — site team leaders and their support workers appear under Operations nodes.",
        "Click Clear filters to return to the full tree.",
      ],
      relatedRoutes: ["/workforce-planning/organisation"],
    },
    {
      id: "reparent",
      title: "Change reporting lines (drag and confirm)",
      body: "Reporting lines are changed by dragging, not by editing a field. This prevents accidental hierarchy changes while updating titles or locations.",
      steps: [
        "On a position card, grip the ⋮⋮ handle on the right (edit access required).",
        "Drag the card onto the new parent position and release.",
        "Read the confirmation dialog — dependent positions under the moved node move with it.",
        "Click Confirm move to save.",
      ],
      bullets: [
        "You cannot drop a position onto its own descendant.",
        "Reparenting does not change who holds the position.",
      ],
    },
    {
      id: "primary-holder",
      title: "Assign or change the primary holder",
      body: "The primary holder is the person accountable for that position. Changing holder is a separate action from changing reporting lines.",
      steps: [
        "Select a position in the chart.",
        "In the editor, open the Primary holder dropdown and choose an employee or Vacant.",
        "Confirm in the dialog — assignment updates escalation and task routing.",
        "Use View employee or View location links for quick navigation.",
      ],
    },
    {
      id: "acting-holder",
      title: "Assign an acting holder",
      body: "Acting holders cover leave or temporary absence. While acting is set, escalation and task resolution use the acting person before escalating to the parent manager.",
      steps: [
        "Select the position.",
        "Choose an acting holder in the Acting holder dropdown.",
        "Confirm the assignment in the dialog.",
        "Clear acting by choosing — None — and confirming.",
      ],
      bullets: [
        "Cards show Acting: Name when an acting assignment is active.",
        "Primary holders on approved leave show (on leave) on the chart.",
      ],
    },
    {
      id: "bulk-support-workers",
      title: "Support worker positions (test data)",
      body: "Seed data maps 32 bulk support workers under three site team leaders: Northern SIL, Southern Respite, and Murray Bridge Day. Team leader positions are vacant in seed data so escalation flows up to the Team Leader — Support coordination (Michael Smith).\n\nTo reload workforce test data on Supabase, run npm run supabase:seed-workforce from the repository root (after employees and locations are present).",
      bullets: [
        "Northern SIL — support workers emp-sw-001 … emp-sw-011",
        "Southern Respite — emp-sw-012 … emp-sw-022",
        "Murray Bridge Day — emp-sw-023 … emp-sw-032",
      ],
    },
    {
      id: "accountable-manager",
      title: "Accountable manager on incidents",
      body: "On a reportable incident with an employee party, the Overview tab shows Accountable manager — resolved one level up the org tree from that employee's position. If the immediate manager position is vacant, escalation walks up until a holder is found.",
      steps: [
        "Open the incident and add an Employee party (or set primary employee).",
        "Check Overview for the Accountable manager banner.",
        "Submitted reportable incidents can only be signed off by that manager (or override).",
        "Mark manager reviewed, then proceed with commission notification and investigation.",
      ],
      relatedRoutes: ["/incidents"],
      windowKeys: ["incidents", "incident-manager-override"],
    },
    {
      id: "task-automations-org",
      title: "Task automations and org positions",
      body: "Task automation rules can assign work three ways:\n\n1. Security role — task appears in My role for everyone with that role.\n2. Org position holder — resolves the primary or acting holder of a chosen position; falls back to the fallback role if no login user is linked.\n3. Incident accountable manager — resolves the manager for the employee party on the incident.\n\nLive engines today: enquiry, client, location, employee (including scheduled credential expiry), and incident (including scheduled NDIS and investigation SLA checks).",
      bullets: [
        "Reportable incident review → accountable manager",
        "NDIS overdue / investigation SLA → pos-gm-ops holder (Michael)",
        "New enquiry → Intake role",
        "Credential expiring within 30 days → scheduled scan, Team Leader position",
        "Client or location alert added → coordinator or team leader",
      ],
      relatedRoutes: ["/admin/task-automations", "/help/task-automations"],
      windowKeys: ["admin-task-automations"],
    },
    {
      id: "test-scenarios",
      title: "Suggested test scenarios",
      body: "Use these flows after seeding workforce data.",
      bullets: [
        "Login as MichaelSmith — open a reportable incident with emp-sw-001 as party; sign off manager review.",
        "Login as AvaThomas (support worker) — confirm the same incident does not offer manager review.",
        "Login as SuperUser — override works via incident-manager-override on the admin role.",
        "Filter org chart to Northern SIL and confirm 11 support worker positions appear.",
        "Add a client alert line and check Tasks for the automation task.",
        "Open Admin → Task automations and dry-run a rule against a sample incident.",
      ],
    },
    {
      id: "seed-command",
      title: "Reload workforce seed data (Supabase)",
      steps: [
        "From the repo root: npm run supabase:seed-workforce",
        "This runs employees → locations → org structure → bulk positions → task automations in order.",
        "For local Supabase: npm run supabase:seed-workforce-local",
        "Regenerate bulk TypeScript/SQL after changing SW mapping: node scripts/generate-org-bulk-positions.mjs",
      ],
    },
  ],
};
