-- Timesheet submitted task automation (manager approval on submit).
insert into public.app_task_automation (
  id,
  name,
  active,
  module,
  trigger_event,
  conditions,
  task_type_id,
  title_template,
  description_template,
  priority,
  due_offset_hours,
  due_offset_days,
  due_from_field,
  assignee_mode,
  assignee_position_id,
  assignee_role_id,
  dedupe_policy,
  sort_order
)
values
  (
    'tar-timesheet-submitted',
    'Timesheet submitted — manager approval',
    true,
    'employees',
    'timesheet.submitted',
    '{}'::jsonb,
    'tt-approve',
    'Approve timesheet — {{employee.name}}',
    '{{employee.name}} submitted timesheet {{timesheet.documentNo}} for {{timesheet.period}} ({{timesheet.totalHours}} hours). Approve in Timesheet approval.',
    'Normal',
    48,
    null,
    null,
    'org_reports_to_manager',
    null,
    'role-team-leader',
    'one_open_per_entity',
    62
  )
on conflict (id) do update set
  name = excluded.name,
  active = excluded.active,
  module = excluded.module,
  trigger_event = excluded.trigger_event,
  conditions = excluded.conditions,
  task_type_id = excluded.task_type_id,
  title_template = excluded.title_template,
  description_template = excluded.description_template,
  priority = excluded.priority,
  due_offset_hours = excluded.due_offset_hours,
  due_offset_days = excluded.due_offset_days,
  due_from_field = excluded.due_from_field,
  assignee_mode = excluded.assignee_mode,
  assignee_position_id = excluded.assignee_position_id,
  assignee_role_id = excluded.assignee_role_id,
  dedupe_policy = excluded.dedupe_policy,
  sort_order = excluded.sort_order;
